### ISSUE TITLE
Make slipping on water / bananas not do damage

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#1052]
### Expected Behaviour

Janitor not putting signs down doesn't trigger my health OCD
### Actual Behaviour

Take like 3 damage between every body part which is annoying as hell to fix
### Steps to reproduce the problem
1. lizard clown slips captain, harming him
2. borg beats clown's ass because it's harm

LUBE CAN STILL DO DAMAGE SINCE IT'S INTENTED TO BE ANNOYING AS FUCK AND SEND YOU FLYING

> inb4 git gud and walk every time you see a slightly highlighted tile xDDDD!!!

**Comment by ParagonPrime** [comment]
to be fair, it sorta doesn't make sense that you take damage from slipping on a wet floor and falling on it-

meanwhile, having an electrified club strong enough to incapacitate you for more than 5 seconds and achieving just the same knockdown effect- totally harmless lol

**Comment by Alblaka** [comment]
I have stopped considering slips harmful as silicon, because I would have to space the Janitor every damn round. And the Clown. And everyone else who touches a spray (space with EVA suit and internals set).

It would be nice if slipping wouldn'T deal damage, it feels like a completely pointless mechanic since it's very introduction.

**Comment by Cruix** [comment]
Maybe a small amount of stamina damage but not brute like it is.

**Comment by penguinfisher** [comment]
> Take like 3 damage between every body part which is annoying as hell to fix
> switch to the master race :^)

**Comment by ParagonPrime** [comment]
A tiny bit of stam damage, plus the stun, sounds good
