### ISSUE TITLE
HUD for golems?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#1078]
It would make it easier to discern your original master.

**Comment by ShadowDeath6** [comment]
:+1:

**Comment by Super3222** [comment]
A HUD wouldn't make sense.

However leaving it in your (IC) notes will.

**Comment by 00aquir** [comment]
well, if gangs and all other "special" people can see their leaders, why not golem?
It applies the same thing.

**Comment by Super3222** [comment]
HUD's are generally used for special items that you use for work and so team antagonists don't slaughter their own. Med HUD's detect health, Sec HUD's detect whether you are set to arrest or not, chem goggles detect the chemicals in beaker, and so on.

Specifically GROUP antagonists are exempted by this, because of obvious reasons. Ex: Gang. Ex: Borers. People that they specifically NEED to team up with.

In a golems case, a HUD to tell who's your master is wouldn't make much sense with this medium. Sure, it's a good thought. But really, not everything needs X, because everything shouldn't be done easier for you.

There's a difference between a golem being able to tell whether an unknown is his master or not than a gangster being able to tell if an unknown is in their gang or not.

**Comment by 00aquir** [comment]
And a golem doesn't just need to team up but _must_ follow their only leader's orders, so we could make it "recognizable only if not unknown" if you must, but it would help you not try to constantly track one guy with your mouse across the hallway who is running much faster than you(!) in either direction just to see whether he's your leader while his face is uncovered. You get the idea.
