### ISSUE TITLE
New Torture device

### ISSUE THREAD

**Issue by Greatbigben** [yogstation13/yogstation-classic#1091]
make interrogation actually a little RP friendly.

Got a tight lipped tator who wont talk or give up a name. get the information out of him with this device. Your strap it on a chair like the electric chair and whenever you hit him if gives him RP messages like his hair being yanked out or his teeth being pulled Etc etc. Add in a Progress bar for the one doing the hurting so it wont be spammed and when Ahelped they say "oops". The RP messages will change based on the weapon used. like a wrench will say you  are crushing his fingers or bussing his kneecaps.

**Comment by X-TheDark** [comment]
Brutal, but not sure if necessary.

**Comment by ParagonPrime** [comment]
awesome as shit idea (and apparently based on my recent fun with timegreen :^) ) but would probably be waaay underused because most people here will just say 'fuck arrghpee lol'

**Comment by Notamaniac** [comment]
Or you could just buckle someone to a chair and use the me verb all you fancy, still achieves the same thing.

**Comment by FluffySurvivor** [comment]
"why the fuck would i give you my codes text is not hurting me lol"

**Comment by EMT321** [comment]
Leave this shit on bayststion. It's a waste of code.

**Comment by ParagonPrime** [comment]
^fluffy has it
there's so much amazing shit we could implement for antags- from abducting and ransoming random staff to a cold but effective detective interrogating a suspect

except
"LOL FUQ U WOT IS RP LOL U FUQN RP NORMIE LOLOLOLOL"

the only "torture" that actually has a decent chance of effect is subjecting a phytosian to darkness (it HAS gotten results for me occasionally) and that's because it's built into the mechanics

so unless we create a specific "torture device" that has some very interesting status effects attached to it, this won't work out

**Comment by Super3222** [comment]
If the torture device could slowly deal a set amount of damage to the person strapped to it, while having to be geared by someone else than it'd be pretty good.

You guys are looking far more into the RP perspective and random shit, Ben didn't say this had to be all about RP. He wants to make it RP friendly.

It can still do damage while giving you horrifying RP messages of torture.

Now anyway, imagine the Captain giving you the heads up to use the torture chair. It's actually a good thing and adds another option rather than execution, cyborginization, or letting them rot in perma (gulag).

If they die during the torture, it's not your fault right. You didn't want them to die, they asked for it by not giving you what you wanted. In favor, making them experience more pain.

Expecting to get cloned after you get tortured to death? Nope, you get thrown into the big bad security morgue (PS, you'll never be found there). Actually adds a fear factor to getting sent to this. Additionally, if you actually quit the tough guy shit that got you to the chair, than they might let you off with a bomb collar or excuse you for another lesser punishment than your removal from the round.

In fact, this could be a possible way to forcefully rehabilitate gang members / cultists / revolutionaries. Maybe an extremely small chance, after going through multiple stages within the torture before death.

Also I hope that whoever randomly finds this page realizes that we are talking about a video game and not real life. THIS IS A FREE VIDEO GAME ON THE INTERNET.

**Comment by Time-Green** [comment]
I think this is a good idea.
Of course some people will ignore it and be stupid. But like what paragon said, he tortured me to get the answers out of me.

**Comment by X-TheDark** [comment]
Yeah, you'd need mechanics for dealing damage during torture. In addition, I'm worried about how much this will affect administration ("HELP, GUY TORTURING ME 4NORAISINS, BAN HE"), in addition, it's not like I personally expect people to "comply" with the torture. I've seen my fair share of "Fuck you, I'm off" people who went braindead as soon as someone tried to RP with them in the interrogation room.

I'm going to use the "standard response" for these kinds of things that gets thrown around alot : "If they wanted to play on a server with more RP, they would play on a server with more RP".

**Comment by Notamaniac** [comment]
Also adding a torture machine to ss13 really ruins the lighthearted nature of it all

**Comment by 00aquir** [comment]
Just make the guy blind for undetermined period (blindfold or something else), it would be really uncomfortable for them after a while that they can't see jack.

**Comment by Greatbigben** [comment]
Super has said it best. its not to turn us into REEEE rp but to give another option then the 3 standard ones.

**Comment by Greatbigben** [comment]
@X-TheDark it could be like toxins damage or oxygen damage they are slowly dealt over time. i dont think the damage system wouldnt be too hard to adapt, it can also have a cap of 95% health or something so to send them over to crit you have to WANT to.

**Comment by Kmc2000** [comment]
All the torture you need is at kmc's house o' roundend abuse.

Go see my sig for fun ideas, get cargo to make one so they have something to do.

A torture thing isnt very kid friendly, as a LOT of our players are underge, probably not the beeest idea

**Comment by Greatbigben** [comment]
Its a option it isnt necessary persay to do it. most of our admins are underaged but just take a look at admin chat -.- i think only like 3-4 of us can actually buy a beer in the U.S.

**Comment by ghost** [comment]
or you could just hit them

with your

weapons

that you have

**Comment by FluffySurvivor** [comment]
then you get banned for shitcurity or whatever

**Comment by ghost** [comment]
if you have a fucking machine that lets you tear out people's teeth and are free to use it as security nobody's going to ban you for going LOOSE CANNON as the detective during an interrogation and thwacking the roboticist with a toolbox while demanding his PDA codes

**Comment by Greatbigben** [comment]
Anyone still interested in this idea?

**Comment by FluffySurvivor** [comment]
If it deals damage-over-time and doesn't require captain's permission then it's 10/10.

**Comment by EMT321** [comment]
There are infinity easier methods of torture already extant. Glass dragging/tabling/morphine. Or just waterboard em in a cold shower. All of those get results because they do real damage, and they take time enough for people to respond.
