### ISSUE TITLE
REMOVE REVENANT SHOCK ABILITY

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#1119]
### Expected Behaviour

Revenant is a sneaky, opportunistic, covert antag that takes advantage of the conflict between others to feed off the dead that ensue. Its main strategy is coercing others into killing potential victims for it to feed on in exchange for having an ethereal ally and scout.
### Actual Behaviour

Chief tactic of Revenant is to spam the ability that shorts out lights and kills you within 3-4 shocks. Feed on resulting corpses. Profit.
### Hao 2 fix

I actually don't want the ability removed- I want it changed to suit a better role.
Instead of using it as an offensive weapon to actively kill people to succ dry of lifeforce, it should be an opener- if you've befriended someone on the ground, activate this ability in another room, stun the occupants, and let your friend rush in and kill them while they're down.

This can be achieved one of three ways, or by a combination:
1. Decrease damage severely, and possibly increase stun time. Makes it more of a utility than a weapon, so this is actually the option I'd prefer most, combined with 3.
2. Increase cost severely
3. Increase cooldown severely
4. **Make it not work on lights that have already been blown.**

**Comment by X-TheDark** [comment]
In my opinion, the main problem with revenant is that he's too hard to deal with. Unless he's draining someone, he doesn't stay in place (and revealed) nearly long enough for crew to be able to kill him and with the recent bugfix of him no longer randomly dieing, it's become all the more clear that that's the main problem, you just can't kill him unless he's dumb enough to try to use ability/drain in front of 5 people and even then, you're probably going to be able to get away, unless the guy has laser rifle.

I think Overload Lights is fine, it doesn't need to require revenant to befriend a traitor, he does that plenty enough already:
- Blocked by Insulated Gloves;
- Turn Off/Remove lights;
- Can be mitigated by a simple trip to chemist to tell them to give you bicardine or another burn healing chem;
- Requires at least a corpse or two to actually get;

Increasing cooldown doesn't seem like a bad idea, though. But I'm not sure if Revenant needs to have it's only offensive option removed and be changed into a "coop only" antag. I like the fact that you can just start sowing chaos and harming people.

**Comment by Groudonmaster** [comment]
> just have the chaplain bless everything

**Comment by ghost** [comment]
break light

revenant can't shock

also, the shocking lights ability does tops 15 damage at worst get good

**Comment by ghost** [comment]
also yes, it already doesn't work on lights that are blown

**Comment by X-TheDark** [comment]
I assume Paragon meant that the same light cannot be used twice (if you Overloaded it, it's done).

EDIT: Also, it does 25 base damage to unarmored people. Not sure how armor interacts with the burn damage.

**Comment by ParagonPrime** [comment]
^
You can overload the same light numerous times, I believe

Also, 15 damage is pretty heavy, especially since it slows you down and makes you more vulnerable to the rev anyway

Adam, you're always the one advocating secondary antags being kept secondary. That's what I'm trying to do here- make Rev a little more about subterfuge and manipulation and a little less ability-spam.

**Comment by X-TheDark** [comment]
The thing is, for subterfuge and manipulation, you need a carrot and a stick. The revenant currently has the sticks (EMP, Overload Lights. Defile is shit, though), but absolutely no carrots. How would you intend the Revenant to entice people to cooperate with him? Just hope for RP?

EDIT: I've thought about giving Revenant some ways to "empower" people, but Adam shot that idea right down and I'm not sure I disagree with him.

**Comment by ToGWtF** [comment]
Problem is,  revenants sometimes get objectives NOT to harm the crew at all and only feed on the dead. This objective is a free greentext, and with removal of the murderbone rule no one gives a fuck about that objective anymore

**Comment by ShadowDeath6** [comment]
Make defile have a chance to throw people around so it can actually hurt people when

**Comment by ghost** [comment]
consider the following for revenant-

Defile is now a targeted spell on humans or mobs that throws some, with a maximum of 15,  moveable objects in view radius towards the person revenant used defile on, like dark matter reaction

Defile breaks windows 100%, not just doing damage to them, like a fireaxe hit.

Defile has a random chance to emag doors or APCs that it's used on.

-Malfunction no longer disables bots, so they can use their emag abilities immediately.

-Overload lights is unchanged because it's completely fine as is.

Add goon's possess ability, for 100 essence allows the revenant to take control of the object possessed for thirty seconds and move around and attack things. Can range from simply taking control of a laser or tazer in the middle of a firefight during gang and being a massive dickbag to everyone in sight, to taking control of an extinguisher, bashing open a plasma tank and popping the lights with overload lights to ignite it. Revenant is revealed and immobile for ten seconds after ability expires.

Make salt applicable to floors in much the way ash piles appear when paper is burned, when the ground is clicked with a salt shaker or salt is sprayed from a spraybottle. A revenant crossing salt is stunned and revealed briefly. Salt is scuffed and the salt line broken when someone runs over it, but not if someone walks over it.

**Comment by ShadowDeath6** [comment]
> defile breaks windows
> removing a key strategy of revenant

rrrrreeee

**Comment by ghost** [comment]
defile already damages windows

**Comment by ShadowDeath6** [comment]
Yeah but it doesn't guaranteed break them

**Comment by ParagonPrime** [comment]
Sticks applied to others often act as enough convincing. Revs usually play ball when I promise them a bodycount as a traitor.

Or, we could add some utility abilities that do less for the revenant than they do for others.

Here's some ideas:

-Ethereal hijack: High-cost, low-cooldown ability. Acts like an emag, can be used on any airlock. Useful for obvious reasons.
-Darkness shroud: Envelops a chosen person in a purplish ghostly armour that slowly (SLOWLY) heals them, reduces the damage from lasers, and reduces weaken and stun from disablers and tasers.
-Unholy blade: High-cost, high-cooldown. Bestows a robust purple sword unto a person. If they crit anyone with it, it automatically gives the Revenant the Essence. If the person drops it, the sword disappears.
-Other shit you can come up with

Not to mention the Revenant's innate reconaissance ability and the bonus of having an ally to automatically kill those critted enemies of yours lest they somehow get healed.

**Comment by ShadowDeath6** [comment]
Maybe have defile randomly set up walls on floors so it actually impedes movement
Also the EMP spell has a low chance to emag things in range

**Comment by ghost** [comment]
that sounds retarded paragon

revenant is already absurdly useful for helping other antags it shouldn't be built around it entirely because it's a malicious ghost that turns the station against you, NOT a buddy for traitors

**Comment by ShadowDeath6** [comment]
make defile throw shit around like adam said
I want flying pens thrown into people

**Comment by ParagonPrime** [comment]
well then figure out some way to make revenant somehow fucking fit into what it was meant to be without being a direct threat or being 'ABSURDLY USEFUL'

jesus fucking christ stop calling other people's ideas stupid and then not having any better ones of your own

**Comment by ghost** [comment]
i did have better ones than yours because they fit into what revenant is meant to be-a threat that uses the station against people, and i mentioned above how

it's not meant to be buddy buddy with antags as it's entire mechanic, buddy buddy with antags is just part of it-it can just choose to make a bad situation worse by showing up and casting malfunction in the middle of a firefight next to an arcade machine

**Comment by ParagonPrime** [comment]
the key point is that revenant is OPPORTUNISTIC
it doesn't engage directly
it's meant to be stealthy, sow chaos and disarray and side only with those guaranteed to feed it more fleshlings for the eatings

it's meant to drift around conflict sites or potent potential conflict sites and interfere however it can to ensure more fatalities- not actively hunt down solitary maint-crawlers who would have been totally fine without it flitting in

hell, at best, it can even CREATE the conflict- i think you once mentioned that acting semi-antaggy due to revenant whispers was considered legit, and i wholeheartedly approve. enticing someone to go on a murder spree for your food is a great idea.

rev shouldn't be a buddy, but it should have incentive to not just be a ninja that can pass through walls and eats people rather than APCs. that's a tricky balance to get, but let's try.

**This is the first step.**

**Comment by ghost** [comment]
no  paragon, this is the first step to a 

# shit idea

revenant DOES engage directly

it is not meant to be a stealthy antagonist- it is an antagonist that can either be played stealthily and subtly or loudly, showing up in the middle of combat or a busy medbay to be a gigantic asshole to everyone, spamming EMP's and lightning bolts

both of these are completely fine

it's meant to both drift around conflict sites OR hunt down solitary maint crawlers, because forcing revenant to ONLY have one playstyle is a BAD IDEA

because let's look at most other antagonists who only have one playstyle-they're universally bad

every 

single

one

is bad

and boring, for both the crew and the antag, barring certain circumstances

revenants are fine as is and lightning bolt is a perfectly fine ability for it's cost and easily countered by turning off the goddamn lights with a click of a goddamn light switch.

revenant is not just an opportunistic antag-the opportunistic thing about revenant is that it shows up to eat corpses when it appears

until the late game, when a revenant is sitting on a pile of essence, it doesn't have the resources TO ability spam to the extent that it can kill someone with lightning spam, especially because lightning spam contrary to popular belief does not actually do 25 damage, but 10-15 and sometimes not even that-it can take up to eight to ten lightning bolts to crit people, which is a massive waste of essence unless done in the middle of a firefight

by it's own mechanics revenant prevents it being an antag that floats around and picks off solitary maint crawlers because it simply doesn't have the resources to do so until the late game, and all you would change is make revenant more boring by preventing it from doing anything in the late game either

it is a bad fucking idea, paragon, because revenant is already what you are trying to do, and your attempted 'fix' to it is actually going to make it far worse for everyone, because A. either you give them your stupid, edgily named abilities that doesn't fit with the theme or intent of revenant whatsoever because it's not a teamwork antagonist and it's not supposed to be buddy buddy and it's not supposed to exist to help murderboning wizards by giving them absurdly powerful armor and weapons, in addition to weapons that instantly kill you when you're in crit or B. you nerf it's one actual combat ability that isn't entirely situational and leave revenant with no actual ability to cause casualties aside from using whisper and hoping someone listens, or using EMP and hoping an arcade machine blows up, a door gets shocked on someone with low health, or a medibot injects someone after being EMP'd, with no abilities whatsoever to cause casualties

do you see how this is a fucking bad idea, paragon? revenent would be basically powerless without a partner, which is a stupid idea and NOT what you should be aiming for because unlike abductors or cult it's not a teamwork antagonist that requires a competent buddy to do your work for you in order to get anywhere, it's a solo antag that can make bad situations worse by teaming with an antagonist for greater effectiveness or go on it's own and cause chaos with it's lightning bolt abilities, EMP's, and thus drain essence through situations it causes

you remove or nerf lightning bolt, it has no actual power to carry out threats it makes aside from VERY situational shit and thus cannot cause situations on its own, and is reduced to being a ghost that floats around spamming transmit in the rare hope that someone is retarded enough to listen to it, because it's very rare that people you transmit to actually pay off unless you're a very good liar and convince the HoS it's rev and that he needs to start executing people

it's a bad fucking idea, paragon. It's the first step to a pile of absolute **shit** and I hope that sunk in for you now.

**Comment by ShadowDeath6** [comment]
How to fix revenant:
Make malfunction have a low chance to emag borgs and give them lawset to kill everyone but ghosts

**Comment by ShadowDeath6** [comment]
Also: insu gloves give you full immunity to shock

**Comment by OurDreadFather** [comment]
I agree with Adam in that Revenants arent an antag companion. Its not co-op SS13. Sometimes theres not an obvious traitor to follow. You have to have the ability to create bodies yourself. Also, you cant convince a non-antag to kill people for you as a revenant.

I do feel like defile is damn near useless tho. It needs to instant break windows. I like the throwing shit around idea as well. Because all it does right now is stamina crit people after 4 consecutive hits, and you cant even drain them when they're in stamina crit.
