### ISSUE TITLE
Mecha Additions

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1123]
Mecha buffs to make them more versatile.
1. Add a printable mech flamethrower, which draws from the mech's battery charge to fire off a flamethrower.
2. Make mechs atmos-proof, so that you can survive hot or cold temperatures when in a mech. Mechs still take damage from hot or cold air, so it's just a temporary thing.
3. Add to the traitor uplink a hacked exosuit laser weapon, attatchable to any exosuit that fires a solaris laser. Cost is 11 TC.

**Comment by X-TheDark** [comment]
1. I don't think adding a flamethrower will do anything to help mechs.
2. Mechs already do this (activate the internal tank).
3. Eeeeeh, not sure how I feel about adding yet another weapon to traitors, especially when it can be mounted on all mechs. Plus, it won't even be used much, because...

In my opinion, mechs are just garbage overall (with Odysseus being the only one to provide actual utility and even that is not used, despite being a roundstart mech). I've never seen a combat mech being built (maybe the cost of the mechs is the real issue, eh?). You can easily run away from them, but if you don't have the tools to deal with them (Ion, Laser), they are pretty much immune to anything you can throw at them.

**Comment by ghost** [comment]
Mech flamethrower is good for riot control and for fighting blobs.

**Comment by FluffySurvivor** [comment]
there's already an incendiary mech carbine

**Comment by X-TheDark** [comment]
What about the Flashbang Launcher?

**Comment by ShadowDeath6** [comment]
Clusterbang is annoying to get because it needs illegal 2 and sci never gets shotguns outside of war ops and blob 
Mechs are already immune to all atmos, except MAYBE plasma fire
Mechs have a hades carbine for fire, albeit it's less plasma-y than flamethrowers

The only reason robotics never makes mechs is because R&D whores materials consistently every single fucking round

We actually might want to make not whoring materials in sci a rule

**Comment by X-TheDark** [comment]
Mechs protect against plasma fires, I checked.

**Comment by FluffySurvivor** [comment]
> The only reason robotics never makes mechs is because R&D whores materials consistently every single fucking round

Wrong. 

Robotics
3.3.1: Do not create mechs for your personal use. Contact the appropriate department and ask whether a mech is required.

**Comment by ShadowDeath6** [comment]
Literally no admin ever enforces that rule because it's so dumb
If you put the time and effort into making a mech you should be able to use it
The only problem is that robotics almost never gets the chance to make mechs because R&D steals materials

**Comment by ghost** [comment]
the rule basically exists to prevent making gygaxes to validhunt in and with the removal of the murderbone rule that rule is irrelevant for that purpose because you're completely free to get in a gygax you made and go beat up a traitor with an esword and ebow killing everyone in sight

anyway the hades carbine fucking sucks because the hotspots from fire fade almost immediately and the bullet does barely any damage

either make the hades carbine fire dragonsbreath buckshot rather than just one dragonsbreath pellet that does almost no damage or add the flamer

**Comment by OurDreadFather** [comment]
The mech personal use rule is 1 part valid hunting prevention and 1 part making sure the robos don't waste all their metal making round start Materials 1 Ripleys and fuck off for the whole rest of the shift. The reason you don't see combat mechs often is because a series of events have to occur first. You need a miner to go mining. Then you need that miner to not die. Then you need that miner to actually come back with diamond and uranium before the shuttle is called. R&D has mineral priority because research is required for mech parts and boards. After RND gets their minerals and does their research, they will spend some time making upgrade parts and upgrading the station. This is the optimal time for a competent roboticist to go into the RND lab, eject some minerals, and make the combat mech his heart desires. But a competent roboticist is rarer than unicorn tears. So instead, you get a roboticst that ejects ALL of EVERY mineral and puts it in a fabricator and then makes a Phazon chassis without ever having secured bluespace crystals or an anomaly core.

Even when the planets align and you get 20 minute diamonds and uranium and someones doing R&D and upgrades your machines and the robo isn't horrible, its now 30 min into the round, which means antags have acted up and the shuttle might be called soon or already is. Its still gonna take a good 5 minutes to print the parts and make the mech. Even with Materials 7 and Femtos, the cost of mechs is still quite high so there might not be enough diamond for a Gygax or enough uranium and silver for a Durand, and there definitely isn't an anomaly core to make a Phazon with.

That being said, when you do get to build a Gygax, its incredibly robust for just about any purpose. The only worthwhile mech weapon that you'll realistically have available is the Solaris Laser Cannon. The Gygax is sufficiently fast to keep someone in their line of sight long enough to hit them with the laser cannon, at which point they are even slower than the Gygax. You can swap out the default battery for a bluespace battery so that you never have to recharge. They have toggle-able internals so your space proof and (I think) fireproof. No one knows who you are in the Gygax unless you talk. Your practically stun immune and because of this, wizards are an absolute joke vs. a mech.

So to comment on Adams original suggestions:
The flamethrower is an OK idea. Xrays will always be a better use of mineras on Blob.
They are already atmos proof. Maybe not fire. Im not sure.
The traitor Solaris is retarded because any time that you could make a combat mech capable of having a Solaris, you could just print one from the fabricator.
Consider making a traitor item that would forcibly eject a mech pilot and override DNA locks. Should facilitate stealing a mech.

SORRY FOR THE WALL OF TEXT.

**Comment by OurDreadFather** [comment]
Also, R&D doesn't whore minerals. Robos have R&D access, and scientists don't have Robo access. Robos could easily go grab minerals for their fabricators and the scientists couldn't do anything about it. The problem is that when they do grab minerals, they almost always empty the protolathe of ALL minerals. They dont need ALL the minerals. The only things they need to print from a fabricator that needs minerals is the mech chassis, cyborg upgrades, mech attachments, and a battery upgrade for the mech since only ones from fabricators work in the mechs. That means they should have a specific item in mind and only grab the minerals needed to make it. Also, R&D has a higher mineral priority.

**Comment by ghost** [comment]
Scientists will usually beat the shit out of the robo for taking minerals from R&D and possibly get banned on if they killed them (they usually do kill them).

I do have that mining rework in the back that makes mining way more fun, meaning more minerals on a regular basis.

**Comment by FluffySurvivor** [comment]
> viros can be permahealing spaceproof stun-resistant sport cars with no rule preventing it
> 
> genes can be stun-immune spaceproof all-seeing invisible mass-manipulating monsters with no rule preventing it
> 
> scientists can be fucking commandos by having 10 laser cannons wormhole guns etc with no rule preventing it

robos can't have cool mechs because FUCK THAT JOB IN PARTICULAR

**Comment by Robertruler77** [comment]
Robo and Rnd get the message simultaneously and robo is closer. Robo is my most played role and it's easy to get minerals cause robots basically Borg, wait for positron tech/minings ripley order/do RnD thenselves. Is piss easy to drop everything and make a mad dash for cargo.

Soon as you see the alert, go get the stuff. No miner want the suits? Chuck a positron in and let the hop sort access.

It's not difficult.

Surprisingly enough, it's not.

**Comment by X-TheDark** [comment]
@FluffySurvivor 

To be gun-wielding commandos, scientists need Firing Pins and those aren't available readily.

If I remember correctly, Geneticists still need quite a bit of time to get ALL powers (because of how low the chances are for Hulk, for example), plus, I'm pretty sure Hulk is not considered human anymore (correct me if I'm wrong), other than that, yeah, Geneticists can make themselves ridiculously strong.

Viro, yeah, you can make viruses. 

But then again, those 3 jobs are the only ones that can actually make something that doesn't rely on any other department (except guns, those need pins/mats, but RnD can make Rapid Syringe Guns easily enough, which are very good for being guns). Again, the problem being, for the most part, everything in Science is self-sufficient. You can get some pretty good research levels without ever needing Mining, but Roboticist can only make 2 mechs at roundstart - Ripley and Odysseus.

EDIT: In all honestly, mechs as a whole (as I ranted before) just suck. You either run away from them, get Ion/Laser or die. The only really, REALLY fun weapon a mech has is the dreaded Grav Catapult. That is fun as all hell to use on people.

**Comment by ShadowDeath6** [comment]
Also a good mech will curbstomp any hulk, healing virus, or anything that isn't an HoS with an ion rifle and extremely good dodging capabilities
