### ISSUE TITLE
Proposed wiz changes to make it more fun than pure murderbone and disable cheese

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#1139]
Change lich to soulguard-on death unless gibbed, respawns the wiz on the wizard shuttle, naked. Also breaks any summon item bindings they had prior. Only works once, is passive, remove phylactery system. 

What this does-no infinite lich cheese, no skeletal spaceproof chemproof wizards. Uses up a spell slot like RISE but is only useable once-essentially a safety net for inconfident wizards.

Prevent Ei nath from being taken if magic missle or repulse is taken. Just, kill mm ei nath, it's universally hated.

Make Ei nath do 600 brute damage to all limbs and eject the brain from the target's body rather than gib, so it's still extremely lethal but people can actually be cloned if the brain is put back in the body (which is doable in one click.) 

Replace necromantic stone with animate skeleton-used on a corpse (Corpse does not need to be inhabited, unlike as it is now), causes a skeleton to shred out of the corpse's body. Control is offered to ghosts-if no ghosts take it is given simple mob AI-the greytide drone AI that lets it fire weapons and shit. Comes with a claymore but no roman shield since claymore + roman makes it immune to all forms of damaged, ranged or melee. Spell has ei nath cooldown but requires the wizard to be standing next to the corpse as it is also an inhand spell.

Nerf staff of animation to only have a cap of 20 animated items per staff. Still lethal, but no longer grillespam roundender 4000.

Add Clown Curse, basically a direct rip from goon. Same cooldown as ei nath-when used, makes the victim a cluwne, a green ur-clown in unremovable, disgusting clown gear and an extreme form of clumsiness that makes anything a clown could not normally do go wrong 100% of the time, and changes all speech to strangled honking. The only release is death or borging. Truly dastardly.

Give wizards who take the soulstone belt the cultist commune verb, so they can talk to their goddamn constructs.

Give mutate oldtk-the shit that let you magic things at people even through cameras. 

Adjust blink to teleport you in the direction you're facing.

Re-add summon events but remove lava floors from it.

Re-add summon magic, but have it create antagonists with the objective to escape with the wizard and the wizard alone to be his apprentice-other false apprentices must be eliminated. 

Grant staff of change 'madness' to staff of changed crew-everyone looks like and sounds like the wizard to them, and random hallucination wizards appear and hallucinated crew-wizards will randomly shout magic words or fire off imaginary spells-only to the staff of changed crew will this look like it's happening. Staff of changed crew are then given free license to kill the wizard, but revert to normal after three to five minutes-the more deadly the transformation the shorter the reversion time is. The intent is to make staff of changed crew hostile to the wizard-but everyone looks and sounds like the wizard, so this can spiral very badly. But, transformations aren't permanent, so for one restraining or locking down changed crew will let them revert to normal, and also your round isn't over if you get shot into a butterfly.

Staff of chaos no longer fires just any spell bolt-instead, it fires off randomly any offensive spell in the wizards arsenal aside from ei nath as well as spell bolts, so chaos staff wizards can range from harmless to suddenly being electrocuted because electric bolt spell just randomly fired. Give staff a longer cooldown in exchange.

Add staff of doors and staff of healing to buyable wizard gear.

Increase spell cooldown on blessed tiles, and being hit with the null rod or beat with the bible stuns and adds 10 seconds to all spell cooldowns-if ei nath was at 59/60, now it's at 49/60.

Ranged manipulation spell-grants the wizard two extra, floating magical hands that allow him to attack or use items or retrieve items at range. Hands also do 10 damage a hit and can hit three times as quickly as a punch can attack, and on grab intent, agressive grab then throw the target at wherever the wizard has prior selected as a target-the thrown target can smash through a total of one wall before coming to a halt, and the destination cannot be space.

EMP spell will no longer affect the wizard's headset, and can randomly emag things.

The wizard will have his spell cooldowns reset on entering the chapel.

Firing a gun as a wizard will automatically subtle message the wizard how much of an unrobust scrub they are.

The scrying orb no longer makes the wiz a pure ghost-instead, they become a wizardly shade, almost transparent but not quite, with incorporeal movement and the inability to attack. Basically means the wiz is no longer completely invulnerable when using scrying orb, as getting shot with six lasers in orb form makes you take sixty burn on returning to your hody, et cetera. If a non-wiz uses the summon magic orb, they take steady damage, similar to astral journey rune, but in cloneloss.

**Comment by ToGWtF** [comment]
No

No

No

No

Eh

Yes

Yes

Eh

Eh

Eh

Eh

Eh

Eh

Yes

No

No

No

Yes

No

Eh

**Comment by ghost** [comment]
Explain the nos please

**Comment by ShadowDeath6** [comment]
I'm nerfing ei nath to kill like bolt of death instead of meme gibbing
Also I'm not even sure if constructs made by wizzo are cult
Summon events is fun I guess
Summon magic is bad, no. I've seen a round where a wiz summoned guns and one of the antags shit on everyone after wiz died. Encouraging crew on crew fighting is baddu

**Comment by OurDreadFather** [comment]
Changing lich to a one use spell is perfect.

Loving the Ei Nath incompatibility with MM. Iv never used Repulse so I cant comment on that. Consider adding Time Stop too.

Removing the gibbing from Ei Nath is also 10/10.

Staff of Animation only having 20 uses is a little harsh. I would say it would be better to put it on a CD, where you get a charge per 30s or 1m. That way, its viable no matter how long the round lasts, and it still prevents instant grill army. No idea if thats possible with a staff. If not, consider making it a spell.

Clown Curse sounds pretty great.

Wizards should have been able to talk to their constructs from day 1. Fixing that is a great idea.

Loving Mutate not giving hulk. Old TK seems like a good replacement.

Yes to summon events.

Yes to summon magic with sole apprentice antag objectives ala Survivor. That sounds amazing. Also directs the spell usage at other antags rather than some asshat barnyarding the entire station.

Absolutely loving the staff of change madness idea. With that implemented, I could change people into extremely cool and lethal stuff without having them immediately valid the shit out of me. Im NOT loving the 3 minute deconversion. I get that some people dont want to be a syndie borg or monkey or alien. Some people also dont want to get murdered by the antag, but thats just part of the game. On wizard rounds, you will NOT have a normal shift. And being a monkey is far better than getting MM Ei Nathed. It especially makes no sense when you realize the percentage of their crap that will still be where it was dropped when they were changed is roughly 50% to 0%. You can be as happy as can be to be human again, but when you  find nothing left but your uniform and shoes, it's kinda a moot point.

Im all for increasing the chaplains influence in cult and wizard rounds, and against revenants. All the suggested religious changes sound amazing.

**Comment by FluffySurvivor** [comment]
I see a bunch of nerfs. 

Wiz needs a rework, not nerfs.

**Comment by Super3222** [comment]
Do you realize people that EI NATH was suppose to be overpowered. Yes, its unfair, completely takes people out of the round, and makes you want to end the pain when a wizard pairs it with MM. That's the point. Wizards aren't suppose to be easy and fair enough to kill. They are suppose to be a powerful antag because they are the ONLY antag when it comes to wizard mode, unless they use their antiques to forcibly create allies or monsters.

600 brute damage to each limb would do 3.600 damage. But there's literally no point towards doing that, they wouldn't be able to cloned and you'd need to cut open their head to bring out their brain. Unless they are on T4 cloning. Death sucks on SS13, but it makes you learn from it a lot so you don't sit out again.

**Comment by ShadowDeath6** [comment]
You don't learn anything from being MM + Ei nathed. It is either forcing you to be borg or permanently removing you from the round. No other spell will end your round instantly.

**Comment by LesVegetables** [comment]
if you don't want wizard to be a murderbone fest they need to spawn with more objectives than "steal a handtele lol"

They have nothing to do if they get a steal objective past like the first 5 minutes

**Comment by ghost** [comment]
@Super3222 

Okay so the ei nath thing is only a nerf in that it doesn't damn the person to borging.

The body takes 600 damage to every limb, preventing defibbing. Like the grinder does.

The brain is ejected from the body, so the wizard can still pick it up and space it if he wants the person dead, just like he can now, since not picking up the brain = angry borg.

The brain, however, can just be put back into the body, no surgery required, because clicking a debrained body with the brain puts the brain back in it.

So literally the only change to ei nath is that it's deadly as shit but not permanently round fucking in that you're FORCED to be a cyborg. For a cyborg or AI it does the same as  it has always-drop an MMI.

@FluffySurvivor There are, at maximum, four nerfs. The ei nath one (to prevent mM ei nath, and also to prevent body destruction while keeping ei nath as absurdly lethal as it is now), the staff of animation one to prevent grille armies-the number could be increased to fourty, if you wanted that. The lich one, and the chaplain one.

The rest are fundamental changes how spells work to make them actually DEADLIER, and a couple new, powerful spells. And one meme.

Specifically, you get two new, absurdly lethal spells, allows the wizard to talk with the fucking constructs he makes with the soulstone belt so that he can actually communicate and order them around rather than them getting lost because they can't hear him on the radio, a buff to most unused spells such as the EMP one, a buff to mutate, a buff to blink, a buff to staff of change while making it not permanently round fucking, and a buff to staff of chaos.

Wizard is just as powerful as he is now-if not more so-while having more variety to his spells. That's the intent of this stuff.

**Comment by FluffySurvivor** [comment]
MM einath can be countered by not meleeing the wizard, juking the mm then engaging. 

if you melee him you deserve to be gibbed

although i agree mm CD is too low

**Comment by ghost** [comment]
repulse einath

also what about the other stuff

**Comment by FluffySurvivor** [comment]
wiz needs some actual thematic objectives/goals so he isn't just a glorified traitor

staff of ani cheese is too fun pls don't touch
