### ISSUE TITLE
Give medicals cloning acces

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#1167]
### Expected Behaviour

Geneticist are competent and clone people
### Actual Behaviour

They are autistic or dead

Please just give medicals acces to the cloner

**Comment by Super3222** [comment]
Bad idea. Don't step over job restrictions just because the people are incompetent. That's literally their own fault.

And genetciists are generally smart, because the people who just come on to murderbone/greytide won't figure out how to use this job.

So because chemists are usually antags or get killed, should medics be given chemist access?

You should just ask the CMO to give their medical doctors cloning access or tell an AI to activate the emergency thingy with the door.

One more thing, medical doctors get cloning access with a skeleton crew.

**Comment by Rocks4Free** [comment]
> Don't step over job restrictions just because the people are incompetent. That's literally their own fault.

So because geneticists are incompetent then easily-cloneable players should deal with staying out of the round? Their incompetence doesn't only affect them.

> So because chemists are usually antags or get killed, should medics be given chemist access?

Chemistry doesn't bring people back into the round and doesn't pertain much to the job of a medic. Most healing chems can be found within medbay.

> You should just ask the CMO to give their medical doctors cloning access or tell an AI to activate the emergency thingy with the door.

And if there is none or the CMO refuses? It would just be much easier to give medics cloner access by default instead of needing to break in or get the CMO/AI involved. If the job of a doctor is to heal people, why not give them access to cloning?

> One more thing, medical doctors get cloning access with a skeleton crew.

So, why not all the time?

**Comment by ShadowDeath6** [comment]
I usually just bolt cloning open as AI anyway

cloning is just an annoyance to the geneticists who want to mess around with hulk or whatever powers, why not make their lives easier by making cloning someone else's job and saving time because genetics is usually dicking around and they abandon their post after they get powers anyway

**Comment by Time-Green** [comment]
Medbay needs a redo, map-wise

**Comment by Super3222** [comment]
> So because geneticists are incompetent then easily-cloneable players should deal with staying out of the round? Their incompetence doesn't only affect them.

Yes, Rocks4Free. Death sucks in SS13, but it makes you learn from your mistakes so you can better adapt to the environment. That's how survival games work. It's a punishment.

> Chemistry doesn't bring people back into the round and doesn't pertain much to the job of a medic. Most healing chems can be found within medbay.

Yes..? That was an example that medical doctors shouldn't be gaining access just for situation X and that same situation is what another job is suppose to carry out.

> And if there is none or the CMO refuses? It would just be much easier to give medics cloner access by default instead of needing to break in or get the CMO/AI involved. If the job of a doctor is to heal people, why not give them access to cloning?

"So much easier", yeah if you want something that's not being done on this game. You do it yourself Rocks4Free. Let me break down medbays jobs for you.

The job of a doctor is to heal people, you got that part correct.
Whether it be while they are councious, unconcious, bleeding to death, or recently died (which is why a defib is in the surgery room, well half the reason).

The job of a geneticist is to research the different genes of a human (research part) and than manage cloning (which is the medical part). They manage the DEAD for GOOD people, who can't be defibed / husked (if cloning is upgraded). This is when medical doctors can't do anything.

> So, why not all the time?

The first sentence I wrote in my earlier reply.

**Comment by AsV9** [comment]
@timkoster1 

> Medbay needs a redo, map-wise

Yeah hang on mate.
