### ISSUE TITLE
Yog should rebase with TG

### ISSUE THREAD

**Issue by Bawhoppen** [yogstation13/yogstation-classic#1205]
I'm a /tg/ coder, Its been some time since the Yog last rebased with tg, so I had started coming over to the server and trying to convince you to do so in OOC, and I think I convinced quite a few people already it would be a good idea, but someone suggested I make a github issue for it to get everyone's attention.

Anyways in the time since you were last in sync, tg has made numerous code and feature additons and improvements, and while you have ported quite a few features, I think it would be overrall better if you just rebased, as some of the features are extremely hard to port over, and you'll spend more work porting than just porting back in your unique features.

Rebasing would be pretty simple process, tg code is obviously already playable as is, so all you'd have to do is port over the most critical unique features right away, such as your admin ticket system, This would be pretty easy and could be done in a few minutes. (matter of fact for the ticket system I bet you could just copy-paste)

Then you can still keep any other unique features you want very easily, I'd recommend making a seperate folder for unique Yog features and things you disagree with, and if you did that, you could also stay up to date much more easily.

Overall I think a rebase would also be enjoyed by your playerbase if it were to happen.

Also heres some notable unique features you would gain off the top of my head: Map importer, Dismemberment, Pixel projectiles, Clockwork cult, Cult overhaul, Lavaland, Tons of new nukeops shit, Countless code improvements, and a ton of smaller quality of life improvements. Any of which you don't like, of course, could easily be disabled.

**Comment by ToGWtF** [comment]
Heya, talked with you the other day! I'm on the fence about a rebase, but would be okay if the decision was made. (Shit, maybe even a yearly rebase? Our last was one June 2015.)

On one hand, all them background updates that we would no longer need to port when we stea-.. port other content from you. Specifically, simple animal AI and the Action Buttons you use.

On the other hand,  we'll just be a /tg/ clone with only a handful of truly unique major changes. I always felt weird about porting features you guys come up with, and when we do /usually/ proper credits are given, because it was YOUR work. I get that's the nature of being open source, but I feel like idk we're riding your coat-tails.

On the third hand that mutated and grew out of my chest, you /tg/ coders are wizards.

**Comment by Bawhoppen** [comment]
I think that unique-ness doesn't come from the code and features your using, but from the players and community who are using it, and personally I wouldn't think about it in the way of "riding our coat-tails", but moreso of trying to make the game experience as enjoyable as possible by using new features and changes.

**Comment by oisin100** [comment]
Im quite happy with our Codebase as it is, Yogstation has been separated from /TG/ for so long it could almost be considered another codebase, And its nice to be something different then /TG/

If someone wants something ported from /TG/ it doesent take much for them to ask.

But maybe i'm just stuborn, there's nothing i really want from /TG/ at this present moment.

**Comment by EMT321** [comment]
A limited rebase could be nice. There's some TG aspects I'm not as thrilled with, such as science and lavaworld, but there are plenty of items (syndicate and otherwise) we could stand to.

**Comment by ShadowDeath6** [comment]
While tg has a lot of interesting features, it has a lot of features I dislike, and our server's codebase is still going somewhere, albeit not as quickly as tg's. Like Oisin said, it's not hard to port the things you want, and taking everything from tg and removing the things we don't want is more of a pain than porting the things we do want.

**Comment by ghost** [comment]
It'd be a good idea to take /tg/, put our features in a separate folder so we don't lose them, implement them into the /tg/ codebase, and then dig through /tg/ and remove the shit that wouldn't work on our server, like lavaland or /tg/xenos or holoparas or anything from their science.

Rebasing entirely is a bad idea, because we'd just be a /tg/ clone-and despite what you say, when 'its the players that make a server what it is' and 90% of those players are mindless powergamers, we're just a /tg/ clone.

**Comment by Bawhoppen** [comment]
I don't want to be rude but I think you underestimate how many countless both large and small things you'd have to port, whos code now also differs quite a bit from yours making it even more difficult to port, now from what I hear, correct me if I'm wrong, but theres not that many unique features you would need to port back, and, like I said, from what I understand, most of them would be pretty simple to port back and probably could be done in a few hours. I don't think there is actually that much stuff you'd need to disable of tg code, and disabling those things would be pretty easy, disabling lavaland is like a 3 line change, to remove holoparasites you just need to remove them from the uplink, etc and etc

**Comment by Bawhoppen** [comment]
Also you said our science, what do you exactly mean by that? If theres any R&D recipes that are disagreeable, again its like 1 line to comment out disable them each.

**Comment by X-TheDark** [comment]
Indeed, the biggest problem with rebasing is that we really don't know what unique features we have (other than things like borers, cybermen, admin tickets).

There are a few hurdles to clear before this can even be considered:
1. Gather Council's opinion on this, as they are the supreme leader entity of Yogstation, if they are not on board with the idea, it stops right there.
2. Gather playerbase opinion. We'll need to see what our community thinks of this idea.
3. Run a TG-FOR-A-DAY project. We'd need to host tg-station version (unchanged) on our server for a day or two to see what the people think of the whole thing.
4. Obviously, try as best as we can to gather whatever features we have to see what we need to port, as well as list of things we will not keep.
5. **Manually work/adjust the map**. Our map is different to /tg/'s. We have some rooms they don't and mostly, we removed LOADS of firedoors that tg has. Obviously, this need to be done because of the /tg/'s atmos changes, which require the map tile gas mixes to be edited.
6. Compare variables/etc between two codebases and decide what we want to keep. This would require alot of manual labor.

There's probably a few things I'm missing, but that's the gist of it. Other than that, I really don't have anything against rebasing /tg/, but it's not as easy as you make it seem to be if we are to make this a more serious endeavor than "Let's just be /tg/ with admin-tickets".

**Comment by Bawhoppen** [comment]
Tg runs just fine and almost definitely just as good or better than Yog, When you tried to run it locally its because it starts with a low default fps, so it looks super choppy, you can set it ingame to be higher and it will run extremely well.
Hosting tg completely vanilla on it's own for a day would be actually be a very good way for you guys to decide what you want to keep/remove.

**Comment by X-TheDark** [comment]
I see, I suck at this hosting thing then, my apologies, I'll edit that part out.

**Comment by Bawhoppen** [comment]
Also in regards to your council members, I saw a few of them on your server and they didn't seem completely against it, and were interested by some of the features I talked about. If you could direct the other ones here for discussion, that would be a good way to get the idea if they will be willing to let it happen.

**Comment by X-TheDark** [comment]
Over the new few days I'll try to clear the administrative hurdles by asking Council members to make a vote on this (we do this in this kind of way) and our playerbase of this (polls, etc).

**Comment by ghost** [comment]
Your features are impressive, yes, but a lot of your players are different to ours, and so a lot of your features need to be removed or reworked entirely.

For example, we ported /tg/ blob in full. Blob won every round because yog players are less competent at fighting blobs.

And so on. Ashwalkers, holoparasites, sleeping carp-these types of things would steamroll consistently, so while it's not hard to disable one or two things, we'd have to run through your whole code and comment out a LOT of things. 

So we'd really only be getting half or a quarter of your features if we did rebase.

**Comment by Bawhoppen** [comment]
Thats why running tg for a day to see what would and wouldn't work is a good idea, then just disable them from there. Most things are built to be easily disabled.

**Comment by EMT321** [comment]
I think TG for a day would be good.

**Comment by Robertruler77** [comment]
Speaking as someone who plays low level tg on the odd occasion, I'd love to see how yogs reacts to tg features after a pilot of tg code.

To be honest, I see very few glaring issues or conflicts, but I'm not a coder, so I'm probably missing a lot of that side, but a good updated code with variety would be a fun thing, cause I just see yogs and tg is the same raw materials with different luxury industries, if you get the analogy.

In summery: I'm for a pre announced test of tg code on yogs and seeing where we go from there.

**Comment by ghost** [comment]
Yes please.

**Comment by Alek2ander** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
People rationalizing being too lazy to merge 500 conflicts

**Comment by ghost** [comment]
LAZINESS IS A WAY OF LIFE

**Comment by ShadowDeath6** [comment]
https://forums.yogstation.net/index.php?threads/vote-coding-rebase.10567/

**Comment by Bawhoppen** [comment]
I feel like that vote was a bit premature, what are their reasons for being against it entirely?

**Comment by Robertruler77** [comment]
You'd be lucky to even get one of their opinions tbh mate, not like the average player knows jack about the council.

**Comment by ghost** [comment]
not even the admins know jack about the council or how the decisions are made up there

i personally imagine they're all a bunch of bald shadowy figures in a dimly lit room 

and then you turn on the light switch and it's just a bunch of bobbleheads with 'IOU ONE DECISION' stapled to their heads because they take about fifty million years to vote on anything

**Comment by Bawhoppen** [comment]
If you guys are still doing the test though, I'd still like to see it, maybe in a few days?

**Comment by Super3222** [comment]
@Bawhoppen 
This will hopefully be a project that'll be worked on.
I don't feel like that council vote will prohibit the general idea that we are indeed, a very old codebase, and need to update. 

For this to happen though, lots of arrangements and discussions need to be made. But just so you know, I'm in favor for rebasing along with other of our coders who are interested in it as well.

I feel like some people don't understand the weight, nor the reason fully for why we need to rebase. Points seem to be going over peoples heads, or maybe they aren't reading into them at all.

This is a consideration, so I'm not holding any promises. Just know that it's a storm to get through.

**Comment by AdamElTablawy** [comment]
https://forums.yogstation.net/index.php?threads/rebase-to-tg.10587/

**Comment by Bawhoppen** [comment]
I'm not going to make a yog forum account, so if someone could bring up this point on that thread,
Yog is barely unique in terms of features, you are extremely similar to when you last rebased, with the only major changes being ported from modern tg, aswell as a few small unique unique features that would take an hour to port in total. 

Hippie, for example, which is only a few months out of date of tg code, is massively more unique than Yog, I don't want to be rude but Yog is virtually almost the exact same as the tg code you used in June 2015 (when you last rebased IIRC). 

As I keep saying, it would be extremely easy to disable some of the features you disagree with on tg code, and then it would be very very easy to port in your admin ticket system, or whatever smaller things you have/want. 

Overall rebasing would be a very simple process, and very beneficial to the quality of code/features.

**Comment by EMT321** [comment]
Baw is right. This server is missing a plethora of features seen in Hippie and TG (and ultimately the downstream effects of the Goon leak).

**Comment by Robertruler77** [comment]
As of current it's 19-4 in favour. Overwhelming majority want a rebase or some tg updating. See how it pans out.

**Comment by Bawhoppen** [comment]
Did someone delete their comment or something, I feel like there was something else

**Comment by Bawhoppen** [comment]
oh I see now. drama memes

but anyways I don't want to be rude, but I'll say again, you guys have virtually nothing to lose by rebasing except possibly a sense of indivuality, but that should come from community not code
