### ISSUE TITLE
Martial arts (not carp-fu)

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#136]
So basically, adding martial arts, balance is welcome and probably needed, some of the moves would be availible to all crew, but these are kinda bad, some are sec-specific and can also be learned via books in the sec department, it'd work like spells pretty much

Anyways, here's a list I have so far:

////////////////////////
//Learnable via books//
///////////////////////
Choke-slam : User must have a grab on, they will slam the target into the ground, doing o2 damage and some brute whilst the user cannot move for 3 seconds after
Recharge: 60

Brutal punch: A hard-hitting, single punch, ideal for punching someone in the face so you can stun them
Recharge: 40 , does double damage

Barrage:
The user unleashes a 20 punch barrage on the target, with 100% hit chance, each punch doing normal hit damage. Needs aggressive grab
Charge: 100

Headbutt:
User headbutts target, doing a nasty 10 brute to the user and 20 to the target, must aim for head
Charge: 20

RKO outta nowhere!
Must have a grab hold on opponent, click this while near a table and they will be thrown through it, 40% chance that you go with them and take 10 brute, they will always take 20.
Recharge: 100

Move reversal stance:
Puts the user into a defensive stance, they cannot move while in it, but as soon as someone attacks them, the move is reversed.
Charge: Toggleable

Master's final attack:
HYPER RARE, User charges a fatal attack (4 second charge) where they will be in an attacking stance, the target must be 1 tile away and still, they must aim for the chest, once charged, they will get an icon much like the wiz-gibbing one
in hand, where you click the target with it and it RIPS THEIR STILL BEATING HEART OUT
Charge: 100

Mantis sacrificial attack:
With an agressive grab, the user falls on their back, and uses their leg to throw the target a massive distance, doing 40 brute, but leaving the user on the ground for 6 seconds to recover

> ---------------------------------------------------------------------------------------------------------------------------<

/////////////////////////////////////
//Ones that sec actually start with//
/////////////////////////////////////

Shitcurity Sweep:
An instant disarm, if it lands, 60% chance of landing, user uses their legs to knock down the target, stunning them for 3 seconds and disarming them. Must be 1 tile away
Recharge: 40

Last Resort:
Whilst downed, officer leaps up and dives at their target, this downs the target for 4 seconds, and the officer stays down for 6 due to the pain, also deals 15 brute to officer, and 10 to target, maximum 5 tiles distance.
Recharge: 60

Weapon disarm:
The officer performs a skillfull disarm of a weapon, must be standing one tile away from them and must have at least a basic grab grip.
30% chance to fail and trigger the weapon to attack them instead.
Recharge: 20

---

/////////////////////////////////////////////////////////////////
//Common knowledge martial arts (every pleb knows these babies)//
/////////////////////////////////////////////////////////////////

Arm flail attack: You randomly flail your arms and hope to hit something
40% chance that each hit will land, 5 hits (ie 5 punches for the price of 1)
recharge: 30

Clown special:
80% hit chance, clown only, must have water flower in hand, the clown directs a huge spirt of water into the target's eyes, bliding them for 1.5 seconds
Charge: 10

Bar-Brawler's Slam
User throws all their force into the opponent from 1 tile away, landing a deadly punch which deals 30 brute, but has a 50% chance to half the damage and make the user fall over (it's a clumsy move)
Charge: 30

Clowns will have a 80% chance to mess up every move (except the clown move), HONK

REM: For charge, charge = no. of seconds, see: wizard spells

Thoughts?

**Comment by shrimptk** [comment]
Taco was working on something like this, except based around the concept of superpowers on his janky baycode version

**Comment by Super3222** [comment]
I like this idea, as long as there is someway that we can prevent greytiders from reading every last book. Maybe a cap on how many skills you can learn? Watching an assistant tear through an officers armor and rip out their heart would be worth the watch though.

I've seen techniques people can take things out of your hands and into theirs in an instant, maybe we can integrate that as well?

**Comment by shrimptk** [comment]
I don't know the specifics but from the last time I tested it with taco only one power was able to be learned at a time, and the scrolls were incredibly rare for the simple fact that these powers (Fire punches, rapid swings, doppleganger, etc.) were incredibly strong. Maybe these could be implemented as gateway loot,

**Comment by Super3222** [comment]
> Maybe these could be implemented as gateway loot,

That is a brilliant idea.

**Comment by ghost** [comment]
Do not implement these at all.

The karate moves we've seen are already brutally imbalanced. Sleeping carp is easily the strongest gang, provided someone's competent.

Like seriously, the 'heavy punch thing' does as much damage as a fucking energy sword?

AN ENERGY SWORD?

No.

We don't need more gimmicky karate, we don't need some idiot running around with their super shitty meme leg sweeps and kicking people to death while stunlocking them, and we don't need that ridiculous instakill barrage attack.

**Comment by ghost** [comment]
Like look at the 'last resort' thing. 

You stun an officer, so he fucking hurls himself 5 tiles away and bodyslams your fat ass, gets up and beats you to death because he's on fucking meth.

How do you fight that?

The one thing EVERYONE has been able to rely on is that when someone goes down, you have them in control. If you change this, security becomes absolutely nightmarish to fight, even more than their stupid ridiculous barrage of insta-stun memes is.

And then you made it reward people who pull off this stupid shit by also hurting THEM? What kind of shit is that? Who makes an ability, and then punishes the user for using it? That's a ridiculous drawback. 

And a  combo arm hit attack that does 20 damage on fucking RNG? Each with individual knockdown chance? 

What happens when four assistants run up and spam this ridiculous shit? Instant crit mechanics are not good, RNG is not good, and punishing the user for using it is not good.

**Comment by Kmc2000** [comment]
@shrimp.tk 
Yeah I like that, the main thing about the books is they would be an INCREDIBLY LOW CHANCE spawn in loot spawners, such as maintenance, so it would be incredibly hard to find them.
But they would be far better than the standard, bar fightey ones

Also @adam
What do you suggest as drawbacks? i've tried to make them realistic, because if you throw yourself into someone, it's gonna hurt you too
Additionally, the brutal punch would be SUPER FUCKING RARE as with all of these moves

**Comment by BadminBen** [comment]
the thing is about our sec is Non lethal is the way to go. this would be ok for a tator to have because when sending in spies you want them to have some training in self defense. For now im against this untill it can be more fleshed out and tested for balance.

**Comment by ghost** [comment]
@Kmc2000

Having those stupid books spawn in maintenence is ridiculous. No matter HOW low chance, we don't have pulse rifles spawn in maint, nor should we have ridiculous 20 punch 100% hit combos. Those should be admin only.

There should be no drawbacks, or charge times/recharge times for using those abilities, instead requiring specific punches/grabs in order. Harm intent Harm intent Grab intent Disarm intent for arm flail.

Disarm intent Disarm intent for shitcurity sweep.

Remove the lunge entirely.

Make it standard that if a security officer disarms someone, the weapon immediately goes into their hand instead of on the floor.

Remove bar brawler.

All book attacks are admin only.

There, simple.

**Comment by Kmc2000** [comment]
Alright, I like that
+adam
