### ISSUE TITLE
Gang ideas.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#150]
Gang is iffy, as-is.

We could use some buffs for it.

Perhaps, on a successful kill of an enemy gangster, an additional 20 influence is added to gang who killed them?

Successful kill of enemy gangleader would be 40 influence.

The death of a gang, by security, or by gang, would provide 30 influence to all gangs.

Some flavor text being added to newly converted gangsters like 'Ask your gangboss for orders and protect him with your life, and claim territory for the gang' would also be good.

Making gang leader/gang lieutenant chat display the names of leaders/lieutenants so that gangsters could PDA them to communicate with them would also be good.

This encourages co-operation between gangs, and gang/gang combat. Security is supposed to be mostly irrelevant in gang-It's primarily supposed to be the gangs vs each other.

**Comment by BadminBen** [comment]
i not a fan of death of gangster by sec gives influence. Flavor text is good

the PDA function will let any competent CE or AI know who is the boss.

Also i would more flavor text for gang boss to actually promote LTs. so gang doesn't only have 1 guy recruiting

**Comment by Hydre** [comment]
Of all the gamemodes gang is not exactly the most iffy

**Comment by B1gb3ast** [comment]
So, snowball mechanics in gang?

Dear jebuss

**Comment by ghost** [comment]
@BadminBen 

What do you mean?

It's the gang leader's name displayed in the chat so gangsters know who the fuck he is instead of 'WHO ARE LIEUTENANTS' over and over.

There's nothing added to PDA's.

**Comment by BadminBen** [comment]
Making gang leader/gang lieutenant chat display the names of leaders/lieutenants so that gangsters could PDA them to communicate with them would also be good.

thats what you stated lol. If the plebs messaged the boss "whats our orders?" or "who to kill"

then its obvious they are a leader. just follow the orders of the Boss in red text

**Comment by Super3222** [comment]
@AdamElTablawy 
The problem is there's no checks to see if X killed Y unless you look in the logs.

Also what if a gang leader happens to randomlly suicide / jump out an airlock? Free 40 influence to the other gangs?

> Making gang leader/gang lieutenant chat display the names of leaders/lieutenants so that gangsters

I'd say that information is processed through IC, and if gangs are competent enough to cooperate and speak with one another than they shouldn't be handed it freely. Walk around, and find a leader if you weren't converted by one.

One other thing that I could see in game is if you could get something added to your IC notes "You were recruited into the X gang!  find and protect your leaders with your life, help them with your goals, etc".
