### ISSUE TITLE
RIPLEY's problem with big power cells

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#166]
I loaded 20000u cell into Ripley instead of 1000u, the power level only started from 20%.

**Comment by X-TheDark** [comment]
Incredibly weird "feature". I found where the bug occurs. 
In the code, when a new cell is inserted, 80% of it's power is "used" (aka removed from cell). Strange interaction, to say the least.

**Comment by DavidEdwards** [comment]
Suggest we fix that "feature", unless anyone can think of a reason to keep
it as it is (balancing something?).

**Comment by X-TheDark** [comment]
I'll make a pull request very soon, it **should** be a incredibly straightforward and easy fix. Oh, right, it also affects all mechs, not just the Ripley.

**Comment by george99g** [comment]
The only reason I see for having that in is to stop people from just replacing the power cell every time instead of charging the mech properly.
Maybe make it remember the percentage of the last cell and then use that for the new one?

**Comment by DavidEdwards** [comment]
If the operator is willing to carry around batteries, is it really an issue
for us to let them recharge the mech that way? It doesn't seem like a _bad_
thing to me.

**Comment by george99g** [comment]
> If the operator is willing to carry around batteries, is it really an issue
> for us to let them recharge the mech that way? It doesn't seem like a _bad_
> thing to me.

Well, R&D prints fully charged cells that they can replace for less than 10 seconds while charging the mech through the normal recharger takes a lot longer.
Not personally against this, but we should probably make the charger faster if we allow them to do this.

**Comment by DavidEdwards** [comment]
Or make fully charged cells harder / slower to make.

**Comment by shrimptk** [comment]
> The only reason I see for having that in is to stop people from just replacing the power cell every time instead of charging the mech properly.

George is right
-1 Because this can be abused super hard with a backpack full of bluespace batteries

**Comment by X-TheDark** [comment]
I'll just implement george's suggestion, which I planned on doing anyway. I'll probably mess about with the recharge rate, as, indeed, it's a tad ridiculous with something like a bluespace battery, where you get about 1% every 3-4 seconds.

**Comment by X-TheDark** [comment]
I decided not to mess with the recharge rates for mechs for now, because I would like to hear your opinion.

How recharge works for mechs currently:
1. Mech bay power port consists of 5 capacitors.
2. Each capacitor rating (1 for basic, 2 for advanced, 3 for super, 4 for quadratic) gives 25 power recharge/cycle.
3. So, the recharge per cycle rates are as follows: 125/250/375/500 for all basic/advanced/super/quadratic capacitors, respectively.
4. (Local) Testing shows, that charging a bluespace battery (capacity of 40k) from 10 power to 40000 took 5 minutes 36 seconds, using all advanced capacitors (250 power/cycle).

Do you think this is too little (considering a commonly available advanced capacitor as the baseline)?

**Comment by X-TheDark** [comment]
Also, mechs start with a weird basic cell that is upgraded to a "special supercharged" cell of 15k capacity (by editing vars directly on the cell), despite using the sprite for the regular 1k cell. I'll up it to 20k by making the cell super-capacity (20k), to prevent inconsistency (and a sizeable buff to starting energy)
