### ISSUE TITLE
Are changes to Summon Magic necessary?

### ISSUE THREAD

**Issue by X-TheDark** [yogstation13/yogstation-classic#238]
As per title, lately, there's been discussion (and by that I mean mostly Adam) about Summon Magic being grief heaven due to it not really doing anything other than give grief items to people **without making them antag or giving them a really good reason to use them** (unlike Summon Guns that spawns antags).

So, what kind of changes are/are not necessary to make Summon Magic better? Current ideas:
1. Remove Mindswap/Horse Mask from the spell list, because they are pretty much pure grief material.

Any thoughts, comments?

**Comment by FluffySurvivor** [comment]
Make summon magic spawn antags as well, with the objective "achieve 5 spells". To do this, people get an "Assimilate" ability which they can use to probe/steal someone's power(s). Should be a damaging channel, not something instant.

**Comment by shrimptk** [comment]
@FluffySurvivor More antags??!! Calm down before keek gets a boner

**Comment by Super3222** [comment]
> Make summon magic spawn antags as well, with the objective "achieve 5 spells".

Just what we need on top of the mass grief and staff abusing that we get from greytiders.

**Comment by X-TheDark** [comment]
Honestly, I was joking with Adam about replacing Summon Guns and/or Summon Magic with Summoning a Donksoft LMG, perhaps that would still be relevant?

**Comment by Groudonmaster** [comment]
We'd have to change donksoft or create a type that spawns with a normal pin

**Comment by X-TheDark** [comment]
That's easy to do. The only question is, what to do? Replace Summon Magic with Summon Magic Donksoft or Summon Guns with that or something else?

**Comment by Super3222** [comment]
@X-TheDark, you are definitely right. Spells like mindswap just cause too many grief and confusion, however horse facing a person for no particular reason is just straight grief. 

Though I'm certain that same spell doesn't have a cancel button, so you are forced to move out of your position or/and choose someone.

**Comment by Stealthkibbler** [comment]
You could make it so that summon magic only summons magic for some crew and effectively turns them into an apprentice with the objective to slay the wizard and an additional objective. They would of-course be considered hostile to the crew and legit targets for anyone including other apprentices however it would eliminate some issues which are.
1.Everyone having magic
2.cutting a vast majority of the grief since only REAL antags are given magics/artifacts
3. turning those who roll lucky into magical bounty hunters with an additional neutral objective that means when the wizards does die or if they cannot find him they focus their efforts on the other objective.
4. The lessening of magical items overall allows for a much more free flowing experience for everyone in the round as opposed to the magical clusterfuck of 50/50 grief/fun.

Alternatively you could make it so that after 20-30 minutes wizard hunters spawn from the pool of ghosts tasked with the objectives of slaying the wizard and confiscating all magical artifacts and slaying anyone who uses magic, they would be considered enemies of the station and a legit target for anyone. As for their gear and abilities I'm not entirely sure how to imply what their mechanics would be but that's my general idea.
