### ISSUE TITLE
Bluespace Fanny Pack

### ISSUE THREAD

**Issue by krgii** [yogstation13/yogstation-classic#250]
It would be cool to have a bluespace fanny pack that functioned similar to the bag of holding maybe with slightly less space or an item size limit.

**Comment by Time-Green** [comment]
You just wanna see people shoving enourmous objects in their crotch?

**Comment by krgii** [comment]
It would be nice to have a toolbelt that has a toolbox inside it.

**Comment by shrimptk** [comment]
> Bluespace toolbelt
> Actually a thing in baycode

**Comment by ShadowDeath6** [comment]
Military belt works the same way, although it can't hold normal-sized items. 
This would just make the item even less used, not really thinking this is a good idea.

**Comment by ghost** [comment]
hurr durr nobody buys revolvers because you can get guns from science durr

the issue with the military belt is that it's fucking an instant taze perma item unless you're going murderboner, and if you're going murderboner there's better shit to spend TC on than some shitty belt where you can just take a fannypack and shove belts in

a bluespace fannypack, printable by R&D, would be hilarious. Or just some form of bluespace belt.

Naturally it needs to do something horrible if you put one inside the other.

**Comment by Rocks4Free** [comment]
> Naturally it needs to do something horrible if you put one inside the other.
> 12 honkbots spawn. Then again, half our rounds would just be filled with honkbots if that were the case.

**Comment by DavidEdwards** [comment]
Sounds like a good idea to me. As Adam said, !FUN! needs to happen when combining things.

**Comment by X-TheDark** [comment]
Done in #281, closing.
