### ISSUE TITLE
Issue with Mech Battery

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#291]
ADMIN: Abdbla/(Alice Coldwaters) (FLW): It stopped working after being shut off 
ADMIN: Abdbla/(Alice Coldwaters) (FLW): Then turned on 
ADMIN: Abdbla/(Alice Coldwaters) (FLW): It now instantly discharges batteries

**Comment by ToGWtF** [comment]
Batteries printed at the Protolathe are considered "Unreliable" and won't recharge in mechs. You can print all tiers of batteries at Exosuit fabricators, and they are suitable for mechs and will recharge.

**Comment by X-TheDark** [comment]
Working on this right now.

**Comment by X-TheDark** [comment]
The only thing I can think of that causes this is the fact that if your battery runs out, any replacement will come with 0%, since it remembers the removed ones charge (which in this case is 0%), causing an infinite loop of batteries being instantly discharged.

**Comment by ToGWtF** [comment]
I believe its intentional. Batteries printed from Mechfab have 100% reliability while batteries printed from Protolathe only have 70%

**Comment by X-TheDark** [comment]
No, no. Nothing to deal with like reliability. I worked on a request (#169) to remove the 20% charge on replacement thing. As a result, when you remove the cell it remembers it's charge (in percent) and applies that to the next inserted cell.

That way you can upgrade the cell (and retain it's charge percent), but not just recharge the mech by replacing the battery (balance issue). But now, because you replace a dead cell, any cell inserted will be dead (so you can't move the mech, basically). I'm going to make a minimum charge level.
