### ISSUE TITLE
Un-nerf chems reeee. Also some med changes.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#303]
One-

Re-add the chemical sprayer to R&D. It used to be a thing and was a weaker version of the ops chem sprayer with no chems and less storage capacity/range. It was fun to use and had great potential.

Two-

Un nerf sprays. I miss my fluacid spraybottles, and all the chems no longer working in spraybottles make me sad. Unnerf sprays back to their original really lethal format where chemicals sprayed on someone were applied on skin contact.

Three-
Un nerf Facid. UNNERF FACID. I MISS MY GIANT ACID GRENADES THEY WERE SO FUN.

Four-
Make space lube have a visible sprite, like water, so that you can see it before you slip on it. Bam, lube balanced.

Five-

Unnerf patches I miss them. The patch change really didn't do anything-The other med changes are fine.

Six- Make cyro non-auto eject when healed-You have to resist out when you cyro yourself or someone has to free you, because otherwise you're stuck kicking the tube until you're free. Discourages powergamers self-cyroing and makes cyro a viable murder tool for antags KOing people.

Seven- Re-add eph's medical brute/burn damage healing surgery, it was fun as fuck and added a use for surgery too.

Eight- Disable the ability to see chemicals in a beaker inside a cyrotube unless you have science goggles on, just like you can't see the chems in a beaker unless you have science goggles on, to allow for more viable cyro murders with poisons.

**Comment by Time-Green** [comment]
I agree with all of them. Except 6
This is just going to cause people being stuck in a permanent sleeping state.
Until a competent medical opens it. And that rarely happens

**Comment by FluffySurvivor** [comment]
Skeptical about chemistry buffs, it's already quite strong. We don't want it to crowd other departament options. 
Everything else except 6 yes pls

**Comment by ghost** [comment]
This is just going to cause people being stuck in a permanent sleeping state.
Until a competent medical opens it. And that rarely happens-

You can resist out.

Just hit resist when placed in a cyrotube, you can kick out in .5 minutes, the same as cable cuffs.

**Comment by Groudonmaster** [comment]
You actually sleep in cryo now Adam

**Comment by ghost** [comment]
yes i know you sleep in cyro

but it's too short to be effective antag murder

dunk someone in cyro for quick storage and pull them out .4 minutes later for stabbings

**Comment by ToGWtF** [comment]
> I agree with all of them. Except 6
> This is just going to cause people being stuck in a permanent sleeping state.
> Until a competent medical opens it. And that rarely happens

Thats the fun of it. I remember "back in the day"  that getting put in cryo by a guy who couldn't figure out how to open a medkit was an immediate death by ghosting sentence.

Perhaps make Cryo auto-eject after being upgraded by science, giving medbay more of a reason to bug science into upgrading their machines and more possibility for healing due to upgraded sleepers.

> You actually sleep in cryo now Adam

You always used to as long as I could remember. Since rejoining, Yog was the only server I knew that didn't have that anymore. You were still able to resist out, unless I'm confusing myself with Baycode medical

As per the original proposal, I do love my chemsprayers. Fill them with Space-cleaner, you're a janitors best friend. Fill them with Lube, a Clowns best friend. Fill it full of Welding Fuel, and youre a syndie's best friend. They spray in a 3x3 area rather than a 3x2 area like Fire Extinguishers do, and could even be filled with healing chems. You could say they could get easily grief-y, but we give chemists grenades already that can do just the same if not WORSE damage

**Comment by Stealthkibbler** [comment]
Cryo can stay the way it is imho, we dont need more dumb reasons for people to make tickets "Help cant get out of cryo"

**Comment by ShadowDeath6** [comment]
Ah, yes, buff patches so that traitor chemists can kill you in two seconds instead of five with le lube+last whisper.

**Comment by B1gb3ast** [comment]
So we're giving CE magboots and noslips lube immunity.
And lube gets a water overlay.

Does that nerf it to the point where it becomes a 10 minute crime instead of a ban?

**Comment by Groudonmaster** [comment]
> Does that nerf it to the point where it becomes a 10 minute crime instead of a ban?

Can we? That'd make it much more fun.  Of course overuse would still lead to a ban but you know.

**Comment by ghost** [comment]
That'd be great, please do.

**Comment by ghost** [comment]
Closing to clear up space, I'll do it myself in a bit.
