### ISSUE TITLE
Objective Compass

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#313]
Well, as an antagonist finding your objective can be really difficult.
I even had cases of CMO destroying his Hypo at roundstart.

Or when you search for the HoS's laser gun and some random dude has it

Perhaps add an item to the syndicate upload that tracks your objective. 
Human or object

And prevent all traitor items from being removed from the z-level like the disc.
(except unused slime cores perhaps?)

**Comment by oisin100** [comment]
:+1: 

I've redtexted sooo many times because i just cant find the damn thing. Literally looking for it 2 hours straight.

**Comment by DavidEdwards** [comment]
I dont really want to start making SS13 have trackable objectives, like Elder Scrolls. With an arrow telling you where to go.

I COULD deal with it reporting the general area that it is in. Updating extremely irregularly.

**Comment by ParagonPrime** [comment]
A sort of "traitor pinpointer" for 1 TC would be useful. Click on it, get a dropdown menu of high-value potential traitor objects (ie, HoS laser and hand tele; NOT plasma, slime core, etc.) and have it lead you.

Nice thing to have if chaos reigns and nothing is where it's supposed to be, and not necessary if you're observant/robust/lucky.

**Comment by Time-Green** [comment]
Perhaps allow players to emag the communications console and ask the syndicate about their location?

**Comment by ghost** [comment]
This is retarded, no.

Stop making it easy mode for antags.

If you're too unrobust to find your objective, you lose, that's the difficulty in a steal objective.

You don't get to go and instantly know where your objective is. It's retarded. Might as well just set your objectives to automatically greentext because you're so unrobust.

Someone close this, please.

**Comment by ParagonPrime** [comment]
^adamsalt.exe

Common scenario:

> get midround antag
> "steal object that any random powergamer would happily nab"
> have to figure out which of the 20 people on escape shuttle has the fucking HoS egun
> who has it in the end? the fucking clown

Are we supposed to murderbone everyone and individually search every bag? And that's for an objective that (tends to) stay with one person, is too large to fit into a box, tends to be kept easily-accessible (thus visible) all the time, and is generally covered by powergaming rules; what about the hand tele? Or the Hypo? The chance of acquiring the former is practically nil if you weren't the person who broke in to get it in the first place, and the latter is probably hidden in some box in some backpack on the psychiatrist's cold, dead corpse in space.

It's not about "robustness" 80% of the time, especially on highpop. You want to make this a non-necessity? Crack down SEVERELY on the powergaming, or else you do get an assistant with half the high-risk items in the station... floating dead outside arrivals because carp, and you'll never possibly know that.

**Comment by ParagonPrime** [comment]
At the VERY LEAST, objective-items should be prevented from leaving the station z-level, akin to the nuke disk, and respawned if destroyed. Otherwise, yes, all the CMOs will covertly space their hyposprays and the Captain cremate his jetpack.

**Comment by ghost** [comment]
TOUGH.

You can't find your traitor steal item?

TOUGH.

Can't find your assasinate target? TOUGH.

Too bad if you can't find it. You LOSE. That's how it WORKS.

Either get good and do some fucking detective work to track it down or LOSE.

There's not going to be some 'ehhh ehhh i'm a whiny little babbe who can't find his hypospray mommy help me' inbuilt thing.

If you can't find the CMO's hypo, emag a comms console and ask. Making a one-TC auto greentext item is retarded.

There are two parts to traitor that make it actually difficult-FINDING the objective and COMPLETING IT.

The first part is FINDING IT, so that if you want to kill your assasinate target you have to LOOK for him. If you can't, you LOSE, that's how it works.

Same with steal.

Can't find the hand tele in the teleporter room? Fucking TOUGH, get the det's scanner, scan the tele door, get some prints, and start looking. 

If that means you have to kill every single person you track down on the trail to the hand teleporter so fucking be it. If you find the RD's prints on the teleporter door and you end up killing him so you can search his bag and if you don't find it end up abducting more people and asking them where the tele is that's how it WORKS and that's what a traitor is supposed to do.

If it means you end up dragging the RD off to a lone room and telling them to tell you where the hand tele is or you'll kill them, TOUGH, that's how it WORKS. It actually makes and enforces RP rather than a gimmick button that you get to use to instantly know where your steal objective is, just like if you got to know where your assasinate target was at all times.

If you end up killing everyone in science in a frantic search for the hand tele, TOUGH, you're a TRAITOR, that's how it works.

Yes, you're supposed to do ANYTHING AND EVERYTHING to accomplish your steal objective, even if that means killing everyone related to it and searching their bags and anyone who's had contact with those people and searching their bags, ect.

Not to mention taking a high-risk item as a nonantag is BANNABLE. If the clown has the HOS's gun? BANNED. Clown has disk? BANNED. Assistant with hand tele? BANNED.

So not only is it unlikely it'll end up in the hands of some random assistant rather than it's rightful owner, but if it does (The owner gives it away) then yep, you better start acting like a fucking traitor and killing people to get it back.

There's no one fucking telecrystal advanced pinpointer that lets you know where all the high risk items are because WHAT'S THE DIFFICULTY in that? Might as well just fucking ship you a box with a pillow and a blanky wanky inside if you're too fucking unrobust to complete your objective.

Sometimes you fucking LOSE as a traitor and that's how it goes. Sometimes you do everything you can and you just can't find any prints and any idea where it went and you did everything you could and you still lose and you know what? TOUGH. This isn't a greentext simulator. You win sometimes, you lose sometimes, and sometimes you lose due to stupid bullshit and that's how it fucking goes.

**Comment by Super3222** [comment]
I've encountered this.. many times.

I figured that I could just communicate with the syndicate by emagging a communication console and simply telling them the item they want me to steal had been destroyed.

The downside is it only works when admins are on.

**Comment by ghost** [comment]
Oh well.

No admins? You lose. Also, admins should always be on.

**Comment by ghost** [comment]
If heads of staff destroy all the traitor steal objectives just to prevent traitors from stealing them, ahelp that shit so we can ban them.

**Comment by ParagonPrime** [comment]
So, Adam, you're authorizing basically slaughtering anyone who so much as thought about our objectives or passed by the door, rather than a bloodless (if "spoonfeedy", though location of objective =/= actually getting the fucking greentext) method? Right. Thanks for the free pass to take people out of the round. Will link here when boinked by less sympathetic admins.

**Comment by ghost** [comment]
Feel free to link here when you're banned for murderboning so I can laugh at you.

Whatever it takes to find your theft item WITHIN REASON, go ahead.

If you bomb primary because 'i wanted to kill people to search them for hand tele lol' you get a ban.

If you find CMO's hypo missing, scan his locker and find 3 prints on his locker, you're justified in assasinating those 3 people and checking them for the hypo, OR abducting them and interrogating them for the whereabouts  of it.

**Comment by shrimptk** [comment]
Common Scenarios: 

> Traitor's Obj is to steal Hypo. Some random clown robusts the CMO and takes it. Before you know it, its changed hands 20 times before 30 minutes have passed on the round clock, and suddenly, the traitor gets banned for murderboning while trying to find the fucking Hypo.
> 
> No one ever gets banned for touching high risk items
> 
> Hand tele's disappear 5 minutes into the round, every round.
> 
> When you drag someone into maint for interrogation, they refuse to talk because its a **'low RP'** server.
> 
> Captain's have a hobby of looting traitor obj items from all the head lockers.
> 
> Objs getting straight up destroyed 
> 
> Powergamers afraid of getting targeted change their appearance via surgery and take on a new name.
> 
> A bunch of other random bullshit that craps on someones fateful antag round.

Essentially, little things can completely fuck up your greentext, no matter how thought out your round is. This has gotta stop. Paradise actually has an Advanced Pinpointer as a traitor item that allows you to use the pinpointer like a Detectives scanner and track certain prints, or find get the general location of a missing high risk item. For a hefty 8 TC, that shit is pretty balanced. We shouldn't treat this as a **'gg tough luck pal'** thing because this really makes being an antag fucking blow. kthx

**Comment by Groudonmaster** [comment]
I agree with shrimp here. We shouldn't encourage antags being fucked just because one person thinks that it's a bad idea. Its not hand holding because it would cost quite a few tc and they would still have to manage to steal it. And while a few of our playerbase is robust enough to do so new players should not be told gg no re because the hand tele was stolen

**Comment by Cruix** [comment]
Perhaps we should just add more admin tools for dealing with high-risk items. Add a notification whenever a high-risk item leaves the z-level or is destroyed, and a panel that shows admins the location of all high-risk items.

Perhaps even an admin message whenever a high-risk item it picked up by a non-antag, non-head, but this would probably be going overboard spamming the admins. There should certainly be some record of all the people who have possessed a high-risk item, so admins can track down people who stole them for no reason, and because fingerprints are, as usual, not up to the task.

While, as Adam says, tracking down your steal objective is half the fun and challenge, I have had the rather unpleasant experience of searching through a depressurized engineering department looking for my unresponsive document-trading partner, only to find out after the round that he had spaced his documents, and they ended up outside the white ship.

**Comment by ghost** [comment]
I have never once seen any of the scenarios shrimp has described and no, a lot of people get banned for taking high risk items. Check the public banlist for my name and see how true I am.

**Comment by DavidEdwards** [comment]
OK. I am behind Cruixs suggestions for additional admin tools to deal with these situations. We could implement links in the _admin_ antag view panel that show the location of all items that match the antags goals. With the ability to spawn a new one in to a random locker if necessary.

This is a game, and sometimes we don't win (ala Dwarf Fortres !FUN!). That is something that must be accepted.

**Comment by Time-Green** [comment]
I am aware, but it shouln't be impossible.

The moment all the traitor items get cremated at roundstart by cap, its impossible.

At least the coms console hacky thing comforts me

**Comment by shrimptk** [comment]
> Checks public Banlist for Adam's Name
> 
> Has to sort through mountains of bans for hours upon hours.

**Comment by ghost** [comment]
> I am aware, but it shouln't be impossible.

The moment all the traitor items get cremated at roundstart by cap, its impossible.

At least the coms console hacky thing comforts me

AHELP

AHELP IT

AHELP THAT

I have NEVER seen a captain do that. Ahelp it if it does.

**Comment by Time-Green** [comment]
This went viral way to fast

**Comment by Groudonmaster** [comment]
> AHELP
> 
> AHELP IT
> 
> AHELP THAT
> 
> I have NEVER seen a captain do that. Ahelp it if it does.

Ah but what if the traitor DOESN'T KNOW. I've had it happen like twice with someone noticing but it happens quite more often than that I'm sure

**Comment by Cruix** [comment]
Perhaps there should also be a traitor forensic scanner. There is only one that spawns on the station, one more that spawns on the detective, and it's not always possible to get one ordered from cargo. Having one in the uplink will also give people the idea to do that at all - I'm sure many traitors who are not as experienced as Adam, myself included, would never have thought to use the Det's scanner to track down their objective.

**Comment by ParagonPrime** [comment]
Not to mention,

> get forensic scanner
> expect to get instant gratification and find out who stole the hand tele you need
> scan airlock
> "insulated glove fibers"
> bomb whole station to kill everyone because _apparently everyone who has or has ever had insulated gloves is now fair game_

**Comment by Cruix** [comment]
Maybe - <i>maybe</i> - a syndicate forensic scanner that is better than the Det's, and can magically see finger prints through gloves. Perhaps with a limited number of uses, and access to an unerasable fingerprint database. Possibly with limited uses, to cut down on usability.

<i>Syndicate Agent's Compile-o-nator menacingly states: "You can hide from the law, but you can't hide from the syndicate."</i>

**Comment by ShadowDeath6** [comment]
> Blob round
> Random keekenox steals cap's laser to fight blob because MUH BLOB DHKSNS
> Blob dies
> Midround traitor with objective to steal cap's laser
> Never finds it

LEL GIT GUD TRAITOR YOU SHOULD BE PUNISHED WITH REDTEXT FOR SOMETHING YOU COULDN'T CONTROL

**Comment by ghost** [comment]
Yes, exactly shadow.

Sometimes you lose and that's it GG lol you lose lol.

Try doing fucking something else instead of beelining for an impossible objective and then getting upset if you can't get it.

Or I dunno ahelp 'I think my obj is destroyed' BAM CHANGED.

**Comment by Deometran** [comment]
1 TC syndie detective scanner, perhaps. Under the name "High-Risk Item location device"

**Comment by DavidEdwards** [comment]
OK, I am closing this issue. I think that extra admin tools will be a good idea. I will create an issue for that.
