### ISSUE TITLE
Admin tools to assist antags with their lost items

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#325]
OK. I am behind [Cruixs suggestions](https://github.com/Cruix) for additional admin tools to deal with these situations.

We could implement links in the admin antag view panel that show the location of all items that match the antags goals. 

With the ability to spawn a new one in to a random locker if necessary.

**Comment by X-TheDark** [comment]
I'm up for it.

**Comment by ghost** [comment]
This would definitely be a buff.

**Comment by ParagonPrime** [comment]
"Random" being, literally, placing a new item in a random locker somewhere on the station, or being able to just spawn a new one in a chosen location?

Because if it's the former, that's kinda silly. Nothing quite like having the Virologist perma'd for having the Cap's laser suddenly spawn in his locker.

Also, can't admins already kinda do this (with some items) by just going to the AB-USE room, grabbing an item, and returning to station? Isn't that actually why the AB-USE room is there?

As such, though, I'm not against this at all.
