### ISSUE TITLE
Changeling updates

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#339]
Basically takes some ideas from that one ling thread on forums. 

-Remove sleep sting, it's stupid and op
-Add horror form, requires 10 Genomes to unlock, consumes 10 chems every second while in use. Gives you infinite flesh-mend with a cooldown, an AOE stun similar to shadowling's icy veins obviously without the freezing part and a larger AOE. Can devour people, which is like absorption but a lot faster and leaves remains or nothing behind. Reverts you if you run out of chems or get below 40 or so health. Also gives you hulk so you can beat everyone up. Is extremely obvious, hoping for a coolio spriter to make an icon or just steal goon's icon because it looks godly.

The old request died, I think.

**Comment by oisin100** [comment]
God no too OP.

**Comment by ShadowDeath6** [comment]
Also make the horror form cost like 9 or 10 DNA points so you can't use any other abilties. 
Also ALSO: Make it weak to fire and lasers a la shadowling.

**Comment by shrimptk** [comment]
10 Chems/sec is a lil' too much, given the uses.

**Comment by X-TheDark** [comment]
Mandatory plug #172

**Comment by ShadowDeath6** [comment]
I made a seperate thread since I didn't like most of the stuff in the other. 

Would ~7,5 chems a second work?

**Comment by ghost** [comment]
Eh

Porting goon's horror form only works if the ling has less abilities

I feel like it should be an innate ability of a ling, no DNA points required, just like healing from death, but also completely bar the ability to use anything else while active.

Also, while reverting from horror form, make it weaken and stun for around the same length as glare's duration-or half of that if that's too strong. 

10 chems/sec is too strong as well-7 chems a second is much better. Or 10 chems every 2 seconds.

Instead of infinite fleshmend with a cooldown, the horror formed ling should automatically heal over time when not on fi-Fuck it

here

http://wiki.ss13.co/Changeling#Shambling_Abomination

We're ripping them off entirely by doing this, everything shadow suggested is literally just ripped from them, so look at that for what abilities a shambler should have and what it should do.

This isn't an ability a changeling can pop just on the spot whenever it wants for free murderbone-Using it carries a serious risk of getting killed because the stun after reversion is so long and you're barred from using any ling abilities after you revert for a bit, not to mention chem regeneration after reversion should be halted or at least halved to prevent spam.

You should also be required to have 40-50 chems in storage to initialize it. It doesn't expend them, but it is required you have that many chems before horror-forming, so people can't just spam it, shriek, and revert in all under a second with one chem and never have to wait.

It's a last ditch mechanism of being a horrifying shambling monster that can kill the hell out of people and takes a dedicated force to actually beat, but the changes I proposed above mean that it can't just be used as another way to murderbone in maint by going shambler and killing the shit out of some dude and going back. It'd actually be used as a last ditch resort, not instant-murder on the spot in maint.

If anyone's saying 'but now it isn't viable for combat!' it's not supposed to be. This is last ditch. You aren't SUPPOSED to go on a murderboner rampage with it, you aren't SUPPOSED to be super viable in combat and be able to pop it whenever you want with no reprecussions.

You pop it, you kill the people hunting you and make a getaway, and then hide and recuperate your losses.

**Comment by ghost** [comment]
Also, what don't you like about the issue I made prior?

I can certainly modify it in some fashion.

And again, limited DNA for abilities works fine for goon, and I massively increased the amount of DNA return you get for absorbing a living or dead human, meaning you'll rarely run out of DNA if you actually employ your abilities in an offensive manner and act like an alien hunter rather than a guy with a silencer dildo you shove into people's mouths.

Hell, limited DNA would be a far greater mechanism here than it would for chems by giving it something to burn that prevents this being spammed.

**Comment by ShadowDeath6** [comment]
Yeah, make reversion stun for a while, and prevent ability usage for however long. 
Maybe utilize stamina damage so the ling is more vulnerable while they're down?

Also I've played goon ling and the finite chem pool was a huge problem, and being able to use abilites at my leisure to test and try different things was one of the main reasons I enjoy ling here. It's just preferential in my case.

**Comment by ghost** [comment]
That could work.

**Comment by ShadowDeath6** [comment]
Ayy lmao I made a better issue for this
