### ISSUE TITLE
Adamantime Slime Extract + Radium

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#359]
Have it so that if you inject an adamantine extract with radium, it creates one random sheet of metal, other than bananium. 

Basically intended to let science slowly upgrade their shit without mining, but it takes a bit of work.

**Comment by Groudonmaster** [comment]
Why not just change metal some extract to do that?

**Comment by ShadowDeath6** [comment]
Because metal slimes are super easy to get. 
There needs to be some challenge.

**Comment by ghost** [comment]
YEA GUYS LET'S ENTIRELY REMOVE DEPARTMENT INTERDEPENDANCE

LOL YEA WHY NOT REMOVE ANY REQUIREMENT FOR PEOPLE TO DEPEND  ON OTHER DEPARTMENTS TO BE COMPETENT

'but if mining is shit or nobody's mining then R&D can't reach their full potential'

THAT'S THE FUCKING POINT

IF MEDBAY IS RETARDED PEOPLE DIE

IF ENGI IS RETARDED PEOPLE DIE

IF SEC IS RETARDED PEOPLE DIE

FUNNY THING ABOUT SCIENCE, NOTHING BAD HAPPENS IF EVERYONE IN IT IS DEAD AND CARGO'S LITERAL ONLY PURPOSE AT THE MOMENT IS FOR MINERS TO DO SOMETHING BECAUSE NOBODY ORDERS CRATES

'b-but muh maxed levels'

FUCKING TOUGH

HOPE FOR GOOD MINERS, OR YOU'RE SHIT OUT OF LUCK. DEPARTMENT INTERDEPENDANCE.

HELL, ADDING THE CHEM DISPSENSER TO R&D WAS RETARDED BECAUSE SCIENCE DOESN'T NEED TO GO TO CHEMISTRY EVEN IF THEY WANT THEIR SHIFT START ACID

NO

BAD

FUCKING

IDEA

STUPID

IDEA

'B-b-b-b-b-b'
TOUGH

MINE YOURSELF OR YOU'RE OUT OF LUCK IF MINING'S DUMB.

**Comment by ToGWtF** [comment]
Calm down Adam

I made the suggestions that it should be rainbow slimes. At least rainbow slimes take some effort to make, even if that effort is simply waiting for RNGesus to stop being a bastard.

**Comment by ShadowDeath6** [comment]
It's literally one sheet, Adam. Slow as fuck. This is literally eons slower than mining and it makes it so that science isn't completely fucked from having fun because people don't know how to not get violated by tentacles and memed on by goliaths. 
Literally, any department can do something to lessen the effect of incompetence. Hack medivends, getting defenses in case of antags, whatever. It's fucking dumb that THE ONLY WAY TO GET MINERALS AT ALL EVER is via mining, and mining hardly ever does their job. If you think this will break balance in any way you're jaded.

**Comment by X-TheDark** [comment]
I'm with Shadow on this one. It's not the interdependence that's the problem. It's the TOTAL AND COMPLETE interdependence. No other department in the game gets damaged as much as science by absence of another departments cooperation (Cargo Mining).

That doesn't mean I'm supporting this solution (indeed, replace Adamantine with Rainbow, if this were to go through), but a solution is needed.

**Comment by ShadowDeath6** [comment]
There's an equal (or very close to equal) amount of work an RNG to get adamantine and rainbow slimes, doesn't really matter which one gets it as long as it's T3 or above.

**Comment by ShadowDeath6** [comment]
miner drones fixed it, no longer needed
