### ISSUE TITLE
Nerf Energy Shield 360 degrees protection

### ISSUE THREAD

**Issue by X-TheDark** [yogstation13/yogstation-classic#394]
Projectiles hitting you from your side or your BACK should not be reflected, only the ones hitting you from direction of 3 tiles in front of you (front, front-left, front-right of the direction you are facing).

**Comment by ghost** [comment]
NO BAD STOP NO

**Comment by Groudonmaster** [comment]
I can handle keeping the side hits. BUT TAKE AWAY THE REFLECT WHEN IT HITS THEM IN THE FUCKING BACK. I WANT TO BACKSTAB A MOTHERFUCKER.

**Comment by ShadowDeath6** [comment]
NO ESHIELD NERFS EVER, NOT EVER. THEY'RE A NICHE ITEM AND THEY DESERVE TO SERVE THEIR PURPOSE

**Comment by X-TheDark** [comment]
They are not a fucking niche item. They prevent ranged attacks from about 80% of weapons available to security with 360 DEGREES PROTECTION. Seriously, remove the side/back deflect, because it's just dumb.

**Comment by ghost** [comment]
> doing this
> item is now shitty waste of 16tc where adrenals would serve better

Get good and get a shotgun, there are 3 in the armory and sextrillion from cargo once ops is declared.

**Comment by DavidEdwards** [comment]
I agree with you @X-TheDark 

Unless you are wearing a shield emitter that literally covers all angles, the shield should only cover what it appears to cover. I would go as far as to only allow through shots from the rear 3 tiles and allow the rest.

That means that the attack really has to catch the person by surprise, and not just from sideways crossfire.

**Comment by ShadowDeath6** [comment]
They're a niche item. They're SHIELDS, dude. They cost like half the TC available to an op at roundstart (not declaring war) And they're intended to block shots. Literally any halfwit with a stunbaton can fuck an eshield op and if you add this then ops will probably lose every single time since eshields are practically one of the most important items for staying alive for more than 12 seconds.

**Comment by X-TheDark** [comment]
I guess I can concede to that point, it's a much bigger issue in War when ops have loads of TC to spend on weapons and ammo...so they can stim/eshield/loads'o'ammo themselves up.

I mean, have you seen Keek solo like 10 people as a Nuke Op on war, despite being about 6 halfwits with stunbatons (others were civs), they couldn't do crap to him? That's what made me propose this. Plus, walking into AI core with turret shots being literally useless is not cool.

**Comment by ShadowDeath6** [comment]
Declaring war means everyone and their dog is armed to the teeth with gear. If AI isn't moved/reinforced and you dunk on it with an eshield then it's the crew's fault for not expecting it.

**Comment by B1gb3ast** [comment]
I mean, have you seen Keek solo like 10 people as a Nuke Op on war, despite being about 6 halfwits with stunbatons (others were civs), they couldn't do crap to him?>

Well, that's because he's a robust player.
Aren't nuke ops supposed to be elite fighters, anyways? I mean, you could Always just change the way the item looks and turn it into a shield emitter so it fits a more thematic purpose....
But then there'd be no reason to have it in hand.

**Comment by shrimptk** [comment]
> /tg/'s shield emitter

**Comment by ShadowDeath6** [comment]
Shielded hardsuit when?

**Comment by Time-Green** [comment]
What if you put the shield in your backpack slot?

**Comment by Super3222** [comment]
The hardsuit with an infused-eshield from /tg/ isn't as OP as you'd expect..

Logic wise, eshields seriously shouldn't cover every point of your body. That's a true fact and everyone knows it. I'm pretty sure that the e shield is a reference from Halo or something, and that doesn't cover your entire body.

> What if you put the shield in your backpack slot?

Don't think you can do that with these shields. Though you can do it with riot and telescopic shields.

Nerf eshields 360 degree block, but at the same time allow them to block stunprods / stunbatons 100% of the time depending on whether the attacker is on an adjacent turf facing ahead of them. (so they can still sneak stun from he back)
