### ISSUE TITLE
Add aimable fireball/staff of fireball.

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#395]
WIZARD BUFF WIZARD BUFF WIZARD BUFF

nah but srs.

Make fireball aimable inhand, so that you can actually target it and it isn't a shitty meme spell.

Alternatively, give the wizard a staff of fireball buyable for one spell point. Basically just like the wand of fireball, but a staff, for the wizard, and everything that entails.

**Comment by ShadowDeath6** [comment]
Fireball inhand would be a decent buff, staff of fireball is giving a wizard an infinite gyrojet pistol that ignites, so no, that's shitty.

LOB FIREBALLS FOR DAYS LAD

Edit: MAAAAAAAYBE Make staff of fireball for the offensive apprentice only, since it literally sucks so much ass right now. Kind of like healer apprentice having a staff of healing.

**Comment by shrimptk** [comment]
I've wanted inhand fireball **Forever**. Being able to aim 4 directions is fucking lame as shit.

**Comment by B1gb3ast** [comment]
I feel like a wizard might become a little too powerfull if you give him a reliable means of shooting his spell without the risk of dunking himself because he didn't press W+D while factoring in byond lag so he shoots himself in the face instead of down the hallways instead.

As is, a wizard can't cast fireball while running away. If you give him this he becomes even MOAR fucking pow-

What am I saying 1 syringe-rip wizard yeah sure.

**Comment by ShadowDeath6** [comment]
> making fireball a spell worth using

**Comment by Super3222** [comment]
It could be done. So if you activate the spell, it places a fireball in your hand (similar to the new Ei' Nath) but, turns your throw mode on. As long as it diminishes under a certain time limit as well.

Also staff of fireball sounds extremely OP.

**Comment by ghost** [comment]
its shit
