### ISSUE TITLE
Slower shuttle if biohazards are present

### ISSUE THREAD

**Issue by Alblaka** [yogstation13/yogstation-classic#411]
Basicly, in all random-firing xeno events, the xenos are seen, red is swiped, shuttle is called. There's never a true infestation phase going on.
As well, why does Centcom deny shuttles to leave when there's blobs on the station, but doesnt mind it if there's random-spawned blobs? Mah immarsions!

Therefore, my suggestion:
If any event-spawned biohazard is present on the station, a shuttle dispatch takes 20 minutes to arrive, due to a 'special biohazard containment shuttle' (opposed to the normal or the 'priority' one) being used.
If a BH Level 5 triggered, and any blob tile stile exists, biohazard shuttle.
If a BH Level 7 is triggered, and any crewmen is still alive and infected with the respective disease, biohazard shuttle.
If a BH Level 9 is triggered, and there are any zombies, or crewmen infected with the rage virus (and alive), biohazard shuttle.
If a BH Level 10 is triggered, and there are any alive aliens, eggs, facehuggers, or infected crewmen, biohazard shuttle.

If the conditions for the biohazard shuttle are 'cleared' (i.e. last blob tile removes, last diseased patient cured), the shuttle arrival timer is halfed.
In all situations, biohazard overrides Code Red call (aka, you cant just go code red to skip the biohazard shuttle and instead get a 5 minute one).
Biohazard shuttles are ONLY Triggered by the actual events. Mode-spawned blobs (here, shuttle wont leave anyways) and virology-made diseases do not count.

The purpouse of this change is, mainly, to make random event aliens something more then just code red shuttle reason. And maybe give the crew a reason to hunt zombies instead of just hiding in a locker.

**Comment by Rocks4Free** [comment]
10/10 would like.

Would the biohazard shuttle be seperate from the regular one and have actual differences, or would it just be the same shuttle but slower?

**Comment by Alblaka** [comment]
Same shuttle, but slower. I mean, the priority shuttle doesnt have larger engines, either.

**Comment by ShadowDeath6** [comment]
> giving xenos more time to curbstomp everyone
> making shitty diseases like brainrot and magnitis call for a 20 minute shuttle

u wot

**Comment by ghost** [comment]
Minor few issues.

Blobs spawned from lvl5 do not have a win condition. Theoretically they could curbstomp all crew, kill everyone, and cover the entire station, and unless an admin was on, the round would never end and the shuttle would never leave.

The same goes if zombies and xenos triumph over crew.

Finally, making it so thay you have to spend 39 minutes looking for some assistant braindead in maint with magnitis is bad.

Instead of blocking the shuttle-blobs, randomspawn ones, past a certain threshold, will automatically activate the nuke with a ten minute timer. All antag escape objectives will be counted as green if they are on another zlevel when nuke goes boom, as tg did.

Xenos should either have the same mechanics as blob going boom, or past a certain threshhold-80% or so-automatic deathsquad dispatch.

Viral biohazards should delay shuttle arrival by an extra 5 minutes or so.

Zombies would just not launch as long as any infected crew or zombies are on the shuttle. Alternatively, a zombie win condition could be to be on the escape shuttle.

**Comment by Alblaka** [comment]
> shuttle would never leave.

20 minutes != never.

> giving xenos more time to curbstomp everyone
> making shitty diseases like brainrot and magnitis call for a 20 minute shuttle

To be fair, I've never yet seen a Level 7 not be eradicated in 15 minutes. Not sure whether Medbay just became more competent or where else this came from.
And yes, I want Xenos to actually do their curbstomp thing if they're RNGed for once.

**Comment by ghost** [comment]
Biohazard shuttles NEVER LEAVE, Alblaka.

**Comment by Alblaka** [comment]
> Biohazard shuttles NEVER LEAVE, Alblaka.

Did you even read what this suggestion is about? Adding a 20-im (aka slower) shuttle for biohazard-events?

You are talking about the Blob MODE shuttle. Me is talking EVENTS. 

edit: Albeit, we could probably add this 20min shuttle to blob mode, too. If the round lasts 50 minutes (30 min till shuttle can be called, 20 min for biohazard to arrive), something went horribly wrong in either direction and people likely want to leave by then. Make it count as blob victory and noone can complain.

**Comment by ghost** [comment]
OH.

I missed the part where you wrote that the shuttle takes 20 minutes to arrive.

When you just wrote biohazard shuttle I thought you meant it'd never leave.

**Comment by Time-Green** [comment]
Could we give it some smexy sprites?
Like anti tox and other Bio stuff.
Bio Suits. Different kinds of medicin, perhaps a biosquad?

**Comment by Alblaka** [comment]
> Could we give it some smexy sprites?
> Like anti tox and other Bio stuff.
> Bio Suits. Different kinds of medicin, perhaps a biosquad?

This would definitely be nice eye candy, maybe spice up the 'lame shuttle meta' and make sense thematically.
But in the end it's a part of the map you see only 5 minutes, it would have to replace the normal shuttle and might just be way too much effort to be worthwhile.
