### ISSUE TITLE
Hybrid tasers only switch after firing once after switching

### ISSUE THREAD

**Issue by GrayRachnid** [yogstation13/yogstation-classic#444]
### Expected Behaviour

Switch to disabler from taser, shoot disabler
### Actual Behaviour

First shot is a taser instead of a disabler, fixes itself after the first shot. Still annoying.
### Steps to reproduce the problem
1. Get Hybrid taser
2. Switch modes
3. Shoot

**Comment by DavidEdwards** [comment]
This should be quite easy!

@yogstation13/initiate-coders

**Comment by ShadowDeath6** [comment]
Happens with energy guns too, you shoot disablers on lethal mode.

**Comment by ToGWtF** [comment]
Yeah I noticed this with Temperature guns, only seemed to happen with latest master build

**Comment by X-TheDark** [comment]
I am the one to blame, PR #314 (changes in code/modules/projectiles/guns/energy.dm) changed the way the round is chambered for energy guns (so energy weapons could shoot bursts by simple change of burst_size), it seems that I messed it up a tad, because it doesn't "re-chamber" when you change the modes, so the previous chambered shot remains.

One gotcha with fixing this:
- When you switch modes, you have to "refund" the currently loaded projectile, otherwise simply implementing something like qdel(current_projectile) and newshot() will deduct energy merely on mode switch and not actual firing, which is not good.
- Maybe removing line 40 will be enough to fix this, but it might break the Cyborg LMG (Syndicate Borg). Currently that is the only burst fire energy weapon.

**Comment by ShadowDeath6** [comment]
Is there any way to make the LMG a ballistic weapon and keep the same automatic reload?
