### ISSUE TITLE
Bomb Collars

### ISSUE THREAD

**Issue by george99g** [yogstation13/yogstation-classic#48]
opened by Ben · 24 days ago
What is the nature of the issue: Bomb Collars being stuck in a mobs hand
What steps must be taken to reproduce this error:
Bomb collar was placed on a human
Human got turned into a monkey to remove collar and turned back into a human
As a human they picked up the bomb collar now lying on the floor and it got stuck in their hand.
Any additional information? : Will test in on test server

**Comment by Super3222** [comment]
I've tested this on my own server, and it turns out the bug is real. The problem is that there is no other way to get it off your hand unless you put it on your own head. I believe this is because monkeyizing forces everything on them to fall to the ground, but doesn't change the bomb collars NODROP flag. So when you pick it up again, you cannot remove it from your hand because of that flag.

**Comment by Super3222** [comment]
after much spaghetti, I've come up with a potential patch for this. I've been testing all day and can say as a witness the bug exists.
