### ISSUE TITLE
Nerf Minebots

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation-classic#485]
Where to even begin...

While the concept of having these is nice, a competent player can easily hop into one of these things, upgrade the entire station, upgrade the ore redemption machine to essentially have infinite minerals and cargo points all within 20 minutes since they have all access. This is all without breaking the drone laws, as you can justify doing this all for performing law 3 as efficiently as possible

Insert exhibits:
http://imgur.com/lHHdO5g
http://imgur.com/y6IYnmQ
http://imgur.com/kUKiQ93

Since this generally shouldn't be able to be done within the first half an hour of the round, as mining is meant to be a 20-30 time gate (at minimum) for science to be able to finish their research, these things really need some sort of nerf so they aren't essentially god tier miners who can also do R&D.

So here's my list of nerfs
1: Remove their ventcrawling and all access so they can't easily waltz into science and do all of R&D. Better yet would be to whitelist the consoles they can interact with to only the shuttle cockpit and the mining shuttle consoles so they can't do R&D or anything else stationwise period

2: Remove their screwdriver repair and force them to use an APC to repair instead (and make sure it's in their activation text so they actually know to use it) so they're forced to return back to the station to repair if they get damaged. I know it doesn't make much sense for an APC to be used, but
using minerals/otherresource would allow them to hoard them and use them at will

3: Remove their drone vision so they can't see where crates are or what is in artifact rooms. This stops them from immediately being able to spot the rooms with sonic jackhammers/diamond drills/ other useful mining stuff.

4: Nerf their speed to borg levels so they can't scarper fifty lightyears away from any threat .I'm a bit iffy on this one, in general mining mobs need a buff as they're no threat at all anymore unless you encounter two or more of them at the same time, but I'm digressing. This'd also slow down the rate they can deliver minerals, which is a good thing in the long run.

5: Give them the normal scanner instead of the advanced one. The advanced scanner simply lets you spot minerals more consistently and let's you find diamonds and uranium much more easily, while most miners have to at least put a token effort in mining first before they can get it.

**Comment by ToGWtF** [comment]
I thought the plan for them was to not allow them to leave the mining asteroid for any reason?

**Comment by ShadowDeath6** [comment]
Why is their effectiveness a bad thing? They were made specifically because miners would never bring in materials, completely cockblocking science from upgrading things. Their laws allow them to do R&D for better mining supplies, but not for upgrading things on their own.

**Comment by Super3222** [comment]
Exactly what Shadow said.

You aren't suppose to be in R&D unless you are gaining tools to mine. Sitting there and waiting for research to be done is exceptional after coming back with an amazing amount of loot. But doing research yourself (and even furthermore - upgrading?) shouldn't be tolerated at all.

**Comment by ghost** [comment]
I am in the process of nerfing (decreasing their efficiency) them. I will lower their health by ten points and give them an access card for only mining, cargo, and maybe science. Their goal is to refine minerals, which I'm pretty sure they can't do on the asteroid. Also, I won't make all the changes described in the issue because after all, they are a drone, and like regular drones, are meant to efficiently carry out their goals, which regular humanoids don't always do... They must be bought for 1000 points from a vendor and they can't really interact with anything but xenomorphic life forms on the asteroid, inhibiting their actions that would cause them to be more like humanoids. Also, maybe we could add an anti-power game rule for drones and minedrones, preventing them from maxing out research or stealing every valuable research item, unless the round is almost over.

**Comment by ghost** [comment]
Leaving mining is bannable.

Yes, this includes doing R&D. You can't do that.

Your purpose is to do mining. That is it. That is all you can do. You mine, you refine, you go back to mine. You can't do R&D. You can print things from R&D for mining, but you cannot do it, or upgrade it, or anything else.

**Comment by ghost** [comment]
Exactly.

**Comment by ghost** [comment]
They're not allowed to do any of that in their laws.

**Comment by ghost** [comment]
So yes, notify us if a mining drone is doing R&D so we can ban them.

Otherwise, they are perfectly balanced right now.

**Comment by ShadowDeath6** [comment]
I'm fine with drones doing R&D as long as it's to get better materials, since mining with a satchel of holding and a plasma cutter is infinitely more efficient than a drill and an ore box. If you make it so they can't do R&D at all, it makes them much slower than a miner who can use R&D. 

They literally have the exact same function as a miner with stimpacks. A miner can bring in just as many materials, but they don't.

**Comment by EMT321** [comment]
Minebots present a method for dead players to get back into the game in a uniquely beneficial manner. I personally have not encountered mining drones doing R&D at all, although I do tend to see them bringing materials in about equally often as miners during medium/high pop, and more often on lowpop, where they may very well be the only miners.

Mining and science, specifically with the end result of upgrading the station to everyone's benefit, are one of the most interconnected department dynamics. 

Handicapping that arbitrarily is short-sighted. I agree that limits, if made clear to drone players, would alleviate some concerns raised. I believe that the current dynamic is more to do with experienced people enjoying mining again, rather than the drones themselves being OP.

**Comment by ShadowDeath6** [comment]
I agree completely with EMT. It isn't the drones themselves being OP, it's the players in them. Functionally, drones are no different than human miners, outside of a few differences that don't affect productivity. Nerfing them would only cause players to enjoy them less, and thus turn into a feature that nobody uses unless it's an off-day. 

Also, please don't make it from the miner vendor only. That will completely remove them from any and all rounds, I can guarantee it.

**Comment by Notamaniac** [comment]
> Functionally, drones are no different than human miners

Drones have a screwdriver repair that essentially removes any risk mining as they can run away and repair. At the very least a miner needs to bring the brute first aid kit, and they risk running out of patches if they take too many hits, and they can't easily heal burn damage from basilisk unless they make a trip to medbay just to get burn patches. As for drones, all they need to do is sit still for a bit, then they're back up to 75% health again (which I'm guessing is a bug).

They also move much faster than normal miners since they aren't slowed down by their hardsuits, which lets them mine far more quickly, especially since they have their mining drill which is slightly faster than their pick.

Now before you say miners have their stimpacks to move faster, let me remind you that stacking both epinepherine and the stimpack boost only gives you a 33% boost. A 33% boost of sluggishly slow is still slow, no matter what way you spin it. You also have to use points to buy it, so that means mining before you get them, and taking a box uses up space you could be using for another tool or for storing artifact loot.

Talking about artifact loot, I'll reiterate my point in the OP, drones can simply look into artifact rooms to see whether they have better mining tools/good loot, while a normal miner has to actually mine (god forbid) into them to see what they have.

If I was a normal roundstart miner, it takes me at least 20 - 30 minutes to get a haul of 80+ plasma, 30 gold, 30 silver 20-30 uranium 100 sand and 150+ metal 3-6 diamonds. As a drone I can do this in about 15 minutes, simply because I'm faster, I have a better drill and a better scanner

Minedrones are fun right now because they're explicitly better than normal roundstart miners, who are slow, can get completely dunked on if they get surrounded by two or more mining mobs (rare but possible), start off with shittier equipment, and even if they do get better equipment, assuming the minedrone gets the same equipment (i.e plasma cutters, sonic jackhammers ect.), they're STILL worse off since they aren't as fast nor can they simply repair themselves with a screwdriver.

And no, fun =/= good. KA's were fun for a while, when they had a 3x3 mining range, dealt 15 damage in non vaccum and were upgradable so they could shoot faster and have faster firing speeds. The 3x3 mining range simply let you DESTROY the mining asteroid and upgrading your KA, especially if you bought another let you kill (unarmoured) normal crew members within seconds if you cocked one KA after another, not to mention what it did in anyone in a vaccum or how quickly you could murder a goliath with them. These eventually got their upgrades and 3x3 range removed because they were so ridiculous. Cutting to the short of it, minedrones are just below this level of good, for the above reasons.

> So yes, notify us if a mining drone is doing R&D so we can ban them.

The issue is that there's nothing explicitly stating anywhere not to do R&D. You can even justify doing R&D by law 3 as you're working towards getting better mining tools, and upgrading the smelter lets you process resources more efficiently.

**Comment by ghost** [comment]
And now I'm saying don't do R&D and I'll see to it about getting the rules updated or the laws updated to explicitly include that.

**Comment by DavidEdwards** [comment]
We can add some admin logging when drones access terminals. That way they can be found out faster.

**Comment by Stealthkibbler** [comment]
A veteran miner can obtain everything R&D will ever need in under 7 minutes of the round starting. Incompetent miners are the miners who take longer than 20 minutes to get all the minerals. 

A veteran scientist can have all the pre- mineral research done before a veteran miner can even bring his first batch of minerals in.

Honestly it would be nice if you could obtain extremely unique materials such as Bananium or adamantium  (Some servers do have this) With the sonic jackhammer and bluespace satchel.

As mining drones stand, you do 10 minutes of mining, buy a mining drone and then go afk because you dont even need to mine anymore. It can get to a point where if the smelter has been upgraded once, twice or three times 5 minutes of minerals can allow for 2-4 more drones to be made with every haul.

Gameplay wise miners at the moment only exist to jumpstart the drone replication process, however drones cannot self replicate without an ID card. As Drones cannot claim mining points the miner can easily see his drones bringing in more and more points for him to spend on more drones.

Research wise I can guarantee if there is a scientist and a drone walks in and starts touching his console he will kill that drone, if there is no scientist doing R&D I do not see the problem if it is using it to obtain better gear, afterall upgrading is a part of drone directives.

**Comment by Ephemeralis** [comment]
Departmental completion should be a 45min~ target, not 7-20 minutes. Needs immediate fixing.

**Comment by Stealthkibbler** [comment]
> Departmental completion should be a 45min~ target, not 7-20 minutes. Needs immediate fixing.
> Mining already has access to all the minerals the station will ever need, there's a specific spot where veteran miners will go to gather the most amount of each mineral in the most effective way possible. Mining isn't enjoyable unless you're being extremely effective and providing minerals extremely fast. 

If Mining gets another heavy nerf people will just stop playing it period, gameplay wise miners should not have to spend 20-40 minutes of the round getting the first batch of minerals. many gamemodes tend to end around the 40 minutes mark, Such as revolution, Shadowling and nukeops.

As someone who played miner a lot and loved that I could min-max the minerals being brought in I wouldn't bother even playing miner if the entirety of the departments progression was nerfed because of an addition that isn't even a core element of the department but a bonus object you can obtain for 1000 points, and with an un-upgraded smelter getting a minedrone takes roughly 15-20 minutes because it is extremely expensive and most the time if R&D is slower than me I just buy the diamond pickaxe for 1200 points.

Do not nerf mining because of these drones, nerf the drones and lower their required points, heck even replace the broken as shit NPC drone that you can get with a coupon and let the miner coupon the player controlled drones. The whole department does not have to suffer because a coder put it an object that off-balances it, nerf the object, not the department.

I will say it again, Do not nerf the entire department based on a single addition that is not even a core element of that department.

**Comment by ghost** [comment]
Minebots were nerfed already.

Departments are never completed anyway. You can't 'complete' mining. You mine, get shit, go back and mine s'more.

Making science wait 45 minutes for minerals every round means no Xrays vs blob.

Nope! Closing this, already nerfed as per your request.

Mining drones are less common now, and mining drones that do R&D are banned.
