### ISSUE TITLE
Borer jobban

### ISSUE THREAD

**Issue by AsV9** [yogstation13/yogstation-classic#514]
Borers should be able to be jobbanned by admins.

**Comment by oisin100** [comment]
Ok dokey!

**Comment by ShadowDeath6** [comment]
No :^(

**Comment by Time-Green** [comment]
And give it its own preference.

And rules... Or is that the wrong place for it?

AND PLEASE BLOCK SUICIDE.
SO MANY POOR PLAYERS DIE BECAUSE THEY ATE A CANDY AND THEIR BORER FREAKED OUT AND SUICIDED AND I HAVE NO IDEA WHAT TO DO REEEEEEEEE

While you are at it, give it a prompt if ya wanna be borer.
I was cap, died, got brought to medbay BAM YOUR A BORER AND CAN NEVER GOT YO BODY BACK HYEH NYEH NYEH
And no, turning of midround antag does not work with borers.

**Comment by ShadowDeath6** [comment]
> so many players
> quoting a player who had it happen to him

Also it's alien preference, since they're aliens.

**Comment by oisin100** [comment]
/should/ be fixed in #509

**Comment by Time-Green** [comment]
Shadow I know.

And I hate that

**Comment by oisin100** [comment]
This has been added.
