### ISSUE TITLE
Atmospheric pressure 192529152 kPa caused by event?

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/yogstation-classic#520]
### Expected Behaviour

Having much less than 192,529,152 kPa pressure in a room.
### Actual Behaviour

Engineering pressure raised to 192,529,152 kPa apparently after an event "WARNING: Fulminant atmospherics error detected. Plasma routing temporarily diverted to distribution loop. Fires may occur. Internals are advised." (plasma burned out) at Server Time: 2016-03-10 12:25
### Steps to reproduce the problem
1. Suspected plasma burn and pressure raise after event.

**Comment by oisin100** [comment]
This has happened before... Hallway outside of medbay once has so much pressure that you were killed almost instantly just by standing there.

**Comment by 00aquir** [comment]
yep, now I died in an eng hardsuit, too (couldn't really move once I was inside and saw the pressure, plus the big temperature). AI's panic syphon was useless against this...

**Comment by ghost** [comment]
holy fuck

**Comment by ShadowDeath6** [comment]
KEK

**Comment by nazitra** [comment]
can confirm, I was AI, what the fuck was that

**Comment by ParagonPrime** [comment]
would make for pretty hilarious situations though

> **CAPTAIN ON DECK**
> "ohai guys what's-"
> _opens airlock_
> _flattened against wall_

**Comment by ParagonPrime** [comment]
for reference, that pressure is higher than that of Jupiter's surface

(yes Jupiter has a surface look it up)

**Comment by Notamaniac** [comment]
I can't see anything offensive in the plasmafire event code, but then again I don't know byond well.

`if (prob(3)) //may the honkmother have mercy on your soul (this ignites the vent tile presumably causing hellfire and suffering)
            var/turf/location = pump.loc
            if (isturf(location))
                location.hotspot_expose(1000,500,1)`

~~This'd be my guess, the hotspot generated by the vent is so hot it raises the pressure to exceedingly high pressures by itself, but I don't know what the hell location.hotspot_expose is ACTUALLY doing.~~

Nevermind it's the standard igniter call.

Alternatively it could be that other atmos glitch which lets you get 2.6e^124whateverKPA of hell gas overlapping with this glitch, but as far as I can see all the code is doing is just putting the gas in the vent location so it can get spewed. 

My only guess is that the plasma mix ignites on the vent tile, and with potentially 150 moles of concentrated plasma on the vent tile, it ignites and burns all at once, rather than spreading out normally then catching fire, but that all breaks down when you realise that 150 moles is basically just 6 full plasma tanks, which is much less than what a canister.

**Comment by Groudonmaster** [comment]
I vote leave it just because it's hilarious as fuck

**Comment by oisin100** [comment]
Mm, Im gonna call it a feature.
