### ISSUE TITLE
Admins crowd mentality

### ISSUE THREAD

**Issue by DavidEdwards** [yogstation13/yogstation-classic#564]
### Expected Behaviour

Tickets get claimed when they appear.
### Actual Behaviour

If there are lots of Admins on, each Admin assumes that someone else will take the ticket. This leads to tickets being forgotten.
### How to fix this problem

Send a notice to all Admins when there has been an unclaimed ticket for longer than a minute. Keep reminding at regular intervals until it is claimed.

**Comment by Time-Green** [comment]
Not a bad idea.
This is how most unclaimed tickets end up yeah

**Comment by FluffySurvivor** [comment]
Huh? 
In my AO time I was in a race to claim the tickets before adam, so I thought the more admins the faster tickets get claimed. 

Anyway, good suggestion it doesn't hurt implementing

**Comment by ghost** [comment]
SIgh

It's not a coder isuse, it's an admin issue

Just ban all admins except for me because I'm the only one to speedclaim tickets

**Comment by Stealthkibbler** [comment]
Tickets get overlooked because they dont look important, this is combination of players not providing the exact problem in the ticket hence the admin attending to tickets that do explain the issue, afaik admins are allowed to prioritize tickets that provide suitable detail to the problem and ignore tickets that are like "Help" or "Why am I ded". In the end though you are meant to deal with every ticket, but if the ticket provides no context to what is the problem you can ignore it until the ones that do provide context are solved as it would take less time.

This addition would be great nontheless, I think another issue with this is administrators expecting other online staff to take a ticket leading to this sort of situation where a ticket sits there waiting to be taken. It starts off in Mod or AO when they're ambitious and eager to take any ticket but miss out because admins like Adam are trying to beat the olympics world record for ticket taking. 

Make it occur at intervals of 30 seconds when an admin is online, Hardy has made it pretty clear and mango has also told me that tickets are not meant to be sitting unclaimed for more than 2 minutes which usually ends up being the case, online staff should recieve this notification every 30 seconds whenever there is unclaimed tickets forcing someone to take the ticket.

**Comment by DavidEdwards** [comment]
> In my AO time I was in a race to claim the tickets before adam, so I thought the more admins the faster tickets get claimed.

If there are 2 or 3 admins, that kind of mentality can appear. Which is great!

However, when you reach 5+ admins, it starts to switch to the style in this issue.

I was also thinking of implementing DB logging for admins who take and resolve tickets. That way we could have a kind of leaderboard of awesomeness.

**Comment by Time-Green** [comment]
If you do that, holy fuck.
Yes please

**Comment by Alblaka** [comment]
It could help greatly if unclaimed tickets would throw up boinks and whatever the player sends AFTER THE FIRST MESSAGE.
Right now, if someone ahelps 'Hey' and then 'X killed me in Y after Z happened and because A it might be B but I think he could be C', only the 'Hey' part will ever be displayed to the admins (unless thwe ticket is claimed by someone right after).

I cant count the times where I made an ahelp, then added more lines as a situation progressed (or to ahelp a new situation), then some admin answers only on the first ahelp closes the ticket, I ahelp again asking whether he checked on the second part, too, just to hear 'Oh wait, didnt see that one'.

Additionally, with this chance in place, users would likely ahelp further if their ticket is never claimed, serving as automatic reminder.

**Comment by Greatbigben** [comment]
this is merged so closing this
