### ISSUE TITLE
Buff ductape

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#594]
### Expected Behaviour

Type here what you expect to happen.

You get ductape
### Actual Behaviour

Type here what actually happens.

You make shitty sord
### Steps to reproduce the problem

Buff ductape, make it so you can: 

Cuff people, taking 0.50 mins to remove

Silence people when applied to mouth

Seal ONE tile worth of hull breach

Use it like holotape to cuck up doors

Use it as badages that are crappy as hell

Wear it as a shitty scarf

Make a sock mace style horror when soap is used on it

Make it so you can mark areas like with the sign projector and holotape

Duct tape your ears shut to act like earmuffs 

Make a horrifying balaclava out of the stuff

And finally: Apply duct tape to neck to drag someone along the ground (from harm grab) and choke them

Inb4 adam

**Comment by Kmc2000** [comment]
Oh and make a noose and hang someone with it taking a long ass time

**Comment by ghost** [comment]
So 

Some incredibly useful tool that has more versatility than anything else in the game and requires minimal effort to get and is just as good as cablecuffs which at the least come in a limited supply, provide flashbang resistance, provide the ability to mask your identity, kill people, and muzzle them, all at once

and completely replacing the use of multiple items we already have, including gauze, craftable bandages, holotape, et cetera

somehow managing to patch over an entire hole in the station floor with one roll of the shittiest substance on earth 

and forever taking us farther and farther away from the 'futurey spacey' feel of ss13 and making it 'earth tech but with laser guns and clowns and if you die you go outside' because at this point it's basically just australia

So no

against

too much shit for duct tape to do

at most it should have three extra uses

Sealing doors temporarily shut

Patching up cracked windows

And duct tape cuff people which lasts for 0.2 minutes, shittier than cable cuffs.

Or just remove it and the shitty armory entirely because we don't need more impro weapons and the gear is already overpowered.

**Comment by ShadowDeath6** [comment]
bad idea 2 op >:^(

**Comment by ToGWtF** [comment]
duct tape + paper sticky notes when

**Comment by Time-Green** [comment]
I agree with adam here.
But the ghetto muffle wouldn't be a bad idea axtually.
