### ISSUE TITLE
The Great Shield Change

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#613]
Riot shields, eshields, and new shields, oh my!

So, a few ideas. Separated into neat headings!
# SIDEGRADE RIOT SHIELDS

Aight, so, Riot shields are a bit underwhelming right now- yet downright OP in some cases.

I say we buff them, but make them a little more situation-specific!

+100% chance to block disarms
+Vastly increased chance of blocking melee weaponry
**+VASTLY INCREASED CHANCE OF BLOCKING TASERS** (riot shields are typically made of Polycarbonate- polycarbonate doesn't conduct electricity.)
+No longer shocks you when attacking electrified grilles with it
_-NO LONGER BLOCKS DISABLERS/LASERS_
-Bullets have a chance to penetrate the shield, doing decreased damage to the holder. Shield breaks after 3-4 penetrations.
-Only protects from front and squares diagonally in front.
# NERF ESHIELDS

These are a bit of an instant "I win" button for nukies against sec. Nerf 'em a little.

-Severely decrease chance of blocking bullets- this'll actually encourage people to use the riot shotguns!
-Raise the cost so you can't get both an eshield and adrenals, because that's a REALLY ridiculous combo cafe
-Make it a normal-sized item so it doesn't fit in pockets.
-Same nerf as above shield- only protects from front and front diagonals

**Comment by Super3222** [comment]
REGARDING ESHIELDS:

> These are a bit of an instant "I win" button for nukies against sec. Nerf 'em a little.

#394 

Anyway, I like these some of these ideas. Especially the ballistic shield (minus the reflecting bullets), but can we figure out a way to not make science more overpowered.

**Comment by ShadowDeath6** [comment]
eshields already got an issue, don't make another one for it. Shields are already extremely powerful and don't suffer from unuse, so I'll be :-1:ing this.

**Comment by ParagonPrime** [comment]
...I'm making a general issue on shields as a whole. Riot shields seem to be in a really weird place right now and frankly too determined by RNGesus, and I'd like to change that with a little more specialization.

**Comment by Kmc2000** [comment]
I actually made ballistic shields, an extendable one and a flash mounted shield to fulfill my siege addiction.... I mean for the lols.... 

So if this doesnt get nuked by adam i can send em yoir way

**Comment by ToGWtF** [comment]
I like the bubble shield idea kinda. on Bay theres a sort of portable shield generator that makes a force field that no one/thing can pass. Do you plan for the bubble to be impassable? or just blocks projectiles/thrown objects?

**Comment by ghost** [comment]
Just make riot shields have a 100% chance to block any melee attacks and block stuns from stunprods/stunbatons as well so that it doesn't go right through and kill you.

Now you have to use ranged attacks. Whoop de doo.

That's all the buff they need-invulnerable versus melee, weak versus ranged.

Same with eshields-near invulnerable versus bullets, invulnerable versus energy weapons, weak to melee.

Increase eshield cost by 1 TC so that you can't buy eshield + Carbine on standard 30 TC without some legitimate finagling.

Bubble eshields is dumb. /tg/ tried this with shielded hardsuits for nukeops and it's bad and dumb.

Ballistic shields not only doesn't make sense from a logical point of view, but it'd also be really unbalanced.

So, not only do you gain almost complete invulnerability to gangs-in some cases even killing the shooter because bullets are far more debilitating and harder to see-and nukeops, who only use ballistic weapons, meaning that you have to land upwards of 15 shots on them, meaning that they either HAVE to take a carbine and unload a full clip into you or die.

Not only does this COMPLETELY invalidate WAR because if ops declare war cargo will just buy shitloads of ballistic shields and then almost no nukeop weapons short of bombs can penetrate them and ops can't get their hands on lasers.

Not only does ballistic shields function as a reverse eshield available to fucking security, invalidating 90% of all traitor ranged items such as the revolver or stetchkin where at the least it lowered damage but didn't nullify it entirely.

Not only with it taking 15 hits to break but you'd unload 3 full clips of a revolver into it to even make the first couple hits connect and security would still keep coming.

Not only would the ballistic shield not take damage into account.

But it also blocks energy weapons anyway just for the sake of it, meaning it's a good GG against ops who manage to use lasers instead of bullets anyway because fuck you, no balance?

Do you have any idea how unbalanced this is?

You're complaining that 'eshield is too overpowered lol' and then you're giving security the exact same thing with a ridiculously high block chance versus lasers and disablers, FORCING people to use tazer bolts, which are obvious, easy to dodge, on a low clip, and facilitating stun combat, the one thing we are trying to remove, meaning that not only is there no counter for this aside from a nukeop or a gangster getting into melee range-And getting into melee range with security is a bad fucking idea, because they can just harmbaton you to death-But that it actively punishes you for using ANYTHING, including shooting at someone with a ballistic shield on their back because they suddenly pulled it out, shooting around and suddenly getting GG fucked by tons of bullets coming right back at you, forcing you to waste shitloads of ammo on the one fucker carrying two ballistic shields, and then cockblocks you for pulling out a laser because it will still block the lasers anyway?

So basically ballistic shields force stun combat, are overpowered, don't take into account weapon damage, nerfing and making WAR entirely impossible short of buying mechs, forcing people into melee range where they will almost immediately die versus security because lol stunbaton, force traitors to spend three clips of their revolver just to bring down one guy carrying it and they will definitely carry it after 'tRAITOR HAS GUN' is declared and you bet your ass cargo will vomit them out by the shitload.

IT's traitor gear, available for security, at roundstart, facilitating every single issue we presently have with combat at the moment but in reverse. This isn't rock paper scissors, this is 'fuck you, fuck you, suck my giant murderboner cock.'

And then you give traitors an item that blocks all attacks incoming from any direction and makes traitor scientists who buy 4 of these and carry around bluespace batteries with 40,000 charge almost completely invulnerable to assault by security.

Because let's do the math.

There are, lessay, 4 security officers on the average round.

In the tazer there are 6 tazer bolts.

So 4 x 6 is 24. 24 tazer bolts.

And if if that's -2500 per tazer electrode impacting on the shield.

24 x 2500 = 60000.

So for 4 officers firing simultaneously with perfect accuracy on an immobile target that is not shooting and not killing any of them, that is 16 tazer bolts one of the shield generators will block, for one scientist with a bluespace battery.

Not only would this be a GG item on lowpop when there's almost no or no sec at all, but it'd be a GG OP item during highpop since a traitor can buy two of these, or one of these and adrenals, or one of these and meth, or one of these and a stimpack, and run around taking 16 tazer shots before he gets stunned and has to run off and go recharge for two minutes by wanking off in a locker before he goes sonic the fucking murderboner hedgehog again.

And again.

And again.

And again.

This is assuming that all of security is firing at him at once and NOT MISSING.

If you assume officers to miss 3/6 tazer shots, then basically he can plow through most of the security team without being stopped, especially if he just lurks in maint and stabs some officers in the cock.

And then not to mention but some admins would ban for disarming the traitor with the energy projector and call it antag hunting even when it's clearly not, leading to people being actively terrified of attacking the traitor in the first place out of fear of getting banned for an item that literally requires mass lynchmobs to defeat.

So assume the armory gets open and sec gears up to shoot ONE GUY. Assuming they all find him at the SAME TIME and not just get picked off one by one as he recharges for two minutes before continuing to murderbone, 

That's ONE GUY with this item.

Assume EVERY traitor buys it. On a round like DA, that's up to 12 people, with a shield that blocks 16 tazer shots, PER PERSON, if they all have bluespace batteries, or even just using highcaps 4 tazer bolts, meaning that they can juke and dodge more tazer shots than even an adrenal will afford them and kill all of security.

And god forbid a traitorling gets ahold of it because combine blocking any incoming attacks with sleepsting or blindsting or your inbuilt stun resist ability and suddenly you become an unkillable godmonster when you combine this with the shield and emp shrieks which drain tazers and stun resisting abilities.

Disablers would barely even have an effect because all the fucking energy guns in the armory firing AT ONCE at one guy with a bluespace battery combined with captain and HOS also shooting in disablers would only make the shield fail

IT'd be a horrible, unbalanced, overpowered nightmare, and if it costs anywhere less than 10 TC traitors can buy multiple of thme, and if it costs anywhere less than 40 TC operatives can buy multiple of them per operative and then you combine that with an energy shield and adrenals on WARops and suddenly your eshield nerf doesn't even matter because the leader just ran in with 12 shield generators, an energy shield, and a shotgun and took the entire armory to his dick and kept coming.

So uh.

I'm against it.

Heavily.

It's horribly unbalanced. With the new murderbone restrictions-or lack thereof-it'd lead to complete depopulation of the station on lowpop and be shuttle call tier for anyone moderately robust instead of some insane idiot who runs around in primary with it instead of hiding in maint slowly killing off sec one by one, render nukeops unkillable, render changelings even more unkillable then they are already supposed to be ect ect ect horrible unbalanced nightmare from hell.

The bubble shield is legitimately the worst idea I have ever heard of in the history of mankind and i'm the guy who says 'I should microwave this egg to make it cook faster.'

No no no no no no no  a thousand times NO.

**Comment by ParagonPrime** [comment]
updated to reduce adam's salt :^)

**Comment by ghost** [comment]
still shit
