### ISSUE TITLE
Cover mechanics!

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#614]
Let's add a little extra shooty fun!

Add a verb that lets you crouch. This adds a decent chance to have projectiles miss you when you're directly behind a table (+10% chance per tile away from the shooter) at the cost of slowing you down to a speed that's even slower than walking pace.

Also, add craftable sandbags (tablecrafted with cloth + sand) that can be built into makeshift barricades  with a somewhat higher (10-15%?) miss chance for anyone shooting at you.

Makes bunkering down a little more interesting, negates adrenals very slightly, and encourages breaching tactics if you know your enemy is well defended.

**Comment by oisin100** [comment]
Rainbow Six Siege mode confirmed?

**Comment by Super3222** [comment]
Hah, if this even happens imagine a sprite where your 2d spessmen is crouching

Buy revolver.
Shoot captain dead
crouch stand up crouch stand up crouch stand up repeat

**Comment by ShadowDeath6** [comment]
How would this negate adrenals, exactly?

**Comment by ParagonPrime** [comment]
Making "run around at sanic speeds as best way to avoid fire" a slightly less valid strategy.

**Comment by ShadowDeath6** [comment]
it would still be better than relying on RNG, though.

**Comment by ghost** [comment]
So making new sprites, new items, for every single currently existing item in the game to allow spacemen to crouch, making RNG lolrandom dodge a thing because someone happened to be on crouch and you didn't see even though you're vastly better armed than them?

nope, i'll save you the trouble and close this right now because there's no way there is going to be new sprites made for every single item in the game to accomodate people lying down

**Comment by Cruix** [comment]
The issue is not technical - it is easy to translate sprites downward at runtime in the code. Having the player crouch would look like crap, but it could be done. If you are going to close this issue, don't close it because it is impossible from a technical standpoint.
