### ISSUE TITLE
Brig and Map Revamp - Initialized by GreatBigBen

### ISSUE THREAD

**Issue by shrimptk** [yogstation13/yogstation-classic#64]
Just tryin' get that official go-ahead to start working on a massive map change. 

Check out the original thread to see our progress so far, see images, and input your thoughts.

http://forums.yogstation.net/index.php?threads/revamping-brig-area-including-labor-camp.8482/

**Comment by BadminBen** [comment]
Officially Official

**Comment by Super3222** [comment]
Could you also give the HoS and Warden access to the external airlocks near the pods? If they already have it, maybe security officers. If the Warden gives you a hardsuit and tells you to go look outside for someone potentially breaking in, I think officers shouldn't need to go around the station and through escapes or arrivals to catch them.

Currently they don't have it, since they don't start with external airlock access. And they have those hardsuits for a reason.

Labor camp lockers, each locker having individual access to a certain the designated card, would be awesome. So if they survive the gulag, they come back and can pick up their stuff without looting other peoples gear.
