### ISSUE TITLE
AI starting lawset

### ISSUE THREAD

**Issue by ToveyAyyLmao** [yogstation13/yogstation-classic#651]
So pretty much in other stations they have it so at the start of the game the AI's law set is randomly selected between Asimov, paladin, corporate etc which is really useful because it means interesting ones like corporate don't go ignored. Ideas?

**Comment by oisin100** [comment]
Sounds like a nice idea. Cant wait to hear all the salt though...

**Comment by Time-Green** [comment]
This was actually a thing before on yogs.
But It got reverted for some reason.

But yeah, I like it

**Comment by ShadowDeath6** [comment]
No, fuck paladin, I'm gonna make an issue to remove the board from the upload, thanks for reminding me.

**Comment by ToveyAyyLmao** [comment]
Although I agree Paladin sucks dick, Ive literally never seen corporate ever uploaded because there is literally no reason to do it. And its a really fun law set. Especially when the AI looks at the market value for a live xenomorph...

**Comment by ParagonPrime** [comment]
Corporate is actually really fun and more appropriate to what NanoTrasen is than Asimov. There was one AI that, whenever he was roundstart-Corporate, would always turn off all the lights in the station to save expenses. Made for some really good RP because I was a light-obsessed Chaplain and was constantly battling him over it.

I'd actually be in favour of having Corporate appear more often at roundstart- though Paladin, I agree, is a bit excessive to have with ABSOLUTELY ZERO work.
