### ISSUE TITLE
Rev mode should default max heads of staff

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#660]
### Expected Behaviour

An massive war for the station, the heads of staff banding together for their lives
### Actual Behaviour

The RD is the only head of staff and gets killed in 5 minutes

**Comment by Time-Green** [comment]
Pretty good idea. Would make people aware of the gamemode if they payd attention. But yeah, not like that is hard in a rev round.

**Comment by AsV9** [comment]
There is already a proc for this I believe.

**Comment by ShadowDeath6** [comment]
Remove rev and this wouldn't be a problem reeee

**Comment by Super3222** [comment]
The thing is, and I believe this is from my hunt to find the truth about RNG, the game checks to see if anyone has there's assistants first, and than head roles, THAN security, and than other jobs.

That's why if you set a headrole low, and have for example, clown for high, if no one's even aiming for that headrole you'll get it.

Now, I'm not too sure about randomizing the headroles and forcing someone who could be possibly NEW to play a headrole. That's my biggest issue with this, but I can see where you're coming from. It's pretty shitty for a rev round to end in the first five minutes.

So forcing people to fill in head roles is a bad idea. If a traitor has to steal the blueprints, should CE be forced? No non-antag wants an antag to win, but it happens even in the shittiest scenarios like the one you described @ToGWtF

**Comment by FluffySurvivor** [comment]
Rev unlocks at 25 pop, so if round starts with fully staffed command at say 27 pop it's a dead giveaway it's rev

this doesn't work
