### ISSUE TITLE
Borgs can't get out of security camera viewing

### ISSUE THREAD

**Issue by Universum01** [yogstation13/yogstation-classic#687]
When your a Borg and you view a camera through a monitor you get stuck, since your not standing at the screen moving around does nothing.

I did fix it for me but i had to leave and rejoin and had about 0.5seconds to click the monitor again so i could cancel, took a few trys but i got it.

https://www.youtube.com/watch?v=5Za8SL5wjrM

**Comment by 00aquir** [comment]
On one of the tabs, there is "cancel camera view" option.
Nevertheless, the camera window **should pop up** every time you're in camera view until you click on "cancel".

**Comment by Greatbigben** [comment]
did you have it minimized?

**Comment by 00aquir** [comment]
(You cannot minimize the camera window.)
As borg:
 If you are at the camera screen and in camera view, and you select any options in the camera list window, no problem. 
 If you are in camera view and you or someone moved you away from the 1 block range of the camera screen **and you click anything other than the "cancel" options of the camera list window** (e.g. selecting other cameras), the camera list disappears and you remain in camera view as long as you are within the view range of the camera screen (which you can't see since you are in camera view) or you press the "cancel camera view" button under one of the tabs. (Otherwise, if you manage to move away and then try to return within the view range of the camera screen, you'll not be able to reach it because the camera mode will turn back on immediately,  so you have to press "cancel camera view" anyways to exit properly.)
