### ISSUE TITLE
Blob tiles have too little health.

### ISSUE THREAD

**Issue by Time-Green** [yogstation13/yogstation-classic#696]
### Expected Behaviour

Die because blobs eats you
### Actual Behaviour

Guitar instakills a normal blob tile
### Steps to reproduce the problem
1. Get a guitar
2. Play viva la vida (optional)
3. See the blob crie in agony as you quickly come closer with your music of death

**Comment by X-TheDark** [comment]
The reason for this is because the new damage calculations were ported, but not the new resist system /tg/ uses.
The result is as follows:
`/obj/effect/blob`
`__var/brute_resist = 4 (instead of /tg/'s 0.5)`
`...`
`__damage = max(damage * brute_resist, 0)`

Fire damage seems to be consistent with /tg/'s version.

**Comment by ghost** [comment]
I'll fix it unless someone else can do it sooner.

**Comment by timkoster1** [comment]
HAHA I AM GONNA FIX IT.
