### ISSUE TITLE
Re-add abduction to mode rotation

### ISSUE THREAD

**Issue by MacHac** [yogstation13/yogstation-classic#705]
### Issue

Abduction, while being sound in theory and fun in practice, was originally removed because the crew had little real way to combat the alien menace and, in fact, rarely saw the abductors at all if they knew what they were doing.  This led to abductor rounds looking very much like extended rounds, at least until they got overrun with horrifically OP spiders.
### Proposed solution

I propose that Abduction be added back into gamemode rotation, but as a secondary mode like changeling.  This would mean that abductor teams could only spawn alongside traitors and possibly changelings.  This would fix the problem of abductor rounds being largely uneventful.  Additionally, the worst glands (bodysnatcher, spiderling) would be removed and possibly replaced by more benign varieties.

**Comment by ShadowDeath6** [comment]
I wouldn't like it to be as common as a gamemode, MAYBE have it be like a 10% chance to spawn in regular traitor ONLY, so we don't have all the fuckery with lings that happens right now.

**Comment by Greatbigben** [comment]
it should be more like 25% its a great addition to the round and makes interesting side effects to the ones that get abducted

**Comment by Time-Green** [comment]
It's alot of fun.
Aaaanndddd. Please fix the abductor monitor, it needs alot of time to load, enough to get your agent killed.

**Comment by Greatbigben** [comment]
i forgot that the monitor was bionked

**Comment by ShadowDeath6** [comment]
I for one find abductor mode one of the least fun modes since you can literally be fucked over permanently or killed because of an abductor gland. If it appeared every 4 traitor rounds we would probably end up with a lot of rounds ruined because the objectives are either retarded or the glands are so annoying you just kill the abductee. If you could remove the gland it would bw fine, but you can't, so you might as well kill yourself because you stun for 5 seconds literally all round because you have sline vomit gland or you get 200 quadrillion brain damage from incurable brainrot.

**Comment by ParagonPrime** [comment]
I think Abduction SHOULD be modified slightly to make it more interesting and focused-

First, remove all glands that are harmful, or modify them so the benefits stay but the negatives are gone/severely reduced.

Second, add a direct objective to the Abductors- get x many Research Points by the time the round ends. Research Points are gotten simply by abducting and experimenting on people and animals, with different effects:

Monkeys and dead humanoids: 0.5 RP
Living humanoids (Phytosians, Unathi, Preternis): 1 RP
Augmented humanoids, humanoids listed on the crew manifest as Security staff: 2 RP
Humanoids listed on the crew manifest as Head of Staff: 3 RP
Humanoids listed on the crew manifest as the Captain: 5 RP
Changeling: 8 RP

^The last bit also means that Abductors should be able to appear in the same round as lings and be able to abduct them for HUGE POINTS. This system also means that abductor scientists will observe a tiny bit more and abduct high-priority targets rather than "first guy who walks into maint"

Finally, make it so that all abductees are released with two main objectives: the weird ones we currently have, and one that says "if you are present at an abduction, assist your masters in any way possible". Now, this doesn't mean "go make a stunprod and cable cuffs and jab people yourself"; it just means that Abductors can pop into a room with you and only one other guy, and you're expected to fully help them steal the person away. It's great for raising paranoia to hair-trigger because _no longer is proximity to others a safe thing; they might very well be abductees themselves._

**Comment by MacHac** [comment]
If a changeling wakes up on the mothership, the abductor team has already lost, lol.  That's what the probe is for.  Plus, the captain is actually usually a pretty easy target if you can sneak up on him, as he's often alone in his cabin/the bridge/the upload.  I do like the idea of a certain crew member(s) giving more RP, but giving points for monkeys and corpses would just lead to corpseductors and/or infiltrating cargo and stealing monkey cubes in large quantities without actually experimenting on anyone.  The harmful glands are there to ensure that players have some motivation not to offer themselves to the alien menace, although I would be removing the ones that destroy people's rounds like bodysnatcher and spiderling.  Without harmful glands, abductors would end up like borers i.e. everyone begging to be abducted instead of avoiding the greys like they should be.

**Comment by MacHac** [comment]
Also, shadow, the viro gland doesn't infect the person that it's in.  It just turns them into typhoid spessman.  Most of the worst diseases are blood spread only, and if virology is on their shit they can pump out cures in quantity.

**Comment by ShadowDeath6** [comment]
The virus gland virus isn't curable. It can be treated and go away, but you can just get the disease again.

**Comment by MacHac** [comment]
You have to pull out the gland with surgery.  This is the sort of thing that makes abductors antagonists.
