### ISSUE TITLE
Make emagged mediborgs more functional

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#706]
Since we're still working on mediborgs (hopefully?) and they got the defib thing, I think it's time that they got a more functional traitor item upon emag. Fluacid currently literally does nothing because of the way sprays work, so I was thinking that they get a hypospray of certain dangerous chemicals.

I can't remember if there was an issue for this, but I was thinking the hypospray would have-

Formaldehyde
Nulvoscine (whatever is in mimanas and mute sting)
Neurotoxin (the drink that stuns for ages)
Amantin (mushroom toxin)
Initropidril

These chemicals would charge fairly slower than the regular hypospray and the new hypospray would be called "suspicious hypospray" so if you examine a borg it's pretty obvious.

**Comment by FluffySurvivor** [comment]
like mediborgs aren't broken enough

**Comment by Greatbigben** [comment]
mediborgs are Op enough against this

**Comment by ShadowDeath6** [comment]
No they are not OP in the slightest. 
Literally every borg module has an instant stun before or after emagging or an extremely lethal module, i.e esword or lasergun. Medborg does not have anything other than a 15 damage saw which can be countered by running away.

**Comment by ParagonPrime** [comment]
^this

Emagged medborg should be all about stealthily creeping up, making friends with whoever's gotta die, and at last moment, JAB 'EM FULL OF DEATH

support

or maybe even give them the bioterror sprayer because nobody ever, ever uses that

**Comment by ghost** [comment]
The mediborg acid spray, due to the changes, is entirely and completely nonfunctional.

Every other borg module is much better.

Janiborgs and clownborgs have lube. Secborgs are secborgs. Engiborgs have stun gear and a shitton of stuff to kill you, wall you in, ect. Minerborgs have heavy weaponry and stun gear. Serviceborgs have an instant KO chem that permafucks you and makes you die of toxin damage and a method of instantly applying it.

Mediborgs do 5 damage per acid spray.

Yeah, me and shadow agreed-they need this buff.

Since they'd still be entirely melee only, in anything more than a 1v1 they're toast unlike any other module and they have to get in flash range, meanwhile 80 ion bolts flies through the air.

**Comment by ghost** [comment]
Bioterror sprayer is never used because it's shit.

All other modules have a reliable stun-even standard, which comes with a stunbaton and esword. 

Mediborg having-

Neurotoxin which is an instant stun, but since the hypospray recharges so slowly, you'd both have to choose between 5u neuro and hoping you can kill them quick enough or 10u neuro and only having enough neuro to deal with 2 more people for a while if you use it in 10u amounts.

Neuvulscine is mute toxin. You can see the uses of this.

Amantin is a toxin that hits you for a stack of toxin damage the last second it's out of your system. The longer it's in you the more damage it does. It's useful for stealthier assasinations where people won't be able to connect you with getting injected and then suddenly ded 5 minutes later.

Inidropidil is the only truly lethal immediate chem medborgs have-remember, any other borg module can kill you in seconds using just one module. Medborgs, without initro, would have to saw you to death while dodging laser fire and hoping they kill you before neuro wears off. Any other borg module has shit that kills in seconds, like secborg lasers. Initro would fufill that purpose-5u would make you ded or in the red in about 10 seconds, and if your heart stops that's gg. Note that it also has a chance of killing really, really slowly, hitting for 5 tox damage every 3 seconds, meaning that it can either take forever to kill one guy, or hit for 25 toxin, knock out his air and stop his heart in the first three ticks.

Formaldehyde is a potent toxin that decays into histamine, another potent toxin. Unlike initro it's not rng randomness that might not kill you, but it's slower to kill you than initro-a staple poison to initro's LADY LUCK SHINE ON ME TONIGHT

**Comment by X-TheDark** [comment]
One reason I haven't given medborgs a toxin hypospray already is because it's so hard to balance. Here's the thing. Yes, other borgs have better things both emagged and not-emagged than a medborg. But they are completely obvious. What is easier to notice - being injected with something that **might** be lethal or instantly being stunned by engborg/secborg/serviceborg? That's why emagged borgs aren't THAT good, because it's completely obvious.

Also, giving medborg BOTH instant-stun and a way to prevent people from informing others about this...really? No, seriously. You think giving STUN AND MUTE to a single entity is a good idea? That's also part of the reason why you can actually combat emagged borgs - you can call out them stunning you and it requires some form of communication silencing to be truly effective (which calls for either AI help or you manually turning comms off and stuff).

Other than that, I support the medborg emagged module to be replaced with a better one since the current one was broken due to changes to reagent application via spray.

**Comment by ShadowDeath6** [comment]
Not like stunning and muting is hard for any borg. They can just shit on tcomms with ctrl-click, or in engi's case, decon every single machine and space them.

**Comment by utahclock** [comment]
how about making mediborg saw do more damage ? instead of 15 say 30-50 ?

**Comment by Super3222** [comment]
> how about making mediborg saw do more damage ? instead of 15 say 30-50 ?

There's an energy saw for that!

**Comment by Groudonmaster** [comment]
50 is just a tiny bit op. 2 hits and they're done for. I can live with the 30 damage though.

**Comment by ShadowDeath6** [comment]
30 damage still not as good as lasers rrreeeeeeeeeeee

**Comment by utahclock** [comment]
Im working on an emagged version that will allow mediborg to have rapid syringe gun with chloral hydrate... Still have a couple kinks to work out but it may be enough of a buff to satisfy ya

**Comment by ShadowDeath6** [comment]
Working on coding in the hypo, holy fuck initro is ungodly OP, we need to make this hypo regen REALLY slow.

**Comment by ShadowDeath6** [comment]
amatin/amantin is apparently not an existing thing, so I guess it's amatoxin.

**Comment by ShadowDeath6** [comment]
update: amatoxin is ass and does shit damage, however it lasts long enough in the body to kill someone from full if you dump the entire 30u into them. Crit should be like 15-20u of it.

**Comment by X-TheDark** [comment]
Closing due to utah implementing the Syringe Gun with Tirezine. Feel free to suggest additional changes/balance issues/etc in a new issue.
