### ISSUE TITLE
Magnitis is completely borked

### ISSUE THREAD

**Issue by Notamaniac** [yogstation13/yogstation-classic#716]
### Expected Behaviour

Catch virus, cure it with iron, be happy
### Actual Behaviour

Cure virus with iron, catch it again because you don't develop antibodies, then continue to have symptoms after curing it a second time and wearing a biosuit, without the disease showing up on the medscanner
### Steps to reproduce the problem

Catch magnitis and cry

**Comment by ShadowDeath6** [comment]
Was this from abductors or just random

I think this happens with all random diseases

**Comment by Notamaniac** [comment]
Random virus event

**Comment by AsV9** [comment]
![](http://i.imgur.com/ye3BT1r.png)

I am convinced this is broken.

**Comment by Nirnael** [comment]
According to the code, magnitis can't be cured, even though there is a cure coded (why even, i don't know). It was made incurable since it's creation. If you want i can make it curable.
If it actually gets cured, then there is some major fucking bullshittery going on cause there's no fucking way it can get cured the way it's in code atm.

**Comment by oisin100** [comment]
Fixed in #951
