### ISSUE TITLE
Buffs sec 

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#731]
### Expected Behaviour

Sec is a major threat to group antags
### Actual Behaviour

Sec is consistently curbstomped every group antag round
### Steps to reproduce the problem
1. Be good sec and implant people
2. Run out of implants because 8 implants to 40 revs/gangs
3. Go to cargo
4. Get killed by spears or guns because cargo is a cesspool of villainy
5. Manage to order implants but only get like 1 box because cargo spent it all on ablative armor crates

Two solutions- 
Make loyalty implants cost WAY less supply points, like 25 or 30 down from 40. 
Add two lockboxes of implants in armory instead of one, giving sec 12 implants.

**Comment by ToGWtF** [comment]
tg is removing ordering implants from cargo kek

**Comment by Super3222** [comment]
If we remove the loyalty implants from cargo, I'm porting the Nanotrasen auto rifles from /tg/ instantaneously.

Anyway, revs/gangs are easy to control. As long as you have at least 2-3 security officers who understand the easy fundamentals, and you all don't split up, gathering up loyalty implants is easy.

**Comment by ShadowDeath6** [comment]
More like 5 officers and several heads of staff that know what they're doing

**Comment by EMT321** [comment]
Making the loyalty implants cost 30 rather than 40 would be a nice change.

**Comment by apneaman** [comment]
Sec needs an upgraded stun proof vest against  batons and tasers but would still be vulnerable to disablers. Nake it something RnD would have to make or an armoury item . I stopped playing sec because all that happens is the second your focus is on someone else you cop a stunprod in the back followed by many toolboxes and now the mob has a full sec kit and access . Even if you kit up with all the riot gear and appear to be an threat a naked assistant can still drop you with a prod easily

**Comment by apneaman** [comment]
From the rounds ive played that group antag has lost. The sec officers in general get destroyed immediately the only thing that saves the day are the secborgs and a competent HOS
