### ISSUE TITLE
Rev rework idea.

### ISSUE THREAD

**Issue by penguinfisher** [yogstation13/yogstation-classic#744]
As of now rev rounds last 10 minutes and are the shittiest thing ever mostly because rev rounds can start when there's 49 assistants and one research director. RD dies and boom- round over.

Obviously make rev start with every head role filled.

But don't make headrevs right as the round starts. The round type will be rev- but the antags don't spawn right away. Randomly choose 3 non-implanted people who have headrev get a message (maybe 10 minutes into the round?) saying "You don't get paid enough for this! It's time to show centcomm who's boss! Replace the head of staff with your fellow rebels." or some shit. 

The point of a revolution isn't to murder whoever's in-charge. Well maybe it is- but the point is to spark a change. Replace the heads of staff with fellow revs kind of like how cybermen have to get into head of staff positions as the second objective. The first being to eliminate them.

My idea is to make the flash to convert people have a 5 or 6 second cooldown kind of like the gangster pen but not as extreme but is still reliable.

This would stop scientists from seppuku bombing the station since the goal would be to REPLACE the heads and not kill everything that doesn't have a little R by the name.

Anyone else have any input to improve it? I'm tired of 10 minute greytide rounds.

edit: The shuttle can be called and end the round early with this gamemode to stop rounds from going on into infinity because of people not being placed into a command position.

**Comment by ShadowDeath6** [comment]
cool

**Comment by oisin100** [comment]
The rev spawn delay is actually quite a nice idea.

As for the cooldown on the flashes its been thought of before. Just all of us are too lazy to implement it.

**Comment by apneaman** [comment]
Like the delay idea alot it makes sense. Also would like to see something to slow down cults as they either fail or completely dominate in 5-10mins

**Comment by Super3222** [comment]
> Obviously make rev start with every head role filled.

Like I said in the last topic that addressed this issue, this is guaranteed to be a horrible idea. First, we shouldn't be forcing job preferences for people.. I mean, unless you are an antagonist of the mode you shouldn't be forced into a certain job. Second, there's the looming danger of new players getting forced into these head roles which is a bad idea as well. For some adept and veteran players, it's really no problem to be forced into some of these roles, but new players will have trouble trying to understand the concepts of their job and what they are suppose to do.

Also, forcing people to play Captain is not fun. Neither is forcing people to play HoS. Not fun.

Moving on, I like the aspect of "silently" replacing each headrole of the station. It's actually a pretty good idea, and makes sense of the idea of revolutions. To bring change or whatever. I can agree though, rev (currently) is respectively a shitty gamemode which can either be full out 3 hour long war or a 5 minute round. But yeah, forcing people into roles is generally a bad idea.

**Comment by penguinfisher** [comment]
I never thought about forcing head roles when I thought of this idea- I meant for it to trigger rev AS apart of secret when the head slots are filled. 

Although to make it work it'd probably have to force head slots since I don't have a dicking clue how byond choses what type of round it is or how antags are chosen.

**Comment by FluffySurvivor** [comment]
Wooo let's delay the 10 minute grief rounds by another 10 minutes! HOW GENIUS AND INTUITIVE!

**Comment by apneaman** [comment]
looking from the perspective of general player dynamics in any group antag matches

i think it actually gives crew a chance to set up and be prepared without knowing it and get settled into a round so when an Rev starts a response can properly happen and its not just people being caught out in the opening seconds and leaving things not set up or just a mad assistant rush.

 ex. engineering setting up engine/power , all Medbay or science being turned in under a minute and that whole area going to shit or being abandoned. Also sec on average head to brig at round start for extra gear so there's almost always no sec on patrol or at their stations for 1-2 minutes at round open. Borgs go to robotics for power cells and even AI is distracted  

 not saying it wont delay the grief but it could make for much longer rev rounds

**Comment by Super3222** [comment]
How about this:
- We keep your idea about 3 nonimplanted people turning into revs 10~ minutes into the round. because centcomm only promises minimum wage
- Revs will get a flash upon that time, sent to them by the Syndicate
- Revs also receive a spraycan for fluff stuff, maybe it'll have a special use in the future
- The rev flash will get a 2-3 minute long CD, similar to the gang pen.

The conditions of the mode are:
-Exile the heads to another z level (not centcom)
-Replace ALL the headroles with revs. By wearing their ID's / making new ones that match their name.
-Escape on the EMERGENCY SHUTTLE (let me specify nooot pods) with the replaced headroles on board

If all the heads are exiled (and alive), the headroles are replaced with revolutionaries, and they have escaped on the shuttle and to centcom than the revolutionary receives a major victory. Congratulations, you win ss13.

If all the heads die, but they are exiled after the shuttle docks at centcomm, and at the same time all the other conditions were met, the revolutionary receives a minor victory. Nothing to gloat about.

If none of the heads are exiled (alive or dead), but the other conditions are reached, once the shuttle docks at centcom it's a neutral victory.

If none of the goals are reached at all, and the original heads make it to centcomm, the crew gets a major win. Even if you've replaced the heads at this point.

If none of the goals are reached at all, and the shuttle makes it to centcomm, but there's revs onboard than it's a crew minor. With no revs on board, it's a crew major.

If all revolutionaries die, than mulligan or round ends. Depends on how far the round has gone and the state of the station (admin controls this?)

To clarify some things, this means that when all the heads die the round will NOT reboot.

---

So lets say in the worst case scenario, you don't manage to replace every single one of the heads and you've made it to centcomm. (assuming you've exiled all the heads)

You get 1/5 or 2/5 of the heads replaced, but they are all exiled somehow.
Neutral victory. You didn't make your revolutionary point, and have failed at completing one of your objectives.

You get 3/5 or 4/5 of the heads, but you are missing one. Each one of the headroles are exiled dead or alive.
Minor Victory. You haven't exactly made your point, but you've at least 

---

"HELP I'M STILL CONFUSED AND NEED FURTHER CLARIFICATION ON WHAT YOU JUST TALKED ABOUT SUPER"

One. You need ALL the heads exiled and off the station (onto the asteroid or some other z level).
If you don't, than you do have not completed this objective. If the other objectives are uncompleted to, crew minor. if they ARE, than neutral vic.

Two. You need to replace the heads, and this will only be accountable if five revs have escaped on the **SHUTTLE** as each one of the heads.

So you exile all the heads, and you don't replace them.
Neutral victory. Revolutionary didn't complete broadcast their point, and made themselves seem like actual terrorists (if they haven't been already).

Uhm, just ask me for anymore questions.

FAQ:

'but what happens when some asshole rev gibs all the bodies'

they get jobbaned. let an admin fix it at that point.

'hey. some asshole killed all the heads. what do we do now?'

You clone them, replace them, and send them into exile for their 'corruptness'.

**Comment by penguinfisher** [comment]
yes all of this yes^ i hate current rev.

but for the exile to work maybe give the head revs a tool that can spawn exile implants so the CE and captain can't hide on tcomms and cause revs to minor. 

or give 4/5 + 5/5 heads replaced and exiled major because of above.

**Comment by ghost** [comment]
okay that's a good idea except

heads will never let themselves be exiled

security will stomp all over the revs if they can't kill heads and only replace and heads will just deconstruct the mining and labor consoles and weld all the external airlocks

**Comment by darkwahn** [comment]
Having to keep the heads alive in any way is pretty shit, exile or kill should be the condition.

**Comment by Super3222** [comment]
I forgot to mention this as well. You'll need to cooperate with your revs. Once you exile the heads, you HAVE to make sure that they don't escape. By simply guarding them until the shuttle docks on centcomm. So cooperation is a must, since you'll basically be splitting up your army of revs.

@penguinfisher : 

> give the head revs a tool that can spawn exile implants so the CE and captain can't hide on tcomms and cause revs to minor.

I know that exile implants prevent people from entering the gateway... but I can see what you're saying. Correct me if I'm wrong, but with that idea all you would need to do is inject the heads with an exile implant and BOOM. Objective done. I'm not so sure about that to be honest... it sounds far to easy.

@AdamElTablawy : 

> heads will never let themselves be exiled

We all know the heads won't ever give up, that's why they have to be hunted down. That's why they have the option to exile themself, suicide, give up, or fight.

Now if they do give up, the revs wouldn't have a legit reason to just go ahead and kill them. For a MAJOR win, they must have the heads ALIVE as exiled.

If they fight, by either running, they are bound to get caught. If they don't, and the round drags on for ages, than that's when admins intervene at that point.

> security will stomp all over the revs if they can't kill heads and only replace

That's why the revs have to fight back against the opposition, they are free to massacre security members. They can either swing for the minor win, and send the heads corpses into exile, or try to test their luck by killing the heads, than cloning them, tying up the clones, and sending them to the gulag / asteriod / aboard the whiteship and onto KS13.

> heads will just deconstruct the mining and labor consoles and weld all the external airlocks

Yeah, that sounds like an IC situation to me to be honest. If the heads won't let themselves be exiled, than the revs are free to kill them. Technically they still win if the heads are dead, it's just that it's a minor victory and they've stooped to Nanotrasens level.

Furthermore, those things can also be easily fixed with competent revs on your side. Also research... technical storage ... etc.

@darkwahn : 

> Having to keep the heads alive in any way is pretty shit, exile or kill should be the condition.

Hey, it's always been an option in the current rev mode. If you aren't a brute, but a man with a plan, than this'll be an easy task for you. However if you feel like leading an army, massacring the heads, and dumping their mutilated corpses in labor, than it's fine as well.

Both aspects will work, it's just that keeping them alive is much harder, and therefore you will be granted a major victory.

You see, with a major victory, you have shown that you are not as cruel and corrupt as Nanotrasen. You have not sunken to their level!

More FAQ:

'HEY SUPER, W-W-W-W-WHAT IF THEY SUICIDE!!'

They can't suicide when tied up. And if they ghost, they'll still be counted as alive.

**Comment by ghost** [comment]
so

it'll be exactly like regular rev then because exiling is too much work and heads will just get bombed and die and absolutely nothing will change???

**Comment by ParagonPrime** [comment]
but adam

it's the same logic that drives nukeops to major victories rather than minor ones

people want dat greentext and they want a bigger, bolder greentext if at all possible

will contribute actual ideas later, but more exiling sounds goood
