### ISSUE TITLE
Just Another Revolution Game Mode Review

### ISSUE THREAD

**Issue by hawkname** [yogstation13/yogstation-classic#793]
Hi folks! Was looking at the forums and github recently when I noticed the whole dissent against the revolution game mode. Personally it is one of my favourite game modes because pretty much everyone has the chance to participate, but I can understand where the outcry comes from. I looked at the issues at hand as well as referred to other ideas and comments and thought out the proposal below. Feedback and comments are greatly appreciated. Hopefully this can kick start several ideas on how to better Revolution as a game mode.

**Revolution Game Mode Revamp Proposal**

**1. Current Problems**
- Powergaming and Metagaming; Round turns into who can kill/convert the fastest the moment sounds of flashing are reported.
- Deathmatch/murderbone round of grief and greytide.
- Little Teamwork and more of a bum rush.
- 10 minute game mode.

**1.1 Sources**
- https://forums.yogstation.net/index.php?threads/remove-rev-unironically.10134/
- https://forums.yogstation.net/index.php?threads/vote-removal-of-rev-gamemode.9092/
- https://github.com/yogstation13/yogstation/issues/153
- https://github.com/yogstation13/yogstation/issues/744

**2. Past Knowledge Review**

**2.1. Game Modes**
- Cult: Coordination and teamwork required to slowly grow the Cult.
- Gangs: Balanced; Gangs grow slowly due to cooldown of pen and territorial fights make for interesting set up of game.

**2.2. Revolutions and Protests**
- Paris Uprising of 1832 (June Rebellion): Death of General Lamarque sparks Revolutionaries to take up arms. Revolution fails to incite further rebellion amongst the populace and is quelled.
- Tiananmen Square Protest of 1989: Violent crackdown possible but difficult and made for more dissent.
- Occupy Movement of 2011: Growing dissent amongst people lead to occupation of territory.

**3. Proposed Solution**
- X number of Revolutionaries at round start.
- Extremely slow way of conversion, perhaps similar to that of Shadow Ling where the Revolutionary casts a 'spell' that takes time to rile up the anger of the targeted personnel.
- Revolutionary Main Objective: Eliminate all Command Staff/Head of Departments (Captain, HoP, HoS, CE, RD, CMO)
- Methodology: Progressively grow the Revolution, taking over department by department.

**3.1 Head of Department Present**
- Goal: Assassinate the Head of a Department (HOD) to expedite growth of Revolution.
- Upon death of HOD, all non-implanted personnel in the department – inspired by the violent act of Civil Disobedience – converts to the Revolutionary Cause.
- 1 random personnel belonging to the department – inspired to step up to lead the rebellion of his department – is established as the Revolutionary Head of Department (RHOD); If starting revolutionary/existing revolutionary is part of the department, he has priority to become the RHOD.
- Tables have turned, Security now tasked to identify and eliminate/implant RHOD.
- If RHOD is loyalty implanted, he becomes the Acting Head of Department, a loyalist who is now the target of the revolutionaries similar to that of a HOD. The department personnel are scared back into submission and no longer support the Revolutionary Cause.
- If RHOD is eliminated by Security, the department personnel are convinced of the brutality of Nanotrasen, and remain as revolutionaries until implanted individually or killed.

**3.2. Head of Department Not Present**
- Starting Revolutionaries should either locate a department head to start off the revolution with a violent and inspiring act (See 3.1), or utilise stealth and slowly convert their way through a department without a HOD.

**3.3. Victory Conditions**

**3.3.1. Revolutionary Victory Conditions/Loyalist Defeat Conditions**
- All Command Staff eliminated/flees the station (Captain, HoP, HOS, CE, RD, CMO).

**2.3.2. Revolutionary Defeat Conditions/Loyalist Victory Conditions**
- All revolutionaries eliminated/flees the station, or
- Station is evacuated (Only possible if no RHOD exists).

**3.4. Game Mode Revamp Objectives**
- Reduces powergame; No longer a flashing spree at start of round, but must remain clandestine and covert when the revolution is starting up.
- Discourage heavy handed security response and instead utilise riot control and arrests, yet does not completely remove the ability to turn to lethal weaponry if things go awry.
- Discourage revolutionaries from murdering crewmembers as they will form the backbone of the Revolution.
- Lessen the prospects of Metagaming as flashing no longer utilised and security will not have the knowledge to immediately turn to forced implants.
- Lessen the prospects of bum rush as converting is no longer simple and quick.
- Enforces teamwork amongst revolutionaries and loyalists in accomplishing goals of protecting heads.

Thanks for checking this out!

**Comment by ghost** [comment]
> random rev engineer welderbombs the Ce
> 
> everyone in the department is instantly a rev

good game

it'll just turn into one guy spacing the CE with a stunprod  and every single engineer on the station regardless of location instantly becoming viva

and then revheads will just suicide if they're about to be caught/blow themselves up/toolbox themselves to death if they're about to get caught and see people viva again

alternatively the RD is an idiot and kills himself in xenobiology, everyone in the department is now a revolutionary because a slime got hungry, but the RHOD is an idiot and gets immediately caught by security who know who he is and gets implanted right as a bunch of scientists are bombing the brig and now there's a nice long awkward pause as you hold a ticking bomb at your hand staring at the bloody corpse of a security officer because some guy you don't give a shit about halfway across the station got implanted in maint

**Comment by LesVegetables** [comment]
I still believe the easiest way to fix it is #744, have revs spawn after 10 minutes, add a cooldown to their flashes and have it only happen if all heads are present. 

It will be more rare and sec won't get trounced 12 seconds in by assistants with toolboxes and nothing to lose.

One of the other most important things should be some rule change about being the CE (or any head) and pointlessly hiding for 20 minutes, this benefits no one and you have already lost. Once there is only one head left they should get a special last man standing objective like "escape on the mining shuttle" or "alert centcomm via communication consoles." This would at least end these rounds faster.

**Comment by ParagonPrime** [comment]
Here's an idea:

If the original HOD/RHOD is **exiled**, _everyone in the department auto-converts to rev/deconverts- but only after a short-ish delay and a message_
If the original HOD/RHOD is **killed/deconverted**, _you have to manually convert/deconvert everyone in the department_

Balances it so that it won't automatically be a situation like Adam described, and might actually fucking lead to people exiling heads.

Also, suicides count as exiles ("well fuck, our head/revolutionary head just went and offed himself- that proves our faction is weaksauce and we should defect!")

**Comment by ShadowDeath6** [comment]
Make it so every rev goes through a 25% chance of deconversion if a revhead is killed/leaves the zlevel

**Comment by Super3222** [comment]
I like this idea, but what Adam describes as

> it'll just turn into one guy spacing the CE with a stunprod and every single engineer on the station regardless of location instantly becoming viva

honestly sounds way too easy to do, and there are other easy methods to killing people. Imagine a cargo tech bashing in the head of the HoP with a toolbox, and than all of the other cargo techs try to stop him. Instantly after the HoP dies, all of them are converted to revs. What?

Also what ParagonPrime describes as "short-ish delay and a message" won't help anything, it'll just delay the inevitable. And if that even happens, from my cargo example, imagine if none of the cargonians are even inside of cargo when the RHOD bashes in the HoP's ahead. One minute you're playing blackjack as the bartender with the drunken Captain, and the next second you're automatically a rev, which doesn't make much sense at all if you know where I'm getting at. Space Magic?

My problem it's just too convenient to happen, but I'm guessing it'll boil down to the amount of starting revs in a round. It'll just be like the normal rev eventually, having to slaughter all of security and the heads with them.

If a revolution gets to out of a hand, and there's one head left, they'll have to turn to giving up and calling the shuttle before getting trampled by an army of rebels or literally stun and kill every rev that shows up infront of the brig. Because if they can't turn them back with a loyalty implant (though this may be a feature, it's just not described) and they NEED the RHOD's, than it won't be pretty.

**Comment by ParagonPrime** [comment]
Hmmmmm.

Maybe insteant of instant conversion, the exile of a HOD can "fuel revolutionary ideas".

So, if we change to a longer conversion time as has been suggested, if you're in a department where the head dies, that conversion time drops far lower, yet you keep your loyalty. Now, on the other hand, if the head is KILLED, you become "disillusioned with the revolution" and the conversion time increases. This still applies to sec, slightly increasing the time taken for a loyalty implant to take effect, but hits less painfully than for the revs.

And again- this should continue to encourage exiling because it'll speed up conversion times a LOT.

As for conversion, the revs should be given a special verb. When spoken, a menu will appear, and you will begin to "brainwash" a chosen target adjacent to you to join the cause.

This again helps balance out the slower conversion time because now the AI and sec can't instantly cuck you over the moment it notices you with a flash, and it should decrease public blitzkrieg conversions a lot.

As for how long it takes to convert, well, that can depend. Maybe 10 seconds with "revolutionary ideas fueled", 15 normally, and 30 when "disillusioned"?

**Comment by hawkname** [comment]
The idea was to have a mixture of risks versus rewards:
- Revolutionaries want to immediately take down the Chief Engineer in full sight? Better expect Security to immediately realise what's going on and put the entire department in lockdown for mutiny.
- Revolutionaries want to quietly but slowly work their way in getting more members? Slow but quiet brainwash exists.
- Security want to quell the rebellion without having to manually implant everyone? Investigate the department, utilising riot control to avoid killing the RHOD, find the target and deal with him.
- Security doesn't want to waste time in identifying the instigator of the revolution? Better expect to slowly convert/cut down the angry mob, as well as risk losing the one chance they have in a fast deconversion.

Valid points on the suicide/accidental deaths! I was wondering if there was a way to identify how they died? Could help in mitigating this.

> One of the other most important things should be some rule change about being the CE (or any head) and pointlessly hiding for 20 minutes, this benefits no one and you have already lost. Once there is only one head left they should get a special last man standing objective like "escape on the mining shuttle" or "alert centcomm via communication consoles." This would at least end these rounds faster.

Last man standing sounds really good! The last head knows they can do something other than hide and could expedite the end of a round. But I have been in some rounds where the heads were killed off without a single one of them knowing it was a revolution, and if the last man gets such an objective he would surely know it's a revolution. We stand to lose this potential game mechanic.

> If the original HOD/RHOD is exiled, everyone in the department auto-converts to rev/deconverts- but only after a short-ish delay and a message
> If the original HOD/RHOD is killed/deconverted, you have to manually convert/deconvert everyone in the department

I like this idea too, and the rewards are pretty high that security would seriously consider exiling them. Would the exiled be able to come back? Would they remain revolutionaries or turn neutral? ShadowDeath's idea of a varying percentage of deconversion depending on how the RHOD was dealt with sounds like a viable strategy as well.

> If a revolution gets to out of a hand, and there's one head left, they'll have to turn to giving up and calling the shuttle before getting trampled by an army of rebels or literally stun and kill every rev that shows up infront of the brig. Because if they can't turn them back with a loyalty implant (though this may be a feature, it's just not described) and they NEED the RHOD's, than it won't be pretty.

I was thinking of keeping the loyalty implant about, that way security still has the ability to slowly convert their way through like current Revolution. But now there exists another High risk high reward method, which is to investigate and locate the RHOD, which would simplify their lives.

Playing about with the conversion time could be an interesting game mechanic. So something like:
- Base brainwash/time for implant effect is 15 seconds (Loyalty implants take the same amount of time to inject, but requires a longer time to take effect akin to holy water and cult).
- Revolutionaries exile HOD, fueling revolutionary ideas - Brainwash time for department personnel reduced to 10 seconds, time for implant effect increased to 30 seconds.
- Revolutionaries kill HOD, disillusioned with the bloody turn of events - Brainwash time for department personnel increased to 30 seconds, time for implant effect reduced to 10 seconds.

With this, we will probably have to keep the idea of Head Revolutionaries as starting revolutionaries. Maybe we can then introduce ShadowDeath's idea as the following mechanic for loyalists:
- Head Revolutionary exiled (Assuming 3 Head Revs at start), Revolutionaries begin to question the need for a Revolution as Nanotrasen is peace loving: 25% chance to deconvert each revolutionary with no more than 1/3 of current number of revolutionaries being deconverted.
- Head Revolutionary killed, instigating further uproar amongst the mob: Permanent increase in 5 seconds of time for implant effect.

The permanent increase could be painful for security, who would then turn to exiling if they believe they can successfully prevent the mob from breaking the Head Revolutionary out of exile. Numbers subjected to balancing. The time for implant effect will also eat into their manpower as they need to station a guard about to ensure they do not escape, as well as potentially not being able to storm a department and begin implanting immediately.

Cheers all!

**Comment by ghost** [comment]
the thing with sec locking down the department won't happen because sec is fucking retarded and engineers can't be locked down because they're all farting around in space in their hardsuits with RCDs

you kill a guy halfway across the station and suddenly the scientist holding a valve bomb next to the HoP is instantly a rev

it'd be no different than regular rev except for stationwide conversions because sec won't bother to nonlethally detain 12 angry engineers, they'll do the same shit they do with regular engineers and beat them all to death or lock them all for implantation as usual except there's an RNG chance where they realize one guy's the revhead and they space him instantly deconverting all revs on the station

also it takes 1 minute to remove a set of handcuffs so if it takes 30 seconds for implants to work you can just stuncuff implant and then they deconvert p soon anyway

not much changed there, it's just a needless delay that changes nothing, on both the sides of revs and sec

**Comment by ParagonPrime** [comment]
okay, let's fucking increase the times then

20 seconds low, 45 seconds normal, 80 sec high for rev; 10 seconds low, 30 seconds normal, 60 seconds high for sec because their deconversion process isn't free unlike revs

that way, if you fuck up and kill a HOD/RHOD/revhead, better have a buddy nearby when converting, because they'll break free before you finish otherwise (and you have to remain still)

let's remove the % chance to autoconvert/deconvert completely, then- all that exiling vs killing does is allow spread of revs at MUCH higher momentum

also, in a scenario where someone's conversion time is raised to 90 and implant time lowered to 10 by the death of a head, if sec then kills the RHOD, your time balances out again because "both sides are equally evil"

Also- revheads should be able to select RHODs and promote new revheads much like gang bosses with lieutenants in gang. When an HOD dies/is exiled, the revhead is prompted to select a new RHOD within a certain time frame, or a random person in the department is given the role. If a revhead dies, the remaining revheads can select a new one that's been a rev for a certain amount of time already. There can only be 3 revheads at a given time.

Finally- return from exile. This is tricky, but has a few solutions-
1. Provide revheads with on-demand exile implant
2. If a head returns from exile, there's no penalty for killing them (though admins should boink anyone who 'exiles' someone then immediately returns them to the station to kill them penalty-free)
3. Any head (station or rev) returning from exile "inspires" all members of their faction, including those not in the department, increasing and decreasing appropriate convert/deconvert time by five seconds. Bonus applies only once per head. This option encourages people to actually guard the heads when they're exiled, which can create _gasp_ RP
