### ISSUE TITLE
Code Red Locker

### ISSUE THREAD

**Issue by Groudonmaster** [yogstation13/yogstation-classic#802]
### Expected Behaviour

Security to have better gear but it's locked up unless heads approve Code Red
### Actual Behaviour

Stuck with normal riot gear
### Steps to reproduce the problem
1. U
2. Wot
3. M8

Anyways I suggest adding a locker that only unlocks upon code red declaration to the armory.

This would actually make things like #800 viable and not overpowered as it requires two heads (or admin) to declare red before ANYONE can access it. The locker wouldn't be emaggable or anything it is literally locked period without station wide emergency.

We could also throw in a few more loyalty implants just in case shit gets even worse during a rev round or #532 could be a thing.

**Comment by ghost** [comment]
> emag proof snowflake lokers

no

**Comment by Groudonmaster** [comment]
Be useful if you're going to be insulting Adam

**Comment by DavidEdwards** [comment]
I think it would be useful for additional loyalty implants. An emergency locker. Edit: Emag could perma lock them. Making them unusable in an emergency.

**Comment by ShadowDeath6** [comment]
What kind of gear do you want in it? The stuff in the referenced issue is probably only good for autismal stunprod spamming (rev) and not good for literally any other mode. Same with loyalty implants.

**Comment by ToGWtF** [comment]
I believe someone already made sprites for an upgraded riot shield that has a built in AOE flash. Would be great crowd control on rev

**Comment by Groudonmaster** [comment]
The things that would go in it would be what people have insofar deemed overpowered if available at roundstart or normally locked in the armoury. Let's throw some real shotguns in it instead of the riots, let's throw additional abalative's or even another ion rifle or emp grenades, something that would help in the late round on game modes such as malf, rev, or cult.

**Comment by DavidEdwards** [comment]
We could actually randomize the contents. Have a list of things that it can be, and choose a random 10 items from it.

**Comment by Groudonmaster** [comment]
Or have it spawn game mode specific items maybe?

**Comment by ParagonPrime** [comment]
> mode specific items
> inb4 declare code red just to open locker
> find a bunch of bulletproof armor
> basically, station declares war without the nukies ever getting the extra TC

yeah, no, that's silly.

randomizing sounds interesting, but has to be carefully balanced.

**Comment by Groudonmaster** [comment]
You know what stops them from doing that? 1, the new whitelisting stops incompetents from always doing that because regulars realize that's fucking retarded, 2. That is blatant powergame and people realize it. 3. I will shit on people who abuse this.

**Comment by ghost** [comment]
It'll still be abused anyway. Heads will go code red for some bullshit reason like the captain got his cock stuck in the door, warden will walk into the armory, open the locker, close the locker, and lock it, and know it's definitely lings.

Powergame or not you can't catch that every time.

Also, before you go around saying 'be useful instead of insulting' come up with a decent idea, first. Otherwise i'm going to treat it like trash.

So you're advising giving the armory, already full of lethal weapons and gear, a snowflake locker that's unemaggable full of powerful gear? What's to stop the warden from welderbombing it open or something? 

And why does sec need it?

The armory has potent as shit guns. Riot shotguns are incredibly powerful and come loaded with rubber shot, not even beanbags, rubber shot, and you can fill them up with anything else you want. They work as 4 shot combat shotguns instead of 6 shot. They have lasers, riot gear, bulletproof armor, ect.

Giving sec a snowflake locker for code red is just unnecessary, especially if it's unemaggable for no good reason. If nanotrasen can make the locker unemaggable, why not make all doors and lockers unemaggable, including the Captain? It doesn't make logical sense, nor does it make sense to punish a traitor for breaking into the armory and emagging a locker only to get fucked over, nor lock it behind going code red, which requires 2 simultaneous ID swipes-meaning a traitor can never do it.

The shit in that issue for insulated stuff is just obnoxious, too-Fully stun resistant body covering suits means that security will have the advantage in nearly all situations. Armed with a tazer, they'd be basically unstoppable without resorting to telebatons and such.

So boo to the snowflake emag locker, and boo to you for whining that every time someone disagrees with you they're being insulting. NOW i'm being insulting.

You want to give sec some snowflake gear? No EMP grenades, those are too powerful for standard security use. Borgs and AI would get cucked every time. No combat shotguns either, and no special snowflake roundtype gear.

Give them a locked locker of lethal and incendiary shotgun shells in the armory that requires HoS access to open rather than magically code red whew lad instant open emag proof. Like every other locker in t he game.

So that security can load up riot shotguns with lethal stuff.

And security DOES get better gear when the armory is opened. If you think it's not good enough, explain why-riot gear makes you nearly immune to melee-but not stunprods, which  needs to be fixed as that's a bug on riot shield's part-and bulletproof armor is potent as fuck versus bullets.

If you really want, add more ablative armor to the armory if you think there isn't enough, or add the reactive teleport armor there instead of on the RD. But that's all the buffs i'd agree to-Sec doesn't need much of a buff at all, and special snowflake emag proof lockers are obnoxious mechanically and from an in game standpoint, especially if it's loaded with overpowered gear that's roundtype specific so the warden can metaknow the roundtype without admins being able to tell unless he goes full retard and shouts 'THERES BULLETPROOF SHIT IN THE LOCKER ITS OPS'

**Comment by LesVegetables** [comment]
I am still of the opinion that sec only seems weak because most sec players are woefully inept, it does not matter how much you buff sec gear if the people are too stupid to use it the antags will eat it up anyways

**Comment by EMT321** [comment]
The biggest issue is a lack of coordination. Although shields blocking stunprods would be very nice, as right now there is little you can do against a methed-up assistant with a stunprod, regardless of what you have.
