### ISSUE TITLE
Make floodlights only emit light when wrenched to floor instead of dragcheese huge aoe lights

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#861]
Floodlights are an awesome counter to shadowlings that were sorely needed.

But dragging them around with no repricussions as a moving 'fuck off shadowlings' field is less so.

Just make them only emit light when wrenched down so you set them up to light ul areas instead of massive unveilable flashlights for cheap.

**Comment by ShadowDeath6** [comment]
Then make it so that they're a lot harder to take apart since all you need to do is touch it once as shadowling and you're free to be totally balanced until the people recover from stun.

**Comment by EMT321** [comment]
Shadowlings had an absurd (At least 75%, if not higher) winrate. Lets let this go for a while, examine the rate, and move forward rather then succumbing to kneejerk reactions. Its nice to finally have a semblance of an effective weapon, rather then being gazed by thralls as sec or having no chance outside of a 3v1 vs a sling. Besides, there already exists counters:
1. Stop cargo, either by fucking APC's, thralling anyone with cargo access to send the shuttle back immediately/waste points, or just breaking the consoles. I've only seen 3 occasions where someone other then myself ordered lights and made effective use of them. I've seen far more where cargo didn't figure it out, or they were brought low by thralls/slings. Given how likely cargo techs are to be in maint, this isnt a particularly hard task. This makes cargo a point of contention
2. Wear a hardsuit. I believe this still stops burn damage.
3. Simply turn em off. Most slings make the mistake of running away, rather then gazing + walking over a body to shut the thing off for good. It takes a good deal of time to kill a sling with floodlights: if they play agressively, they will still be limited to one person at a time, but by no means does it spell a death sentance.

I'm tired of being fucked over by slings regardless of carrying  torches and god knows how many lights, plus an armory and half of sec behind me. Do you really want a return to the meta of  Red-alert+break consoles+Kill all thralls+Early launch? Because removing credible defenses against slings will do just that.

**Comment by doerakpoes** [comment]
Actaul flood ligths are movable if i remember correctly
As in they dont need to be attached too the floor

**Comment by ToGWtF** [comment]
Moveable sure, but they are moved by hooking them to the back of a truck

**Comment by doerakpoes** [comment]
What if the people of SS13 are all just strong peeps

And then still they are activated when not really hooked too a power source other then a battery i think

**Comment by doerakpoes** [comment]
And then still they are actavated when not really hooked too a power source other then a battery i think

**Comment by ParagonPrime** [comment]
Maybe vary the brightness?

Like, you could either have a powerful stationary light that's wired into the station's power (and doesn't use its battery charge), or a weaker (stronker than flashlights but weaker than stationary floodlights) floodlight you can SLOWLY drag around and drain battery rapidly

**Comment by doerakpoes** [comment]
That seems like the best of both worlds

**Comment by EMT321** [comment]
There is currently another PR up where people are complaining about shadowling winrate. According to Adam, who I'll assume is not being superfluous, they have a 90% winrate. Why further nerf the one credible defense the station has, so that maybe they can win greater then 1/10 times?

And as far as realism goes, we have man-portable floodlights with a stupid high lumen output IRL. We use them on our rescue squad, and they can either run off a dedicated current or an attached gasoline generator.

**Comment by Super3222** [comment]
Adam, I had the same exact idea that I was telling the admins online. However, they didn't listen.

My thinking was that floodlights are meant to protect specific areas and emit a strong amount of light so shadowlings AVOID those areas.

**Comment by EMT321** [comment]
Yesterday I was informed that shadowling 'only' had a 60% winrate now, since the addition of floodlights. We are seeing issues where none exist.
