### ISSUE TITLE
Blast doors to Tesla/Singulo airlocks

### ISSUE THREAD

**Issue by ToGWtF** [yogstation13/yogstation-classic#867]
### Expected Behaviour

Set up Goofball correctly, not die.
### Actual Behaviour

Goof EMP's a door open, shocks you like you just stuck your dick in a light socket

**Comment by EMT321** [comment]
Please fix this. I've died many times to a correctly set up tesla that chains up and kills anyone near engineering.

**Comment by ShadowDeath6** [comment]
remove the memeball >:^(

**Comment by Super3222** [comment]
If the button was in the CE's office, that'd be great.

**Comment by ToGWtF** [comment]
fuck what am i thinking, the blastdoors just get deleted as well

**Comment by FluffySurvivor** [comment]
That is the funniest antag thing to do. 

Btw, just wall off the right entrance, and the tesla will stop leaking.

**Comment by X-TheDark** [comment]
I'm voting against implementing this. No power generation option should be "fire and forget" just because "you set it up properly". There should always be inherent danger to it. Grounding rods are used to MINIMIZE these damages, but not eliminate them completely. Unless you are being hit by a tesla bolt in the middle of Engineering (rather than near the South glass window) - then it's a problem.

**Comment by FluffySurvivor** [comment]
It's not a bug. 

It occurs only with double teslas (or more) and you are supposed to wall the entrance.

**Comment by ShadowDeath6** [comment]
It occurs with one tesla as well actually
