### ISSUE TITLE
Blob

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#888]
### Expected Behaviour

It's fun
### Actual Behaviour

It's not
### Steps to reproduce the problem

Unanimous vote is that it grows too fast and it's basically unwinnable.

Proposed solution-

x2 blob win requirement, so one blob has 700 tiles to cover, not 350

Lower blob growth speed back to pre-buff

Remove delay between 'classified announcement' and 'LOL BIOHAZARD' to just display the biohazard alert when it pops.

Remove blob shunting abilities.

**Comment by ShadowDeath6** [comment]
I can increase req to win, but that's about it.

**Comment by MacHac** [comment]
Personally, I think that the blob should have significantly longer to operate as a human before bursting.  It's hard to play saboteur when the upper cap on your time is 8 minutes, and you're almost certainly not starting as an engineer.  Blob bursting should be a semi-accurate countdown, as long as 20 minutes if you're lucky.  To balance this fact, increase the amount to win requirements as adam mentioned.

Really, the biggest problem I see with blobs right now are nodes.  Nodes regenerate far too quickly.  If you release plasma into a node's entire area and light it up, it will regenerate faster than the plasma burns.  Additionally, nodes act as an effectively impenetrable wall until xray lasers are made, because even three or four crew working together with welders can only barely reach a node, and that's without any spores in the picture.  Node effectiveness should be dropped to about two thirds of what it currently is, so the crew can kill them (with effort) even if mining spends the entire round in the bar as usual.

**Comment by ToGWtF** [comment]
blob shunting is necessary

the 5 minute delay for announcement on popping gives you enough time to put your first node down and not get your core rushed by the clown

maybe re-nerf blob growth

definatly increase blob win requirement. 700 might be too much. getting to that point means blob basically has infinate chems anyway

**Comment by ShadowDeath6** [comment]
> force people to play as human longer

I think people like blob because the actual blob antag, although giving them an option to burst when they want could be helpful.

**Comment by oisin100** [comment]
> x2 blob win requirement, so one blob has 700 tiles to cover, not 350

I would personally love this. Its so annoying getting to the point where your actually having fun and then once you get to that point you get "You win" no more fun for blob.

> Lower blob growth speed back to pre-buff

Yep, 100%. Blob wins way too quickly and doesent give the crew long enough to fight back.

> Remove blob shunting abilities.

Not quite sure why this even exists. If you cant defend your core then your probably gonna loose anyway, no point drawing it out for everyone else.

**Comment by ghost** [comment]
we're nerfing blob not buffing it

**Comment by apneaman** [comment]
I love blob rounds but yeah i hate the speed of growth. I remember placing an emitter about 14 tiles away the second i fired it up it was ontop of me in about 15 seconds. And usually the crew is just getting a defensive line set up and its already 2/3rds to victory
