### ISSUE TITLE
Remove cult

### ISSUE THREAD

**Issue by FluffySurvivor** [yogstation13/yogstation-classic#900]
### Expected Behaviour

cult does not exist
### Actual Behaviour

this shit that gives me braindamage actually does exist
### Steps to reproduce the problem
1. pronounce "cult"
2. pass out irl

**Comment by apneaman** [comment]
I actually really like cult when its done right (taking time to set up multiple hidden bases , actually using the offensive/defensive runes) you know having an actual war with sec
Same problem as rev though it either fails due to lack of communication and teamwork or turns into a speedy flurry of stunprods

**Comment by Kmc2000** [comment]
God yes

Replace it with COC; zombies

**Comment by ghost** [comment]
I have never once seen offensive/defensive runes being used in cult or bases being built in all the time i've spent on yogs. Not once.

I have seen in all my time playing only two times teleport manifest ghost runes were ever used by someone not me.

Cult literally only needs the convert and sac runes to win, and sometimes summon narsie. Cult also has no scaling-you have enough cultists to summon narsie at shift start, and all their magic is woefully overpowered, balanced only by the fact that all the cultists are too retarded to use anything aside from swords on the chaplain.

There is a rune that fucking crits anyone in eye radius fighting you instantly, the ability ro instantly remove and free captured cultists to sec, the ability to make infinite cultists no matter how few they are by manifest ghost or saccing dead bodies, and instant, unresistable stun papers that also mute + a metashield that lets them run around with a tome in public and draw runes in public.

And they still lose because it's a shitty gamemode. Kill it.

**Comment by ShadowDeath6** [comment]
Blood boil has a 5% chance to completely gib people too :^)

**Comment by oisin100** [comment]
We could port /TG/'s cult, Almost another gamemode really.

**Comment by ShadowDeath6** [comment]
> port tg's cult

no

**Comment by ParagonPrime** [comment]
remove cult, put cybermen and zombies properly into rotation

yes

**Comment by Cruix** [comment]
No.

**Comment by TheSadFox** [comment]
B-but cult is fun.

**Comment by ghost** [comment]
No it is not

**Comment by TheSadFox** [comment]
> No it is not

Thats like, your opinion man.

**Comment by Kmc2000** [comment]
I pronounced cult and passed out, as fluffy said

Its a horrible game mode..... 

Imo

**Comment by ShadowDeath6** [comment]
Cult is fun if you play it like a shitler. (I.E murderbonering everyone, saccing them and making a construct army) The main reason cult is bad is because players are literally retarded and don't understand what the big red circle means and want to run away from it.

**Comment by FluffySurvivor** [comment]
no

it's not only that. 

Holy shit it would be actually decent if it were only that. 

Every cult mechanic was exploited to shit (like current ez word research vs SACCING FOR WORDS LIKE IT WAS MEANT TO BE). 

You don't need the billion runes (important: that are ALSO OP AF) because you can just ez stomp sec OR rush your sac target and do cancersie 3 mins in. 90% of the time you spawn with enough cultists to either narsie/escape. Round end conditions are also flawed, you have to wait 7 minutes as a ghost without wall passing or deadchat when the big red tentacle monster is spawned. Not to mention troll recalling then that extends waiting by 10+ mins. 

Moving on, every cultist has that ultra risk-free and ez stunpaper that's more powerful than a sling glare. Iirc there is also a rune that lets you spam stunpapers. 

Deconversion is a joke. The guy that has the only deconversion mean is either killed 2 mins in or goes afk. Of course, deconversion has to take 3 minutes cause fuck you balance. Another cultist uses the port rune and hits you once with his cultbook and bam, you're good to go! 

Metashields. A horrible and unreliable way to balance something on a low rp sever. Cult has them. 

I don't want to even start talking about the competence of people.... 

Cult is a gamemode with an okay concept but with an horrible, absolutely horrible execution. You don't feel special at all when you roll this antag. You can't go "hey i will do something different this cult round", because everything is so metatized there is no point. 

K I L L I T

**Comment by ShadowDeath6** [comment]
"Oh hey I'm rev time to do something different this round"
"Oh hey I'm gang time to do something different this round"
"Oh hey I'm (group antag with set objectives) time to do something different this round"

At least cult is different than le meemee curbstomp bodyspam or hide and seek with a big metal box. I personally enjoy it and outside the autism of people not being able to stand around a circle it's a fun mode.

**Comment by FluffySurvivor** [comment]
> le cherrypick

@ShadowDeath6 pls go away with your cult meme. If you want cult go play it on your local server :^^^)
