### ISSUE TITLE
(Code) Testers

### ISSUE THREAD

**Issue by ghost** [yogstation13/yogstation-classic#904]
### Expected Behaviour

Designated testers will test a coder's code and find errors or problems in functionality.
### Actual Behaviour

Coders have to waste time and test their own code and they may not find all code problems.
### Steps to reproduce the problem
1. Apply for coder.
2. Get accepted for coder.
3. Code.
4. Try to test.
5. Get frustrated at time wasted and inability to test well.
6. Make issue like this.

**Comment by ghost** [comment]
Ideas for how this would work should be in the comments, please.

**Comment by MacHac** [comment]
Testers?  We already have those.  They're called the players, dummy.

**Comment by Super3222** [comment]
Players are the testers.

If you want to invite them onto your private server to test new things, you always can.

**Comment by faultlesselm16** [comment]
yes we players are your lab rats

**Comment by X-TheDark** [comment]
This is not feasible, for very simple reasons.
1. Issues/Bugs - fine, these could be tested by someone, if we keep up with the **Intented Behavior** and **Steps to reproduce** accurately.
2. New stuff - just no. The coder who codes in the new stuff is (or at least should be, since he's the one making it) in the best position to test it, as this person knows exactly (or at least should understand approximately) what the new stuff uses/affects (barring unforeseen interactions, aka bugs). A coder cannot test every possible interaction, but I think he can make sure the basic functionality works (such as adding a new item that spawns/works in hand/doesn't crash the mob it is supposed to be used on (implants, for example), etc).
