### ISSUE TITLE
Horror Form, holy dicks

### ISSUE THREAD

**Issue by ShadowDeath6** [yogstation13/yogstation-classic#907]
I'm trying to code horror form, basically "hyper murderboner / panic button" for changelings. This issue is for balance or whatever since the only input I've gotten so far is from coder chat and a select few players on the server.

Abilities-
Fleshmend
Screech (AoE Stun)
Ridiculous melee damage (3-4 hit crit on unarmored) and guaranteed weaken per hit
Unstunnable
Can break windows, tables, and walls
Extremely tanky (armor values still being debated since I haven't gotten that far)
Automatic night and thermal vision
Devour, a faster absorb which completely destroys the victim's body and leaves nothing but remains
Immune to space

Weaknesses-
Thermal vision makes it vulnerable to blinding by flashes, although not stunning
Drains a ling's chemicals EXTREMELY quickly, it can only hold this form for a short time.
If a horror form'd ling takes too much damage they collapse and go unconscious similar to crit
Even if the ling reverts safely they're still stunned and vulnerable
Can't fire guns (obviously)
Weak to fire (atmospheric, like flamethrowers)
Upon transforming its shriek is as loud as a tesla bolt, so most of the station will know there's a ling.
**REALLY FUCKING SLOW**
Can't use any other changeling abilities

Fighting this thing one on one is basically a death sentence, but it's rather slow so you can run away from it, granted you don't stick around to let it stun you.

reminder- I haven't done a lot of this just yet, so don't expect this to be in the very near future

**Comment by oisin100** [comment]
> Even if the ling reverts safely they're still stunned and vulnerable

So, If they run out of chems will they get stunned?

I'm kinda liking this idea.... Right now changeling seems a bit... Weak... The only lethal they have is armblade pretty much.

But i dont think they should be able to break walls or devour people.

**Comment by ShadowDeath6** [comment]
Running out of chems will revert them. Not sure if it should be like taking too much damage or counting as safely reverting.

**Comment by oisin100** [comment]
It should be counted as taking too much damage.  I assume you re-gain consciousness right?

**Comment by ShadowDeath6** [comment]
KO will probably be for ~30 seconds.

**Comment by ToGWtF** [comment]
You should get more chems for each body you devour to keep your horror form stable

**Comment by ParagonPrime** [comment]
Make sure you can stay in horror form for at LEAST a minute (plus- devouring giving more chems). And it shouldn't be slower than, say, an Adamantine Golem.

**Comment by ghost** [comment]
It will be slower than thirty minutes and last for less than a minute, so that lings can't abuse this to kill all of sec within minutes.

It's sort of a last ditch thing-you're caught, sec is coming, someone's toolboxing you, serviceborg is beating you with a tray-go horror form and hope for the best in killing your attackers and getting away. Devouring should only increase chems by 5-8 chems, depending how many chemicals are drained per tick-hopefully 5-8-so that devouring will give you a second or two longer in horror form, not enough to last long enough to kill all of sec.

**Comment by ghost** [comment]
Er, slower than an adamantine golem. Not sure why i said 30 minutes there.

**Comment by Super3222** [comment]
This is nice, and well balanced.

My only thoughts are..
What happens when the ling dies in this form?
What happens when this form runs out?
Would this be a evolutionary ability where you have to pay points to gain it or will it come naturally?
Will the screaming heads and faces from the horror form whisper creepy stuff, or maybe whisper creepily the last words of the people you've absorbed?

**Comment by ghost** [comment]
Ling drops into red health, they revert and are put to sleep for 30 seconds, shadow said.

natural-this is a ling's 'true form' after all.

If the heads on the horror form whisper the victim's last words people are going to deathwhisper wgw just to get a ling to transform and watch a shambling abomination charge the hos as a thousand voices whisper about woody getting wood.

**Comment by hawkname** [comment]
Maybe make the voices of whoever was devoured say generic things at random, like groaning in agony or screaming or begging for help. Could really mess with whoever's trying to fight the horror when they know they might just join them. Doesn't let horror forms be all stealthy as well since you have a screaming machine attached to your body and reinforces the idea that it is fully for loud and panic purposes.

A minimum number of genomes before being able to become horror form can be introduced so lings don't just go horror form at every single opportunity. It will cost them genomes that they would need to reacquire to get that green text.

**Comment by ghost** [comment]
It would have to require absorptions, not dna stings, so lings can't cheese sting everything, horror form in the middle of sec and scream and wail and beat up all the officers with their other ling buddies also going horror form.

**Comment by ShadowDeath6** [comment]
I'm not sure how to make it ONLY accept absorptions, I was just thinking of making it need 10 people, which if you don't absorb is 250 chemicals, which takes a long time to get.

**Comment by oisin100** [comment]
> Will the screaming heads and faces from the horror form whisper creepy stuff, or maybe whisper creepily the last words of the people you've absorbed?

Nice to see theres another doctor who fan here....
It would be a interesting mechanic...  But i think as Hawkname said, horror form is for going loud. Absorbed people should be able to whisper for some time. Maybe only for a couple of minutes until you fully digest them.

**Comment by ParagonPrime** [comment]
Wait- if horror form is ling's true form, why the fuck would it drain chems so quickly

that makes zero fucking sense

**Comment by ghost** [comment]
Because balance reasons

**Comment by ghost** [comment]
If the ling goes horror form, all your absorbed victim's last words before being absorbed-the same way lings get last memories-are repeated endlessly.

**Comment by ParagonPrime** [comment]
Small thing, but needs to be mentioned:

Make sure that horror form drops all equipped gear shadowling-hatch style, and that you can't recognize who the horror form actually represents (because how the fuck would you identify a horrific fleshy mess as George Melons?)

**Comment by ghost** [comment]
i'm picturing some shambling, spider legged, fleshy screaming abomination

and on it's chest

there's a tiny plastic tag

'Hello! My name is George Melons!' written on it

**Comment by ShadowDeath6** [comment]
I return from the void

Anyway, I have the actual horrorform transformation complete, renaming and abilities and armor and all that. Make sure to comment on what you think stats like stuntines should be.

**Comment by oisin100** [comment]
30 seconds sounds like a good stuntime for the overused horror form.
I think add 10-15 seconds stun time after a normal revert since youre bound to be exhausted after turning into a big massive unstoppable killing machine.
