### ISSUE TITLE
Deep-pressure Suit

### ISSUE THREAD

**Issue by ParagonPrime** [yogstation13/yogstation-classic#908]
Adds a single hardsuit to Secure Storage: the Deep-Pressure Suit.

The DPS is a slightly niche hardsuit with some interesting properties...

+Heavily reduces brute damage and is basically immune to burn damage
+Totally immune to pressure and heat
+-Takes much longer to be pulled off than a regular hardsuit (good if being looted, bad if being healed)
-Slows you. A LOT. I mean, a LOT.
-Increases stun times by 200%
-Disallows use of guns (bulky fingers, man)

So it's basically meant to be niche, useful for everything from handling a tator atmos tech who was smart and released ultra-high-pressure plasma, or for playing tank and storming wherever needs to be stormed. Doesn't make it a guaranteed-win-against-malf though, because the stun times will be absolutely ridiculous.

**Comment by AsV9** [comment]
I'd be open to code this but I'd need some sprites.

**Comment by ToGWtF** [comment]
Basically a bombsuit-hardsuit?

**Comment by Kmc2000** [comment]
Hey, this power armour

I like power armor

Also i did make an alternate space suit sprite a while back, if you want that aSv

**Comment by ToGWtF** [comment]
I was going to say, maybe make it a kind of mech. That way, it has a delay for putting it on and can balance out its huge brute resist for having battery life and being breakable. That way, we don't just have the captain suit up at roundstart

**Comment by ParagonPrime** [comment]
Yes, bombsuit hardsuit. Precisely. It's just meant to be used in emergency situations where shit is REALLY hitting the fan. As for how it looks- it should be less bulky than a mech but bulkier than a regular hardsuit. Maybe something like [this](http://pre12.deviantart.net/2a02/th/pre/i/2013/045/2/2/_golem__hardsuit__sketch_by_tekka_croe-d5uyu7u.jpg) or [this](http://vignette1.wikia.nocookie.net/blacklighttangodown/images/b/b8/BLR_Hardsuit_White.jpg/revision/latest?cb=20130313083807). For some reason, I envision it in some murky brown colour scheme, but see what you find cool.

Can't be a mech- the person still needs to be able to interact with things (except guns), be stunnable, etc.

Captain suiting up at roundstart is just asking for him to be murdered- 200% stun increase! PLENTY enough time to put on cuffs and drag him into maint, though getting his headset off will be trickier.

ALSO, there should be a Combat Deep-Pressure Suit- utilized by NanoTrasen, presumably by the ERT (but maybe also as a really high-end RnD thing?). Heavier armoured and marginally faster; while you still can't use regular guns, you CAN attach mech weapons to them; if the right hand has a weapon in it, it becomes unusable as a hand, and vice versa.

**Comment by ToGWtF** [comment]
+1 for the fucking project blackout mech. was a good game

**Comment by ghost** [comment]
So it makes you unkillable but slow moving?

This is dumb-there's no reason to have this, and it's gonna be near impossible to kill for blobs if someone's wearing the suit, and god forbid a changeling gets ahold of it, since they have the ability to move at normal movespeed in any clothing that slows you down and stun resist abilities.

Or if a hulk wears it. Hulk + tk + this is basically completely unkillable.

And even if not wearing that, you won't be able to kill the wearer, even by stripping off the hardsuit, because stripping it off would take an obscenely long time.

This just really is not good for station crew to have, esp if a ling or traitor or god forbid a cultist gets their hand on it, not to mention all non-toxin blobs are gonna get shit on by that suit.

And malfs, ect-why are we adding another fireproof hardsuit?

Tbh, this is red alert ERT gear/deathsquad gear as it stands-probably only deathsquad.

**Comment by ghost** [comment]
It will be a guaranteed win vs malf- if wearing the hardsuit chances are ai can't laser them to death or turrets will just waste time doing nothing vs that guy, or if only on stun, he can pop some crank, bath salts, or meth and negate the stun duration.

Yeah, that's something else to consider-bath salts, stimulants, both make you basically immune to stuns, so the n1 ''weakness'' of the hardsuit is negated-stuns are easily avoided by a traitor wearing it while wearing a stimpak, or literally anyone making bath salts.

Bath salts are a complex recipie, so it'd be less worrying than say, crank, meth, or epedephrine, which would 100% reduce stun times to normal, and in crank's case make you recover 100% faster from stuns since the hardsuit wouldn't nullify it, and meth grants a giant speedboost, so.

**Comment by ghost** [comment]
Again, this is more red alert ERT commander gear, or deathsquad leader gear, than anything else as is.

**Comment by ParagonPrime** [comment]
Then let's just implement it as ERT gear. Or high, high-end researchable from RnD- not roundstart.

**Comment by Super3222** [comment]
ERT garage system when?

**Comment by ghost** [comment]
Stop adding overpowered gear and then saying 'lol lets hav r&d heff it xxxxxd'

R&D is obnoxiously powerful and incredibly easy to get. All the 'late game' gear can be gotten in fifteen minutes give or take competent miners, and it just makes it even worse because then toxins can suicide bomb without fucking dying. 

R&D is an overpowered department and a bad system altogether that needs a rework-no, it is not 'fine as is xxxxxd'-and adding this overpowered piece of shit would make it completely unbalanced along the lines of foam dart diamonds.

Deathsquad or red alert ERT gear for the commander and the commander ONLY.
