### ISSUE TITLE
Nerf cabbages

### ISSUE THREAD

**Issue by Kmc2000** [yogstation13/yogstation-classic#964]
### Expected Behaviour

Cabbages aren't OP
### Actual Behaviour

They are
### ho 2 fix

Impliment alblaka's edible cabbages idea
Impliment tog's wirecutter pruning (prune cabbages for 20 damage)
Add ability to rip off leaves from cabbages with agressive grab

Really just to get attention onto those neat ideas, plant nerds have leaves, yet you can't murder them by depriving them of them.

**Comment by FluffySurvivor** [comment]
why are they op
???

**Comment by Time-Green** [comment]
You're in my naughty list, kmc

**Comment by AsV9** [comment]
> Actual Behaviour
> They are

Explain please.

**Comment by ParagonPrime** [comment]
cabbages are NOT OP- especially as antags

the only 'op' thing about them is the fact that they can potentially skimp on insulo gloves while hacking (unless engi has wired into the grid...) since they'll just regen the health soon anyway

tator? got phytosian assassination target? don't even need a fucking esword, use a welder- they're exactly the same in terms of damage
same goes for lasers

phytosians aren't OP at all
at
all

**Comment by Groudonmaster** [comment]
Yeah I'm not seeing the OPness of them

**Comment by Super3222** [comment]
Cabbages are not OP.

I highly disagree with this, their weakness to darkness / small light in an area is a well thought out balance towards the race.

The ideas to even nerf them are... uh...

**Comment by MasterPenguin5** [comment]
> Impliment tog's wirecutter pruning (prune cabbages for 20 damage)

Welders already do as much damage as eswords to cabbages, and you can lock a cabbage in a locker and kill it in under 5 minutes. We definitely need another way to brutally murder cabbage people.

> Add ability to rip off leaves from cabbages with agressive grab

Because beating them is so hard? Also wouldn't the leaves just grow back, just like any other form of damage?

> Impliment alblaka's edible cabbages idea

What.

**Comment by ghost** [comment]
The issue with phytosians is that their slow heal-While extremely slow-is still infinitely favorable to playing as a regular, boring human, especially considering not many people exploit the high-damage-burn-shit on phytosians.

Phytosians need more severe downsides and upsides, in all honesty, to encourage people playing different races aside from cabbages.

Here are a list of proposed changes:

The burn damage is not currently a flat 2x. Make it as such, so that a welder will deal 30 rather than 15, a laser will deal 40 rather than 32, et cetera.

Make phytosians heal from certain gardening chems. The specifics-

Saltpetre heals 2.5 burn and 1 tox per tick.

Ammonia heals 1 burn and 1 brute per tick.

Robust Harvest heals 2 tox per tick, but slows down the metabolization of harmful chemicals in the body.

Left 4 Zed functions like a weak unstable mutagen-Causing a low chance of random (usually harmful) mutations, healing 1 burn, and causing one tox per tick.

E-Z Nutrient heals 1 tox and 4 oxy per tick, and stabilizes at -50 health, preventing any further oxygen loss. It is also addictive in quantities higher than 15u and withdrawal adds 2 oxy and +.5 losebreath a tick.

Plant-B-Gone (Weedkiller) causes 3 toxin and +.5 losebreath per tick, in addition to causing confusion (a la cryptobolin.)

Diethylamine- Heals .5 burn, .5 brute, and 2 toxin and 2 oxy per tick, in addition to curing hallucinations like synaptizine. OD's at 20u and causes rapid toxin and brain damage. 

Ethanol (or any alchohol drink) -Causes 2 brain damage and .4 toxin damage a tick, in addition to confusion. Alchohol is not good for plants! Ingesting more than 30u of any drink with a strength stronger than 2 (second highest) or pure ethanol causes heavy toxin damage and knocks you out in 50 cycles.

Sugar-Increases the healing rate of phytosians as long as it is in the body to twice it's normal strength, but phytosians have lower tolerance for sugar and enter hyperglaucomic shock (which already exists in game, sugar comas are fucking nasty) in quantities above 40u. In addition, you also take much more toxin damage in darkness.

The floral somatoray:

The floral somatoray is an R&D counter to rampaging phytosians in much the same way the tempgun is to slimes. The yield setting does nothing to phytosians-The 'Mutate' setting functions exactly like a decloner, but weaker.

Being flashed as a phytosian heals 5 clone, 5 burn, 5 brute, 5 toxin, 5 oxy, per flash. Yes, this does mean you can flash a phytosian to heal them-it's more a gimmick than anything, as flashes burn out and there's a cooldown to it, it'd be much faster just to use med chems.

Acids have 2x their normal power versus phytosians- Just double the acidpower on phytosians. 

Phytosians will not  heal at all at temperatures lower than 150K or higher than 400K-from ANYTHING. So no, you can't use cryo to heal phytosians-they just end up in a stasis. Don't worry about being in an eternal cryostasis-Add a 'resist' verb to cryo so you can kick your way out in 2 minutes just in case.

Phytosians are JUST slightly slower than a human-they won't catch up to a running human if they're both running in the same direction at the same time with no impedements in either way. JUST slightly slower-they won't be as absurdly slow as golems or queens or whatever-just enough that they're 1-2 tiles behind.

**Comment by ShadowDeath6** [comment]
> be wizard cabbage
> knocked into crit by a claymore but teleport right before
> heal from crit and continue to kill everyone

Why the fuck do they get innate automatic healing it's so retarded
They were fine when nutriment and vitamin were non ODing omnizine

**Comment by Kmc2000** [comment]
Thing is, as a frequent cabbage, all you frikkin need is a desk lamp and then you are really hard to kill, 

Seriously, they are really really powerful

Anyways, adam's idea does sound neat

**Comment by ghost** [comment]
you can't heal from crit as a phytosian

only podpeople heal in crit

btw remove podpeople from code

@ShadowDeath6 you suck at knowing things

**Comment by ShadowDeath6** [comment]
How do I suck at knowing things >:^(
