### ISSUE TITLE
Make lube more visible

### ISSUE THREAD

**Issue by EMT321** [yogstation13/yogstation-classic#993]
### Expected Behaviour

Have a glimpse of a lubed surface, thus avoiding an 8 second stun which is impossible to avoid by walking, galoshes, or any non-traitor gear aside from active meth usage.
### Actual Behaviour

Lube is nigh-invisible, and there exists no counter to it other then crowbarring the tile. At which point it can be lubed again, and then there is no counter at all. While an outright counter is not what I am advocating for due to balance, I feel making it slightly more visible would alleviate some of the hallways of death without a station-based counter.

Heres an example of how subtle it currently is: Just a few pixels in a corner.: 
https://gyazo.com/720313fed48893885ee96968ac58807f

Much harder to spot when moving through an area, and not zoomed in: 
https://gyazo.com/042fc9811c3f249531d13e7758d49781
### Steps to reproduce the problem
1. Repeatedly lube an area around you.
2. Laugh at everyone running into it.
3. Pick between the helpless fully armored HoS, Captain, and janitor, all of whom are stunned regardless of equipment.

**Comment by Groudonmaster** [comment]
Already nerfed enough it looks like water and magboots should counter them

**Comment by ghost** [comment]
Giving them a shiny wet overlay, like /tg/ did water, would be useful.

Giving both water and lube the overlay, so you can't tell the difference between them.

Perhaps one or two pairs of security magboots with only 50% slowdown could spawn in the sec Suit Storage Units in the armory.

**Comment by Super3222** [comment]
Lube was already nerfed to look like water. Maybe if you examine the tile, it should make the tile seem suspicious.

**Comment by Super3222** [comment]
Lube was already nerfed to look like water. Maybe if you examine the tile, it should make the tile seems suspicious.

**Comment by EMT321** [comment]
> Lube was already nerfed to look like water

I'm not really seeing this as a nerf.

**Comment by Cruix** [comment]
It used to be totally invisible.

**Comment by Super3222** [comment]
@EMT321 Eh, lube use to be completely invisible which was a nightmare when encountering a competent traitor chemist as Sec. /tg/ decided to make it look like water.

Seeing what Adam has said about a new overlay for both water and lube wouldn't hurt, I GUESS. An examine to differentiate them as well.

**Comment by EMT321** [comment]
Currently you can lube a floor, and have the HoS in full armor knocked down for long enough to crit them with a crowbar. If its gonna be a hard counter to security, at least make it visible.Currently the only real counterplay sec has is shutting off gravity or forcing the CE to give up magboots/getting some from R&D. 

In example 1, now everyone has super speed.

 In example 2, it takes at least 5-10 minutes to get all the materials for it and have R&D allow it, and now you move at 1/4 speed while the other guy dances around you beating you to death, Whereas lube can be made in 30 seconds from roundstart. 

Someone running away and spraying 5u of lube down the hall shouldn't be a hard counter to everything.

**Comment by ghost** [comment]
Hence security magboot suggestion.

Or give security a box of drying agent foam grenades.

That being said, security is already very strong-they really don't need to have a counter to every department. They have riot shields for constructs, revs, most cultists, and lings, not to mention cargo, botany, and xenobio, they have floodlights for shadowlings, tazers and beamspam disablers for anyone without stun resistance, bulletproof armor for gangs and angry cargo, riot gear for blobs, flashbangs and pepperspray grenades for any team antag or riots, ablative armor for almost anyone with a ranged weapon, biosuits for traitor virologists and chemists trying to inject them, they have ion rifles for borgs and mecha-

Granted, all of these counters can be stopped with preparation, but the fact that they exist is usually deterrence enough. Sec doesn't need a counter to EVERY department-they don't need a way to nullify space lube or water or clown pda's.

The most they need is to be able to see it;otherwise they can get magboots from eva, use stun resist chems or, gasp, avoid running right into a trap and instead ambush the guy somewhere that is not a dark, featureless maintenence hall that he has filled with lube.

Because imo being able to see space lube or water clearly is a good enough counter to it-but you deserve to get robusted if the entire security team runs down one maintenence shaft from one direction and chain slips on lube they didn't bother to consider someone having and the entire security team gets killed in one go from the short (in terms of killing a crowd, lube stun is p short-it's only really good for 1v1) stun, and a lone officer, even the hos, deserves to get killed if they chase a known murderer down alone.

Sec doesn't need to be capable of stopping anyone with no effort from another department as one officer. Sec is a team-if a lone officer gets killed trying to arrest a known traitor with lube and he knows the traitor has lube and doesn't plan for it too bad for him-if you bring a buddy or drag beepsky with you that's usually more than enough counter.

**Comment by ghost** [comment]
So like I said give lube and water /tg/'s shiny overlay and that's all the change it needs.

**Comment by EMT321** [comment]
I agree with Adam on this. I'm just saying that a random tile with a dozen more pixels in a corner (as it currently stands) is not adequate for the stun it puts out. TG's more visible route seems a good one that doesn't buff too much.

**Comment by Groudonmaster** [comment]
HOW ABOUT. INSTEAD OF CHANGING THE ICON. WE CHANGE THE FORMULA FOR LUBE. SO THAT PEOPLE CAN'T INSTANTLY HAVE IT ANYMORE. HAVE IT REQUIRE A MATERIAL FROM ANOTHER DEPARTMENT FOR CHRISTS SAKE.

**Comment by ghost** [comment]
no
